define('layers/mbs/nls/richtexteditor_fi',{
'dijit/_editor/nls/commands':{"removeFormat":"Poista muotoilu","copy":"Kopioi","paste":"Liitä","selectAll":"Valitse kaikki","insertOrderedList":"Numeroitu luettelo","insertTable":"Lisää taulukko/muokkaa taulukkoa","print":"Tulosta","underline":"Alleviivaus","foreColor":"Edustaväri","htmlToggle":"HTML-lähde","formatBlock":"Kappaletyyli","newPage":"Uusi sivu","insertHorizontalRule":"Vaakasuuntainen viiva","delete":"Poista","appleKey":"⌘${0}","insertUnorderedList":"Numeroimaton luettelo","tableProp":"Taulukon ominaisuudet","insertImage":"Lisää kuva","superscript":"Korotettu","subscript":"Alennettu","createLink":"Luo linkki","undo":"Kumoa","fullScreen":"Vaihda koko näyttö","italic":"Kursivointi","fontName":"Fontin nimi","justifyLeft":"Tasaus vasemmalle","unlink":"Poista linkki","toggleTableBorder":"Ota taulukon kehys käyttöön/poista kehys käytöstä","viewSource":"Näytä HTML-lähde","ctrlKey":"Ctrl+${0}","fontSize":"Fonttikoko","systemShortcut":"Toiminto \"${0}\" on käytettävissä selaimessa vain näppäimistön pikatoiminnolla. Käytä seuraavaa: ${1}.","indent":"Sisennä","redo":"Tee uudelleen","strikethrough":"Yliviivaus","justifyFull":"Tasaus","justifyCenter":"Tasaus keskelle","hiliteColor":"Taustaväri","deleteTable":"Poista taulukko","outdent":"Ulonna","cut":"Leikkaa","_localized":{},"plainFormatBlock":"Kappaletyyli","toggleDir":"Vaihda suuntaa","bold":"Lihavointi","tabIndent":"Sarkainsisennys","justifyRight":"Tasaus oikealle"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Ei mitään","1":"xx-small","2":"x-small","formatBlock":"Muotoile","3":"small","4":"medium","5":"large","6":"x-large","7":"xx-large","_localized":{},"fantasy":"fantasy","serif":"serif","p":"Kappale","pre":"Esimuotoiltu","sans-serif":"sans-serif","fontName":"Fontti","h1":"Otsikko","h2":"Alatason otsikko","h3":"Alimman tason otsikko","monospace":"monospace","fontSize":"Koko","cursive":"cursive"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Edelliset valinnat","_localized":{},"nextMessage":"Lisää valintoja"}
,
'dijit/form/nls/validate':{"invalidMessage":"Annettu arvo ei kelpaa.","rangeMessage":"Tämä arvo on sallitun alueen ulkopuolella.","_localized":{},"missingMessage":"Tämä arvo on pakollinen."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Liitä Word-ohjelmasta","instructions":"Liitä sisältö Word-tiedostosta alla olevaan tekstikenttään. Kun lisättävä sisältö on mielestäsi valmis, napsauta Liitä-painiketta. Voit peruuttaa lisäyksen napsauttamalla Peruuta-painiketta.","_localized":{}}
});