define('layers/mbs/nls/richtexteditor_kk',{
'dijit/_editor/nls/commands':{"removeFormat":"Пішімді алып тастау","copy":"Көшіру","paste":"Қою","selectAll":"Барлығын таңдау","insertOrderedList":"Нөмірленген тізім","insertTable":"Кестені кірістіру/өңдеу","print":"Басып шығару","underline":"Асты сызылған","foreColor":"Алды түсі","htmlToggle":"HTML көзі","formatBlock":"Еже мәнері","newPage":"Жаңа бет","insertHorizontalRule":"Көлденең сызғыш","delete":"Жою","appleKey":"⌘${0}","insertUnorderedList":"Таңбалауыш тізім","tableProp":"Кесте сипаты","insertImage":"Суретті кірістіру","superscript":"Жолүсті","subscript":"Жоласты","createLink":"Сілтеме жасау","undo":"Болдырмау","fullScreen":"Толық экранды қосу","italic":"Көлбеу","fontName":"Қаріп атауы","justifyLeft":"Сол жақ бойынша туралау","unlink":"Сілтемені алып тастау","toggleTableBorder":"Кесте жиегін қосу","viewSource":"HTML көзін қарау","ctrlKey":"ctrl+${0}","fontSize":"Қаріп өлшемі","systemShortcut":"\"${0}\" әрекеті шолғышта тек пернелер тіркесімі арқылы қол жетімді. Қолдану ${1}.","indent":"Шегіндіру","redo":"Қайтару","strikethrough":"Сызылған","justifyFull":"Туралау","justifyCenter":"Ортасы бойынша туралау","hiliteColor":"Өң түсі","deleteTable":"Кестені жою","outdent":"Солға ығысу","cut":"Қиып алу","_localized":{},"plainFormatBlock":"Еже мәнері","toggleDir":"Бағытты қосу","bold":"Қалың","tabIndent":"Қойынды шегінісі","justifyRight":"Оң жақ бойынша туралау"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Ешбір","1":"xx-кіші","2":"x-кіші","formatBlock":"Пішім","3":"кіші","4":"орташа","5":"үлкен","6":"x-үлкен","7":"xx-үлкен","_localized":{},"fantasy":"fantasy","serif":"serif","p":"Еже","pre":"Алдын ала пішімделген","sans-serif":"sans-serif","fontName":"Қаріп","h1":"Тақырып","h2":"Ішкі тақырып","h3":"Ішкі-ішкі тақырып","monospace":"monospace","fontSize":"Өлшемі","cursive":"көлбеу"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Алдыңғы нұсқалар","_localized":{},"nextMessage":"Басқа нұсқалар"}
,
'dijit/form/nls/validate':{"invalidMessage":"Енгізілген мән жарамды емес.","rangeMessage":"Бұл мән ауқымнан тыс.","_localized":{},"missingMessage":"Бұл мән міндетті."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Word бағдарламасынан қою","instructions":"Мазмұнды Word бағдарламасынан төмендегі мәтін ұясына қойыңыз.  Кірістірілетін мазмұн дұрыс болса, қою түймешігін басыңыз.  Мәтінді кірістіруді доғару үшін болдырмау түймешігін басыңыз.","_localized":{}}
});