define('layers/mbs/nls/richtexteditor_fr',{
'dijit/_editor/nls/commands':{"removeFormat":"Supprimer la mise en forme","copy":"Copier","paste":"Coller","selectAll":"Sélectionner tout","insertOrderedList":"Liste numérotée","insertTable":"Insérer/Modifier un tableau","print":"Imprimer","underline":"Souligner","foreColor":"Couleur avant-plan","htmlToggle":"Source HTML","formatBlock":"Style de paragraphe","newPage":"Nouvelle page","insertHorizontalRule":"Règle horizontale","delete":"Supprimer","appleKey":"⌘${0}","insertUnorderedList":"Liste à puces","tableProp":"Propriété du tableau","insertImage":"Insérer une image","superscript":"Exposant","subscript":"Indice","createLink":"Créer un lien","undo":"Annuler","fullScreen":"Basculer en plein écran","italic":"Italique","fontName":"Nom de police","justifyLeft":"Aligner à gauche","unlink":"Supprimer le lien","toggleTableBorder":"Afficher/Masquer la bordure du tableau","viewSource":"Afficher la source HTML","ctrlKey":"ctrl+${0}","fontSize":"Taille de police","systemShortcut":"Action \"${0}\" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.","indent":"Retrait","redo":"Rétablir","strikethrough":"Barrer","justifyFull":"Justifier","justifyCenter":"Aligner au centre","hiliteColor":"Couleur arrière-plan","deleteTable":"Supprimer le tableau","outdent":"Retrait négatif","cut":"Couper","_localized":{},"plainFormatBlock":"Style de paragraphe","toggleDir":"Changer de sens","bold":"Gras","tabIndent":"Retrait de tabulation","justifyRight":"Aligner à droite"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Néant","1":"très très petite","2":"très petite","formatBlock":"Mise en forme","3":"petite","4":"moyenne","5":"grande","6":"très grande","7":"très très grande","_localized":{},"fantasy":"fantaisie","serif":"serif","p":"Paragraphe","pre":"Pré-mise en forme","sans-serif":"sans serif","fontName":"Police","h1":"En-tête","h2":"Sous-en-tête","h3":"Sous-sous-en-tête","monospace":"espacement fixe","fontSize":"Taille","cursive":"cursive"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Choix précédents","_localized":{},"nextMessage":"Plus de choix"}
,
'dijit/form/nls/validate':{"invalidMessage":"La valeur indiquée n'est pas correcte.","rangeMessage":"Cette valeur n'est pas comprise dans la plage autorisée.","_localized":{},"missingMessage":"Cette valeur est requise."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Coller depuis Word","instructions":"Collez le contenu Word dans la zone de texte ci-dessous. Quand le contenu à insérer vous convient, appuyez sur le bouton Coller. Pour annuler l'insertion du texte, utilisez le bouton Annuler.","_localized":{}}
});