define('layers/mbs/nls/richtexteditor_sk',{
'dijit/_editor/nls/commands':{"removeFormat":"Odstrániť formátovanie","copy":"Kopírovať","paste":"Prilepiť","selectAll":"Vybrať všetko","insertOrderedList":"Číslovaný zoznam","insertTable":"Vložiť/upraviť tabuľku","print":"Vytlačiť","underline":"Podčiarknuť","foreColor":"Farba popredia","htmlToggle":"Zdrojový kód HTML","formatBlock":"Štýl odseku","newPage":"Nová stránka","insertHorizontalRule":"Vodorovná čiara","delete":"Vymazať","appleKey":"⌘${0}","insertUnorderedList":"Zoznam s odrážkami","tableProp":"Vlastnosť tabuľky","insertImage":"Vložiť obrázok","superscript":"Horný index","subscript":"Dolný index","createLink":"Vytvoriť prepojenie","undo":"Späť","fullScreen":"Prepnúť na celú obrazovku","italic":"Kurzíva","fontName":"Názov písma","justifyLeft":"Zarovnať vľavo","unlink":"Odstrániť prepojenie","toggleTableBorder":"Prepnúť ohraničenie tabuľky","viewSource":"Zobraziť zdrojový kód HTML","ctrlKey":"Ctrl+${0}","fontSize":"Veľkosť písma","systemShortcut":"Akcia \"${0}\" je vo vašom prehliadači dostupná iba prostredníctvom klávesovej skratky. Stlačte ${1}.","indent":"Odsadiť","redo":"Znova","strikethrough":"Prečiarknuť","justifyFull":"Zarovnať k okrajom","justifyCenter":"Zarovnať na stred","hiliteColor":"Farba pozadia","deleteTable":"Odstrániť tabuľku","outdent":"Zmenšiť odsadenie","cut":"Vystrihnúť","_localized":{},"plainFormatBlock":"Štýl odseku","toggleDir":"Prepnúť smer","bold":"Tučné","tabIndent":"Odsadenie tabulátora","justifyRight":"Zarovnať vpravo"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Žiadny","1":"xx-small","2":"x-small","formatBlock":"Formát","3":"small","4":"medium","5":"large","6":"x-large","7":"xx-large","_localized":{},"fantasy":"fantasy","serif":"serif","p":"Odsek","pre":"Predformátované","sans-serif":"sans-serif","fontName":"Písmo","h1":"Hlavička","h2":"Podhlavička","h3":"Pod-podhlavička","monospace":"monospace","fontSize":"Veľkosť","cursive":"cursive"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Predchádzajúce možnosti","_localized":{},"nextMessage":"Viac možností"}
,
'dijit/form/nls/validate':{"invalidMessage":"Zadaná hodnota nie je platná.","rangeMessage":"Táto hodnota je mimo rozsah.","_localized":{},"missingMessage":"Táto hodnota je povinná."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Prilepiť z aplikácie Word","instructions":"Prilepte obsah z aplikácie Word do textového okienka dole. Keď ste spokojný s obsahom na vloženie, stlačte tlačidlo prilepenia. Ak chcete zrušiť vkladanie textu, stlačte tlačidlo zrušenia.","_localized":{}}
});