define('layers/mbs/nls/richtexteditor_ROOT',{
'dijit/_editor/nls/commands':{"removeFormat":"Remove Format","copy":"Copy","paste":"Paste","selectAll":"Select All","insertOrderedList":"Numbered List","insertTable":"Insert/Edit Table","print":"Print","underline":"Underline","foreColor":"Foreground Color","htmlToggle":"HTML Source","formatBlock":"Paragraph Style","newPage":"New Page","insertHorizontalRule":"Horizontal Rule","delete":"Delete","appleKey":"⌘${0}","insertUnorderedList":"Bullet List","tableProp":"Table Property","insertImage":"Insert Image","superscript":"Superscript","subscript":"Subscript","createLink":"Create Link","undo":"Undo","fullScreen":"Toggle Full Screen","italic":"Italic","fontName":"Font Name","justifyLeft":"Align Left","unlink":"Remove Link","toggleTableBorder":"Toggle Table Border","viewSource":"View HTML Source","ctrlKey":"ctrl+${0}","fontSize":"Font Size","systemShortcut":"The \"${0}\" action is only available in your browser using a keyboard shortcut. Use ${1}.","indent":"Indent","redo":"Redo","strikethrough":"Strikethrough","justifyFull":"Justify","justifyCenter":"Align Center","hiliteColor":"Background Color","deleteTable":"Delete Table","outdent":"Outdent","cut":"Cut","_localized":{"he":1,"zh-tw":1,"pt-pt":1,"nl":1,"kk":1,"tr":1,"bg":1,"ko":1,"el":1,"hr":1,"hu":1,"es":1,"eu":1,"bs":1,"uk":1,"id":1,"ca":1,"ro":1,"fi":1,"ru":1,"it":1,"fr":1,"cs":1,"ja":1,"sk":1,"da":1,"sl":1,"pl":1,"mk":1,"de":1,"sr":1,"sv":1,"pt":1,"al":1,"ar":1,"zh":1,"nb":1,"az":1,"th":1},"plainFormatBlock":"Paragraph Style","toggleDir":"Toggle Direction","bold":"Bold","tabIndent":"Tab Indent","justifyRight":"Align Right"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"None","1":"xx-small","2":"x-small","formatBlock":"Format","3":"small","4":"medium","5":"large","6":"x-large","7":"xx-large","_localized":{"he":1,"zh-tw":1,"pt-pt":1,"nl":1,"kk":1,"tr":1,"bg":1,"ko":1,"el":1,"hr":1,"hu":1,"es":1,"eu":1,"bs":1,"uk":1,"id":1,"ca":1,"ro":1,"fi":1,"ru":1,"it":1,"fr":1,"cs":1,"ja":1,"sk":1,"da":1,"sl":1,"pl":1,"mk":1,"de":1,"sr":1,"sv":1,"pt":1,"al":1,"ar":1,"zh":1,"nb":1,"az":1,"th":1},"fantasy":"fantasy","serif":"serif","p":"Paragraph","pre":"Pre-formatted","sans-serif":"sans-serif","fontName":"Font","h1":"Heading","h2":"Subheading","h3":"Sub-subheading","monospace":"monospace","fontSize":"Size","cursive":"cursive"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Previous choices","_localized":{"he":1,"zh-tw":1,"pt-pt":1,"nl":1,"kk":1,"tr":1,"bg":1,"ko":1,"el":1,"hr":1,"hu":1,"es":1,"eu":1,"bs":1,"uk":1,"id":1,"ca":1,"ro":1,"fi":1,"ru":1,"it":1,"fr":1,"cs":1,"ja":1,"sk":1,"da":1,"sl":1,"pl":1,"mk":1,"de":1,"sr":1,"sv":1,"pt":1,"al":1,"ar":1,"zh":1,"nb":1,"az":1,"th":1},"nextMessage":"More choices"}
,
'dijit/form/nls/validate':{"invalidMessage":"The value entered is not valid.","rangeMessage":"This value is out of range.","_localized":{"he":1,"zh-tw":1,"pt-pt":1,"nl":1,"kk":1,"tr":1,"bg":1,"ko":1,"el":1,"hr":1,"hu":1,"es":1,"eu":1,"bs":1,"uk":1,"id":1,"ca":1,"ro":1,"fi":1,"ru":1,"it":1,"fr":1,"cs":1,"ja":1,"sk":1,"da":1,"sl":1,"pl":1,"mk":1,"de":1,"sr":1,"sv":1,"pt":1,"al":1,"ar":1,"zh":1,"nb":1,"az":1,"th":1},"missingMessage":"This value is required."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Paste From Word","instructions":"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.","_localized":{"he":1,"zh-tw":1,"pt-pt":1,"nl":1,"kk":1,"tr":1,"bg":1,"ko":1,"el":1,"hr":1,"hu":1,"es":1,"eu":1,"bs":1,"uk":1,"id":1,"ca":1,"ro":1,"fi":1,"ru":1,"it":1,"fr":1,"cs":1,"ja":1,"sk":1,"da":1,"sl":1,"pl":1,"mk":1,"de":1,"sr":1,"sv":1,"pt":1,"ar":1,"zh":1,"nb":1,"th":1}}
});