define('layers/mbs/nls/richtexteditor_it',{
'dijit/_editor/nls/commands':{"removeFormat":"Rimuovi formato","copy":"Copia","paste":"Incolla","selectAll":"Seleziona tutto","insertOrderedList":"Elenco numerato","insertTable":"Inserisci/Modifica tabella","print":"Stampa","underline":"Sottolinea","foreColor":"Colore primo piano","htmlToggle":"Origine HTML","formatBlock":"Stile paragrafo","newPage":"Nuova pagina","insertHorizontalRule":"Righello orizzontale","delete":"Elimina","appleKey":"⌘${0}","insertUnorderedList":"Elenco puntato","tableProp":"Proprietà tabella","insertImage":"Inserisci immagine","superscript":"Apice","subscript":"Pedice","createLink":"Crea collegamento","undo":"Annulla","fullScreen":"Attiva/Disattiva schermo intero","italic":"Corsivo","fontName":"Nome carattere","justifyLeft":"Allinea a sinistra","unlink":"Rimuovi collegamento","toggleTableBorder":"Attiva/Disattiva bordo tabella","viewSource":"Visualizza origine HTML","ctrlKey":"ctrl+${0}","fontSize":"Dimensione carattere","systemShortcut":"La azione \"${0}\" è disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.","indent":"Rientro","redo":"Ripristina","strikethrough":"Barrato","justifyFull":"Giustifica","justifyCenter":"Allinea al centro","hiliteColor":"Colore sfondo","deleteTable":"Elimina tabella","outdent":"Annulla rientro","cut":"Taglia","_localized":{},"plainFormatBlock":"Stile paragrafo","toggleDir":"Attiva/Disattiva direzione","bold":"Grassetto","tabIndent":"Rientro tabulazione","justifyRight":"Allinea a destra"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Nessuna","1":"piccolissimo","2":"molto piccolo","formatBlock":"Formato","3":"piccolo","4":"medio","5":"grande","6":"molto grande","7":"grandissimo","_localized":{},"fantasy":"fantasy","serif":"serif","p":"Paragrafo","pre":"Preformattato","sans-serif":"sans-serif","fontName":"Carattere","h1":"Intestazione","h2":"Sottointestazione","h3":"Sottointestazione secondaria","monospace":"spaziatura fissa","fontSize":"Dimensione","cursive":"corsivo"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Scelte precedenti","_localized":{},"nextMessage":"Scelte successive"}
,
'dijit/form/nls/validate':{"invalidMessage":"Il valore immesso non è valido.","rangeMessage":"Questo valore è fuori dall'intervallo consentito.","_localized":{},"missingMessage":"Questo valore è obbligatorio."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Incolla da Word","instructions":"Incollare i contenuti da Word nella seguente casella di testo. Quando si è deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.","_localized":{}}
});