define('layers/mbs/nls/richtexteditor_hr',{
'dijit/_editor/nls/commands':{"removeFormat":"Ukloni oblikovanje","copy":"Kopiraj","paste":"Zalijepi","selectAll":"Izaberi sve","insertOrderedList":"Numerirani popis","insertTable":"Umetni/Uredi tablicu","print":"Ispis","underline":"Podcrtaj","foreColor":"Boja prednjeg plana","htmlToggle":"HTML izvor","formatBlock":"Stil odlomka","newPage":"Nova stranica","insertHorizontalRule":"Vodoravno ravnalo","delete":"Izbriši","appleKey":"⌘${0}","insertUnorderedList":"Popis s grafičkim oznakama","tableProp":"Svojstvo tablice","insertImage":"Umetni sliku","superscript":"Superskript","subscript":"Indeks","createLink":"Kreiraj vezu","undo":"Poništi","fullScreen":"Prebaci na potpun ekran","italic":"Kurziv","fontName":"Ime fonta","justifyLeft":"Poravnaj lijevo","unlink":"Ukloni vezu","toggleTableBorder":"Prebaci rub tablice","viewSource":"Pogledaj HTML izvor","ctrlKey":"ctrl+${0}","fontSize":"Veličina fonta","systemShortcut":"\"${0}\" akcija je dostupna jedino u vašem pregledniku upotrebom prečice tipkovnice. Koristite ${1}.","indent":"Uvuci","redo":"Ponovno napravi","strikethrough":"Precrtaj","justifyFull":"Poravnaj","justifyCenter":"Centriraj","hiliteColor":"Boja pozadine","deleteTable":"Izbriši tablicu","outdent":"Izvuci","cut":"Izreži","_localized":{},"plainFormatBlock":"Stil odlomka","toggleDir":"Prebaci smjer","bold":"Podebljaj","tabIndent":"Tabulator uvlačenja","justifyRight":"Poravnaj desno"}
,
'dijit/_editor/nls/FontChoice':{"noFormat":"Nijedan","1":"vrlo vrlo malo","2":"vrlo malo","formatBlock":"Oblikovanje","3":"malo","4":"srednje","5":"veliko","6":"vrlo veliko","7":"vrlo vrlo veliko","_localized":{},"fantasy":"fantastika","serif":"serif","p":"Odlomak","pre":"Prethodno formatirano","sans-serif":"sans-serif","fontName":"Font","h1":"Naslov","h2":"Podnaslov","h3":"Pod-podnaslov","monospace":"jednaki razmak","fontSize":"Veličina","cursive":"rukopisni"}
,
'dijit/form/nls/ComboBox':{"previousMessage":"Prethodni izbori","_localized":{},"nextMessage":"Više izbora"}
,
'dijit/form/nls/validate':{"invalidMessage":"Unesena vrijednost nije važeća.","rangeMessage":"Ova vrijednost je izvan raspona.","_localized":{},"missingMessage":"Potrebna je ova vrijednost."}
,
'dojox/editor/plugins/nls/PasteFromWord':{"pasteFromWord":"Zalijepi iz Worda","instructions":"Zalijepite sadržaj iz Worda u donji tekstni okvir. Kad ste zadovoljni sa sadržajem za umetanje, pritisnite tipku Zalijepi.  Za prekid umetanja teksta, pritisnite tipku Opoziv.","_localized":{}}
});