define("dojo/_base/lang dojo/_base/declare dojo/dom-geometry dojo/dom dojo/dom-style dojo/dom-attr dojo/_base/window dojo/Deferred dojo/dom-construct dojo/_base/array dojo/aspect dojo/window com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(n,p,l,v,k,w,x,y,h,z,q,m,r,t,g,u){return p([r,t,u],{jsoneditor:null,i18nJElabels:null,options:null,sizetoparentdomid:null,dom:null,
currentMode:"code",onChangeTimedOut:!0,constructor:function(a){this.options=a;this.sizetoparentdomid=a.sizetoparentdomid;this.dom=a.dom?a.dom:this.domNode;a.loglevel&&(g.LOG_LEVEL=a.loglevel);g.debug("{} options",this.TAG,a)},startup:function(){this.inherited(arguments);window.JSONEditor&&this.createUI(null)},createUI:function(){this.dom||(dnode=this.domNode);g.debug("Creating JSONEditor UI");thisJEObjectObj=this;var a=h.create("div",{id:"jsonEditorID",width:"100%","margin-left":"20px"});h.place(a,
this.domNode,"first");var d=this.jsonEditorOptions();this.fetch("get_i18n_JELabels").then(function(c){thisJEObjectObj.i18nJElabels=c;thisJEObjectObj.fetch("getSymbologyConfig").then(function(c){var b=c.json,e=c.jsonSchema;c=thisJEObjectObj.rootUrl+"/libraries/jsoneditor/jsoneditor.min.js";0==thisJEObjectObj.options.loglevel&&(c=thisJEObjectObj.rootUrl+"/libraries/jsoneditor/jsoneditor.js");require([c],function(c){e&&""!=e&&(d.schema=e);thisJEObjectObj.jsoneditor=new c(a,d,b,thisJEObjectObj.i18nJElabels);
thisJEObjectObj.updateEditorMenu()})})});this._resize();q.after(window,"onresize",n.hitch(this,this._deferredResize))},resize:function(){this._resize()},_resize:function(){console.log("_resize occured");var a=this.onMeasure(),d=document.getElementById("jsonEditorID"),c=document.getElementById("JSONEditor_outer");g.debug("{}: resize() called with measure",this.TAG,a);if(a&&(a.w||a.h)){a.w.replace("px","");var f=Number(a.h.replace("px",""));if(this.fillHeight){var b=m.getBox(),e=l.position(this.domNode);
a.w=b.w-e.x-this.PAD-25+"px"}a.h=f-this.getHeightPad()+"px"}else a&&(a.width||a.height)?(a.width.replace("px",""),f=Number(a.height.replace("px","")),this.fillHeight&&(b=m.getBox(),e=l.position(this.domNode),a.width=b.w-e.x-this.PAD-25+"px"),a.height=f-this.getHeightPad()+"px"):g.warn("Failed to calculate size of miniapp??",a);k.set(this.domNode,a);null!=d&&(this.setDomStyle(d,c,a),this.refreshData())},_removeOldEditor:function(){null!=this.jsoneditor&&(g.debug("{} Cleaning up jsoneditor",this.TAG),
this.clearHandlers&&this.clearHandlers())},destroy:function(){this._removeOldEditor();this.inherited(arguments)},onRefreshRequested:function(a){g.debug("Refresh UI -- nothing to refresh");g.debug(a)},jsonEditorOptions:function(){return{mode:"code",modes:["code","form","text","tree","view"],enableSort:!1,enableTransform:!1,onError:function(a){alert(a.toString())},onModeChange:function(a,d){thisJEObjectObj.currentMode=a;thisJEObjectObj._onModeChange&&thisJEObjectObj._onModeChange();console.log("Mode switched from",
d,"to",a)}}},getHeightPad:function(){return 50},setDomStyle:function(a,d,c){k.set(d,{width:"100%"});k.set(a,c)},_deferredResize:function(){var a=this;setTimeout(function(){a._resize()},300)},refreshData:function(){if(this.jsoneditor&&"code"==thisJEObjectObj.currentMode){var a=this.jsoneditor.get();this.jsoneditor.set(a)}},onChange:function(){function a(){var a=dojo.byId("ValidationID");try{var b=thisJEObjectObj.jsoneditor.get();thisJEObjectObj.onChangeTimedOut=!0;var d=JSON.stringify(b);a&&h.destroy("ValidationID");
stopFocus=!0;thisJEObjectObj.sendMaximoEvent("editChange",{change:d},thisJEObjectObj.componentId)}catch(g){thisJEObjectObj.onChangeTimedOut=!0,console.error("JSON Structure Validation Failed onUpdate",g),a||(a=dojo.byId("JSONEditor_outer"),h.create("div",{id:"ValidationID",title:"Validation Titel",innerHTML:c,style:"color:Red;font-size:150%;text-align:center;"},a,"first"))}}console.log("onUpdate --JSONEditor");var d=dojo.byId("ValidationID"),c=thisJEObjectObj.i18nJElabels.jsonStructureError;null==
c&&(c="JSON Structure Error -- Please Correct<br>Any additional modifications will not be saved and will be lost when navigated away from this page!!");thisJEObjectObj.onChangeTimedOut&&(thisJEObjectObj.onChangeTimedOut=!1,window.setTimeout(a,1E3));try{thisJEObjectObj.jsoneditor.get(),d&&h.destroy("ValidationID")}catch(f){console.error("Validation Failed onUpdate",f),d||(d=dojo.byId("JSONEditor_outer"),h.create("div",{id:"ValidationID",title:"Validation Titel",innerHTML:c,style:"color:Red;font-size:150%;text-align:center;"},
d,"first"))}},_onModeChange:function(){this.updateEditorMenu()},updateEditorMenu:function(){var a=this.jsoneditor,d=this.i18nJElabels,c=document.createElement("button");c.type="button";c.className="jsoneditor-modes";c.onclick=function(){};var f=document.createElement("div");f.className="jsoneditor-modes";f.style.position="relative";f.style["float"]="right";var b=document.querySelector(".jsoneditor-menu a.jsoneditor-poweredBy");b&&(b.style.display="none");if(b=document.querySelector(".jsoneditor-search"))b.style["float"]=
"right",b.style.position="relative";a.options.onHelp&&(b=c.cloneNode(!0),b.title=d.configAssistance,b.style.backgroundImage="url(jsoneditor/btn_help.gif)",b.style.backgroundRepeat="no-repeat",b.style.backgroundPosition="center",b.style["float"]="right",b.onclick=function(){a.options.onHelp()},a.menu.appendChild(b));if("code"===a.mode&&a.options.showGraph){b=c.cloneNode(!0);b.type="button";b.innerHTML=d.graph;b.title=d.graphTitle;b.onclick=function(){a.options.showGraph()};var e=f.cloneNode(!0);e.appendChild(b);
a.menu.appendChild(e)}a.options.onRestore&&(b=c.cloneNode(!0),b.type="button",b.innerHTML=d.restore,b.title=d.restoreConfig,b.onclick=function(){a.options.onRestore()},e=f.cloneNode(!0),e.appendChild(b),a.menu.appendChild(e));a.options.onUpdate&&(c=c.cloneNode(!0),c.innerHTML=d.update,c.title=d.updateConfig,c.onclick=function(){a.options.onUpdate()},d=f.cloneNode(!0),d.style["float"]="left",d.appendChild(c),a.menu.appendChild(d))}})});
