define("dojo/_base/lang dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog ibm/miniapp/scheduler/gantt/GanttWidget com/ibm/tivoli/maximo/miniapps/Handlers ibm/miniapp/scheduler/dispatch/MapUtil ibm/miniapp/scheduler/dispatch/DispatchViewActions dojo/dom-geometry dojo/dom-style".split(" "),function(g,n,p,e,q,l,u,v,w,x){var y=JSON.stringify([235,255,255]),z=JSON.stringify([224,244,244]),A=JSON.stringify([211,228,244]),B=JSON.stringify([191,228,244]);
return n([q,p,l,v],{constructor:function(a){e.debug("{} Base Bean Target set to {} for view",this.gridId,this.mxtargetbean,a);this.mapReady=!1;this.firstTime=!0;this.initMap();this.showMessage=null;this.undoingChanges=!1;this.alternateRowIDs=[];null!=window.timeoutId&&window.clearTimeout(window.timeoutId);Array.prototype.remove||Object.defineProperty(Array.prototype,"remove",{value:function(){for(var a,b=arguments,e=b.length,f;e&&this.length;)for(a=b[--e];-1!==(f=this.indexOf(a));)this.splice(f,1);
return this},enumerable:!1,writable:!0,configurable:!0});var b=this;(function(){var a=sendEvent;sendEvent=function(d,e,f){"click"==d&&b.cancelAutoRefresh();a(d,e,f)}})();window.onclick=function(a){if("click"==a.type&&a.target&&a.target.attributes&&0<a.target.attributes.length&&"closeBtn"==a.target.attributes[0].value)for(a=document.getElementsByClassName("dijitPopup dijitMenuPopup"),i=0;i<a.length;i++)a[i].style.display="none"};if(e.isDebug())try{dojo.config.fwm.debug=!0}catch(c){}},addCustomActions:function(a){window.Grids.ZoomToWork=
g.hitch(this,this.ZoomToWork)},destroy:function(){this.inherited(arguments);null!=window.timeoutId&&window.clearTimeout(window.timeoutId);delete window.dispatcher},isResourceView:function(){return!0},shouldRightClickSelectRow:function(a,b,c){return!1},initMap:function(){e.debug("Begin Init Map");(new u({dispatchView:this})).checkForMap();e.debug("End Init Map")},setMapReady:function(a){this.mapReady=a;e.debug("MAP READY: {}",this.mapReady)},OnAfterSave:function(a,b,c){this.inherited(arguments);var d=
this;null!=this.showMessage&&this.grid.ShowMessageTime(this.showMessage,0,function(a){d.showMessage=null;2==a&&(d.undoingChanges=!0,d.grid.DoUndo())},["Yes","Cancel"]);d.undoingChanges=!1},OnUpdateRow:function(a,b,c){this.inherited(arguments);if(b.parentNode&&b.Moved&&2<=b.Moved){var d=b.parentNode,e=!1;"LABOR"==d._REFOBJECTNAME||"AMCREW"==d._REFOBJECTNAME?(b.ACTIVITY_RENDER_COLOR=d.ACTIVITY_RENDER_COLOR,b.ACTIVITY_FONT_COLOR=d.ACTIVITY_FONT_COLOR,delete b._INTERNALSTATUS,e=!0):"CRAFT"!=d._REFOBJECTNAME&&
"AMCREWT"!=d._REFOBJECTNAME||b._INTERNALSTATUS||(b.STATUS="WAITASGN",b._INTERNALSTATUS="WAITASGN",e=!0);b.ERRVAL&&this.undoingChanges&&(delete b.ERRVAL,e=!0);e&&(this.grid.RefreshRow(d),this.grid.RefreshRow(b));this._updateRoutes()}b.parentNode&&b.Changed&&1<=b.Changed&&("LABOR"==b._REFOBJECTNAME||"AMCREW"==b._REFOBJECTNAME)&&(b.GGanttPoints=c.GGanttPoints,b.GGanttPointsEdit=c.GGanttPointsEdit,b.GGanttPointsIcons=c.GGanttPointsIcons,b.GGanttPointsIDs=c.GGanttPointsIDs,b._NWPARTS=c._NWPARTS,this.grid.RefreshRow(b));
null==c||null==c._WARNINGMESSAGE||this.undoingChanges||(this.showMessage=c._WARNINGMESSAGE)},OnGetDefaultColor:function(a,b,c,d,e,f){return(30<b.Height||b.ERRVAL&&0<b.ERRVAL)&&"RESDESCRIPTION"==c?this._conflictRowColor:null},_newTreeGridOptions:function(){var a={appname:this.appname,projectid:null,addShiftInfo:!0,resObj1:null,resKey1:null};return{Data:{Url:this.toUrl("async_load_dispatch_data",this._ioOptions(a)),Timeout:300},Layout:{Url:this.toUrl("async_load_dispatch_ui",this._ioOptions(a))}}},
jsCallback:function(a,b){this[a]?(e.debug("{}: jsCallback: ",this.TAG,a,b),g.hitch(this,this[a]).apply(this,[b])):e.error("{}: Missing Callback Function: {}",this.TAG,a)},updateProjId:function(a){e.error("{}: updateProjId() not implemented",this.TAG)},onSLRTravelTimeUpdated:function(a){e.debug("{}: onSLRTravelTimeUpdated called with data as {}",this.TAG,typeof a,a);"string"==typeof a&&(a=JSON.parse(a));var b=this;if(a&&0<a.totalToUpdate)if(e.debug("Need to reload model travel time"),1==a.ganttReloadNeeded)this.fetch("on_reload_model_for_traveltime").then(function(a){b.Reload()},
function(a){e.debug("ERROR:",a)});else{a=a.updatedResources;if(null!=a)for(var c=0;c<a.length;c++){var d=a[c],h=b.grid.GetRowById(d.id);h.GGanttPoints=d.GGanttPoints;h.GGanttPointsEdit=d.GGanttPointsEdit;h.GGanttPointsIcons=d.GGanttPointsIcons;h.GGanttPointsIDs=d.GGanttPointsIDs;h._NWPARTS=d._NWPARTS;b.grid.RefreshRow(h)}b.grid.RefreshGantt(1)}},attachExtraGridEvents:function(a){TGAddEvent("OnGanttTip",a,g.hitch(this,this.OnGanttTip));TGAddEvent("OnScroll",a,g.hitch(this,this.OnScroll));TGAddEvent("OnExpand",
a,g.hitch(this,this.OnExpandOrCollapse));TGAddEvent("OnGetDefaultColor",a,g.hitch(this,this.OnGetDefaultColor));TGAddEvent("OnUpdateRow",a,g.hitch(this,this.OnUpdateRow));TGAddEvent("OnSizeError",a,g.hitch(this,this.OnSizeError));this.subscribeOn("scheduler.ZoomToStart",g.hitch(this,this.zoomToStart));this.subscribeOn("scheduler.dispatch.refresh",g.hitch(this,this.refreshSchedule))},OnExpandOrCollapse:function(a,b){this._updateRoutes()},refreshSchedule:function(){this.domNode&&(this.dispatchGridWidth=
this.domNode.clientWidth);this.grid&&(this.dispatchGridLeftWidth=this.grid.GetBodyWidth(0),this.dispatchGridMidWidth=this.grid.GetBodyWidth(1),this.dispatchGridRightWidth=this.grid.GetBodyWidth(2));var a=this;this.fetch("on_reload_model_for_traveltime").then(function(b){a.Reload()},function(a){e.debug("ERROR:",a)})},getWeatherParams:function(a){var b={};e.debug("WEATHER ROW",a);a.WORKORDERID&&(b.oname="WORKORDER",b.objectid=a.WORKORDERID,b.wonum=a.WONUM,b.start=a.startTime,b.end=a.endTime);return b},
Reload:function(a){e.debug("Reload Called");if(a){var b=function(){e.debug("Removing Reload Callback Handler");TGDelEvent("OnReady",this.gridId,b);a()};e.debug("Added Reload Callback Handler");TGAddEvent("OnReady",this.gridId,b,b)}this.grid.Reload();this.firstTime=!0},ReloadModel:function(){e.debug("Reload Model Called");var a=this;this.fetch("on_reload_model_for_traveltime").then(function(b){a.Reload()},function(a){e.debug("ERROR:",a)})},OnScroll:function(a,b,c,d,h,f,C,k,m){m!=k&&(e.debug("Scrolling Gantt: OLD: {}, new: {}",
m,k),this.invokeLater(g.hitch(this,this._updateRoutes),300,"OnScrollUpdateRoutes"))},OnSelectRow:function(a,b,c){this.inherited(arguments);this._updateRoutes()},zoomToStart:function(){this.zoomToDay(this.grid.Cols.G.GanttChartMaxStart)},zoomToDay:function(a){a=a instanceof Date?a.getTime():a;a=new Date(a);a.setHours(0,0,0,0);a=a.getTime();var b=a+this.DURATION_ONE_DAY,c=this.getRoutesForRange(a,b);c&&0<c.length?(a=this.getMinMaxStartEndForRoutes(c),e.debug("Adjusted Start: {}, End: {}",new Date(a.start),
new Date(a.end),a.startItem,a.endItem),this.grid.ZoomTo(a.start-this.DURATION_ONE_HOUR,a.end+this.DURATION_ONE_HOUR,null)):(e.debug("ZoomToDay: start {}, end: {}",new Date(a),new Date(b)),this.grid.ZoomTo(a,b,null))},getMinMaxStartEndForRoutes:function(a){var b={start:Math.pow(2,53),end:Math.pow(-2,53)};a.forEach(function(a){a.startTime<b.start&&(b.start=a.startTime,b.startItem=a);a.endTime>b.end&&(b.end=a.endTime,b.endItem=a)},this);return b},_GetAltCSSClassForActivity:function(a){},OnGanttTip:function(a,
b,c,d,h,f){e.debug("gantt tip: tip: {}",h);return d},GetBarStyle:function(a){var b="";a.ACTIVITY_RENDER_COLOR&&(b+="background-color: "+a.ACTIVITY_RENDER_COLOR+";");a.ACTIVITY_FONT_COLOR&&(b+="color: "+a.ACTIVITY_FONT_COLOR+";");return b},OnGetGanttBarHtml:function(a,b,c,d,e,f,g,k,m,n,p,r,q){if("STARTLOCATION"==b.FWMTYPE)return"<div class='dispatch-start'></div>";var t=this.inherited(arguments),l=this.GetBarStyle(b);return'<div class="'+r[2]+'" style="'+l+'" ><span class="'+r[3]+'">'+(t?t:"")+"</span></div>"},
OnFocus:function(a,b,c,d,e,f){},OnRenderFinish:function(a){this.inherited(arguments);window.dispatcher&&window.dispatcher.map||this.publishTo("readyToCreateMap",!0);if(this.firstTime){this.firstTime=!1;e.debug("Dispatch Render Finish.  Refocus to 1 Day Zoom.");var b=this;this.invokeLater(function(){0==a.GetScrollLeft(2)&&b.zoomToStart();var c=a.GetSelRows();c&&0!=c.length||(e.debug("Selecting ALl Rows, since None Are Selected"),a.SelectAllRows(1));window.dispatcher&&window.dispatcher.map&&b._updateRoutes();
null!=window.timeoutId&&window.clearTimeout(window.timeoutId);b.options.scheduler_plus_license&&(window.timeoutId=setTimeout(function(){b._autoRefreshData(b)},b.dispatchRefreshInterval))},100);for(i=0;i<this.alternateRowIDs.length;i++){var c=a.GetRowById(this.alternateRowIDs[i]);if(c&&c.GGanttBackground){var d=c.GGanttBackground,d=d.split("White").join("WORKAlternate");c.GGanttBackground=d;a.RefreshRow(c)}}}a.RefreshGantt(255)},_updateRoutes:function(){this.invokeLater(g.hitch(this,this.updateRoutesForTimes),
150,"_updateRoutes")},getRoutesForRange:function(a,b){var c=[];this.visitRow(this.grid.Body,{},function(d){d.startTime>=a&&d.endTime<=b&&c.push(d);return!0});return c},onlyExpandedRows:function(a){if(!a)return null;for(var b=[],c=0;c<a.length;c++)this.isRowVisible(a[c].parentNode)&&b.push(a[c]);return b},GetSelectedRowIds:function(a){var b="",c="",d;for(d in a)b=b+c+a[d].id,c=",";return b},isRowVisible:function(a){return a?0>a.Level||"ROOT"==a.id?!0:a.firstChild&&!a.Expanded?!1:a.parentNode?this.isRowVisible(a.parentNode):
!0:!1},updateRoutesForTimes:function(a){var b=this;if(this.grid){var c=this.onlyExpandedRows(this.grid.GetSelRows());if(c&&0<c.length){var d=this.getVisibleRange();e.debug("{}: updateRoutes: Processing {} Rows, Dates: ",this.TAG,c.length,d);e.debug("{}: Date Range: start: {}, end: {}",this.TAG,new Date(d.start),new Date(d.end));var h=this.GetSelectedRowIds(c);this.fetch("async_get_route_details_for_resources",b._ioOptions({resources:h.split(","),start_time:d.start,end_time:d.end,refresh_options:a||
{}})).then(function(a){e.debug("WE GOT OUR ROUTE DATA",a);b.clearRoutes();b.drawRoutes(a,h)});window.dispatcher&&(e.debug("{}: Getting Unassigned work for dates",this.TAG,d),window.dispatcher.updateUnAssignWODates(this.TGDateToUserTZDate(d.start),this.TGDateToUserTZDate(d.end)))}else this.clearRoutes()}},drawRoutes:function(a,b){if(a&&a.allRoutes)if(window.dispatcher&&window.dispatcher.drawAllRoutes)e.debug("Telling Dispatcher to draw routes..."),window.dispatcher.drawAllRoutes(a,null,null);else{var c=
this;this.invokeLater(function(){e.debug("Waiting for 'dispatcher' and then we can draw routes");c.drawRoutes(a,b)},100,"drawRoutes")}else e.warn("No ROUTES for {}",b)},clearRoutes:function(){window.dispatcher?window.dispatcher.clearAllCurrentRoutes():e.debug("No Dispatcher, Ignore Routes")},highlightactivity:function(a){var b=this.findRowByIDX(a);e.debug("HIGHLIGHT ACTIVITY called from the Map: {}",a,b);b&&this.focusGanttBar(b)},updateModelWithOptions:function(a){this.domNode&&(this.dispatchGridWidth=
this.domNode.clientWidth);this.grid&&(this.dispatchGridLeftWidth=this.grid.GetBodyWidth(0),this.dispatchGridMidWidth=this.grid.GetBodyWidth(1),this.dispatchGridRightWidth=this.grid.GetBodyWidth(2));"string"==typeof a&&(a=JSON.parse(a));if(a){this.clearRoutes();var b=this;this.fetch("on_reload_model_for_traveltime").then(function(c){a&&a.hasCallback&&window.dispatcher&&window.dispatcher._refreshInfo?b.Reload(window.dispatcher._refreshInfo.callback):b.Reload()},function(a){e.debug("ERROR:",a)})}},_focusGanttBarAdditionalActions:function(a){a&&
a._idx&&window.dispatcher&&(e.debug("Notify Map about Selected Item XXXXX: {}",a._idx),window.dispatcher.highlightStop(a._idx))},findRowByIDX:function(a){return this.grid.GetRowById(a,"_idx",!1)},resize:function(){this.inherited(arguments);if(null!=document.getElementById("m35629182-mapcontrol_components_h1_0")){var a=w.position("m35629182-mapcontrol_components_h1_0"),b=a?a.h:0;b&&300<b?(x.set(this.domNode,{height:b+"px"}),e.debug("{}: Updated Dispatch Height to match the map: {}",this.TAG,b)):e.debug("{}: Ignore Map Size",
this.TAG,a)}},OnSizeError:function(a,b,c){this.dispatchGridWidth&&this.dispatchGridLeftWidth&&this.dispatchGridMidWidth&&this.dispatchGridRightWidth&&(this.domNode.style.width=this.dispatchGridWidth+"px",a.LeftWidth=this.dispatchGridLeftWidth,a.MidWidth=this.dispatchGridMidWidth,a.RightWidth=this.dispatchGridRightWidth,a.Update());return!0},_autoRefreshData:function(a){this.fetch("async_auto_refresh_model",a._ioOptions({projectid:a.projectid})).then(function(b){if(b&&b.Changes&&b.Changes.length){for(var c=
b.Changes,d=[],e=!1,f=0;f<c.length;f++){var g=c[f];if(null!=g.Parent){var k=a.grid.GetRowById(g.Parent);g.ACTIVITY_RENDER_COLOR=k.ACTIVITY_RENDER_COLOR;g.ACTIVITY_FONT_COLOR=k.ACTIVITY_FONT_COLOR}d.push(g.id)}a.grid.AddDataFromServer(b);for(b=0;b<d.length;b++)f=a.grid.GetRowById(d[b]),null!=f&&(f.name=c[b].name,f._idx=c[b]._idx,f.HASTRAVELTIME=c[b].HASTRAVELTIME,f.TRAVELTIME_SECS=c[b].TRAVELTIME_SECS,f.mxRightIconClass=c[b].mxRightIconClass,f.mxLeftIconClass=c[b].mxLeftIconClass,null!=g.Parent&&(e=
!0,k=g.Parent,k.includes("CRAFT")||k.includes("AMCREWT")?(f._OBJECTNAME=c[b]._OBJECTNAME,f._REFOBJECTNAME=c[b]._REFOBJECTNAME,f._INTERNALSTATUS=c[b]._INTERNALSTATUS,f.STATUS=c[b].STATUS):delete f._INTERNALSTATUS),0!=(f.ERRVAL&a.ERRORS.ERR_CONFLICT_DOUBLE_BOOKED)&&(f.Height=34,f.MaxHeight=34,f.GGanttPointsTop=0,a.grid.RefreshRow(f)));a.grid.RefreshGantt(1);e&&a._updateRoutes()}window.clearTimeout(window.timeoutId);window.timeoutId=setTimeout(function(){a._autoRefreshData(a)},a.dispatchRefreshInterval)})},
cancelAutoRefresh:function(){null!=window.timeoutId&&window.clearTimeout(window.timeoutId)},onRefreshRequested:function(a){this.domNode&&(this.dispatchGridWidth=this.domNode.clientWidth);this.grid&&(this.dispatchGridLeftWidth=this.grid.GetBodyWidth(0),this.dispatchGridMidWidth=this.grid.GetBodyWidth(1),this.dispatchGridRightWidth=this.grid.GetBodyWidth(2),this.ReloadBody())},OnGetColor:function(a,b,c,d,e,f){if(!a.Cols[c]||!a.Cols[c].Visible)return null;a=null;d=JSON.stringify([d,e,f]);if(y==d||z==
d)a="white";this._firstRender||(b&&"RESID"==c&&d==A&&(this.alternateRowIDs.includes(b.id)||this.alternateRowIDs.push(b.id)),b&&"RESID"==c&&d==B&&this.alternateRowIDs.includes(b.id)&&this.alternateRowIDs.remove(b.id));return a}})});
