define("dojo/_base/lang dojo/_base/declare dojo/dom-geometry dojo/dom dojo/dom-style dojo/dom-attr dojo/dom-class dojo/_base/window com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(h,l,p,q,r,t,k,u,m,d,n){return l([m,n],{TAG:"WEATHER",TAB_CURRENT:0,TAB_DAILY:1,TAB_HOURLY:2,constructor:function(a){this.options=a||{};d.debug("{} options",this.TAG,a);this.weatherParams=a.params||{};this.dailyData=this.hourlyData=
this.currentData=null;this.tabs=[];this.currentTab=null;this.labels=a.labels||{};a.embedded&&(this.subscribeOn("weather.embedded.update",h.hitch(this,this.onWeatherUpdate)),this.weatherNode=a.weatherNodeId?document.getElementById(a.weatherNodeId):null);this.sectionHeight=a.height||330},label:function(a,b){return this[a]||b},startup:function(){this.inherited(arguments);this.embedded&&(d.debug("Weather is embedded, we'll wait for the weather.embedded.update command before showing weather"),this.domNode.style.displa=
"none");(!this.embedded||this.embedded&&this.weatherNode)&&this.discoverWeather()},destroy:function(){this.inherited(arguments)},discoverWeather:function(){this.fetch("discover_weather").then(h.hitch(this,this.handleWeatherResponse))},handleWeatherResponse:function(a){d.debug("Handling Weather Response",a);a&&a.error_invalid_locale?this.showNoWeather(this.options.weather_invalid_locale):a&&400==a.status?this.showNoWeather(this.options.weather_bad_request):a&&401==a.status?this.showNoWeather(this.options.not_authorized):
a&&412==a.status?this.showNoWeather(this.options.weather_no_location):a&&404==a.status?this.showNoWeather(this.options.weather_out_of_range):!a||!a.ui||!a.ui.tab||400<a.status?this.showNoWeather(this.options.unable_to_fetch):(this.weatherParams=this.weatherParams||{},this.weatherParams.lat=this.weatherParams.lat||a.latitude,this.weatherParams.lng=this.weatherParams.lng||a.longitude,"current"==a.ui.tab?(this.currentData=a,this.createUI(a.ui.tab)):"daily"==a.ui.tab?(this.dailyData=a,this.createUI(a.ui.tab)):
"hourly"==a.ui.tab?(this.hourlyData=a,this.createUI(a.ui.tab)):d.error("Invalid TAB: {}",a.ui.tab))},createUI:function(a){uiuab=a||"current";if(!this.weatherNode)if(this.embedded&&this.weatherParams.domId){if(d.debug("Embedded weather, trying to find DOMID: {}",this.weatherParams.domId),this.weatherNode=document.getElementById(this.weatherParams.domId),!this.weatherNode){d.error("Missing DOMID: {} in which to embed the weather control",this.weatherParams.domId);return}}else this.weatherNode=this.domNode;
this.weatherNode.innerHTML='<div class="weather"><div id="weather_content" class="weather_content">   <div id="weather_tab_current" class="panel current container">&hellip;&hellip;</div>   <div id="weather_tab_hourly" class="panel hourly container">&hellip;&hellip;</div>   <div id="weather_tab_daily" class="panel daily container">&hellip;&hellip;</div></div><ul class="weather-nav weather-nav-back">   <li><a id="#weather_current" href="#current">'+this.label("label.current","CURRENT")+'</a></li>   <li><a id="#weather_hourly" href="#hourly">'+
this.label("label.hourly","HOURLY")+'</a></li>   <li><a id="#weather_daily" href="#daily">'+this.label("label.daily","DAILY")+"</a></li></ul></div>";this.weatherNode.addEventListener("click",function(a){a.preventDefault();a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},!1);var b=this.weatherNode.querySelectorAll("ul a"),c=this.weatherNode.querySelectorAll(".panel");if(b.length!=c.length)d.error("Tab Buttons ({}) and Tab Contents ({}) do not match",b.length,c.length);else{for(var f=this,e=
0;e<b.length;++e){var g={link:b[e],content:c[e],id:b[e].getAttribute("id").split("_")[1]};d.debug("Hooking OnClick",g.link);g.link.onclick=function(a){return function(b){f.onTabChange(b,a,f.currentTab)}}(g);g.content.style.display="none";g.content.style.height=this.sectionHeight+"px";this.tabs[e]=g}d.debug("Focusing Tab",a);this.getTab(a).link.click()}},getTab:function(a){for(var b=0;b<this.tabs.length;++b)if(a==this.tabs[b].id)return this.tabs[b];return null},onTabChange:function(a,b,c){a.preventDefault();
a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;d.debug("Click: ",a,b,c);c&&(c.content.style.display="none",c.link.className="");b&&(b.content.style.display="",b.link.className="selected");this.currentTab=b;this["on"+this.currentTab.id.toUpperCase()+"TabSelected"]();return!1},onWeatherUpdate:function(a){this.weatherParams=a||{};this.dailyData=this.hourlyData=this.currentData=this.weatherNode=this.currentTab=null;d.debug("Got weather params",a);this.weatherParams.wonum||(d.debug("Missing wonum in parameters, will likely not be able to get a weather location"),
this.weatherParams.wonum="");this.weatherParams.start||(this.weatherParams.start=0);this.weatherParams.end||(this.weatherParams.start=0);this.fetch("discover_weather_with_options",{options:this.weatherParams}).then(h.hitch(this,this.handleWeatherResponse))},showNoWeather:function(a){d.error("No Weather",a);var b=this.weatherNode;this.currentTab&&this.currentTab.content&&(b=this.currentTab.content);if(!b)if(this.embedded&&this.weatherParams.domId){if(d.debug("Embedded weather, trying to find DOMID: {}",
this.weatherParams.domId),b=document.getElementById(this.weatherParams.domId),!b){d.error("Missing DOMID: {} in which to embed the weather control",this.weatherParams.domId);return}}else b=this.domNode;b.innerHTML='<div class="weather"><div class="error"><span class="error">'+a+"</span></div></div>"},onHOURLYTabSelected:function(){if(this.hourlyData)this.showHourlyWeather(this.hourlyData);else{var a=this;this.fetch("get_hourly_weather",this.weatherParams).then(function(b){a.hourlyData=b;a.showHourlyWeather(b)})}},
onDAILYTabSelected:function(){if(this.dailyData)this.showDailyWeather(this.dailyData);else{var a=this;this.fetch("get_daily_weather",this.weatherParams).then(function(b){a.dailyData=b;a.showDailyWeather(b)})}},onCURRENTTabSelected:function(){if(this.currentData)this.showCurrentWeather(this.currentData);else{d.debug("No Current Weather, Fetching it now.",this.currentData);var a=this;this.fetch("get_current_weather",this.weatherParams).then(function(b){a.currentData=b;a.showCurrentWeather(b)})}},showCurrentWeather:function(a){d.debug("Showing Current Weather",
a);this.validateResponse(a)&&(this.currentTab.content.innerHTML=this.buildWeatherPanel(a,a.show_more,0),this.updateButtons(a),a.show_more&&this.applyCardFlip(this.currentTab.content),this.renderComplete())},updateButtons:function(a){a.current_weather||this.hideTab("current");a.daily_weather||this.hideTab("daily");a.hourly_weather||this.hideTab("hourly")},hideTab:function(a){var b=this.getTab(a);b?b.link.parentNode.style.display="none":d.debug("missing tab: "+a)},applyCardFlip:function(a){a=a.querySelectorAll(".card");
for(var b=this,c=0;c<a.length;c++)a[c].style.cursor="pointer",a[c].addEventListener("click",function(a){var c=0<=navigator.appVersion.indexOf("Trident")||0<=navigator.userAgent.indexOf("MSIE")?"flipped_ie":"flipped";d.debug("flip for FF and Chrome");(a=b.findCard(a.target))?k.toggle(a,c):d.debug("NO CARD")})},findCard:function(a){return null==a?null:null!=a.className&&-1!=a.className.indexOf("card")?a:this.findCard(a.parentNode)},validateResponse:function(a){return!a||500< !a.status?(this.showNoWeather(this.options.unable_to_fetch),
!1):401==a.status?(this.showNoWeather(this.options.not_authorized),!1):!0},showDailyWeather:function(a){d.debug("Showing Daily Weather",a,this.weatherParams);if(this.validateResponse(a)){for(var b="",c=0;c<a.days.length;c++)var f=this.buildWeatherPanel(a.days[c],a.show_more,c),b=b+f;this.currentTab.content.innerHTML=b;this.updateButtons(a);a.show_more&&this.applyCardFlip(this.currentTab.content);this.weatherParams&&this.weatherParams.start&&(b=".d"+(new Date(this.weatherParams.start)).toISOString().substr(0,
10),(a=this.currentTab.content.querySelectorAll(b))&&(a=a[0]),a?(k.add(a,"highlight"),b=a.offsetWidth,c=a.getAttribute("panel")*b,f=a.parentNode.offsetWidth,f>b&&(c-=(f-b)/2),a.parentNode.scrollLeft=c):d.warn("NO PANEL FOR {}",b));this.renderComplete()}},showHourlyWeather:function(a){d.debug("Showing Hourly Weather",a,this.weatherParams);if(this.validateResponse(a)){for(var b="",c=0;c<a.hours.length;c++)var f=this.buildWeatherPanel(a.hours[c],a.show_more,c),b=b+f;this.currentTab.content.innerHTML=
b;this.updateButtons(a);a.show_more&&this.applyCardFlip(this.currentTab.content);this.weatherParams&&this.weatherParams.start&&(b=".t"+DateToString(this.weatherParams.start,"HH"),(a=this.currentTab.content.querySelectorAll(b))&&(a=a[0]),a?(k.add(a,"highlight"),b=a.offsetWidth,c=a.getAttribute("panel")*b,f=a.parentNode.offsetWidth,f>b&&(c-=(f-b)/2),a.parentNode.scrollLeft=c):d.warn("NO PANEL FOR {}",b));this.renderComplete()}},renderComplete:function(){if(this.weatherParams&&this.weatherParams.onRenderFinish)this.weatherParams.onRenderFinish()},
buildWeatherPanel:function(a,b,c){if(a.fields){var d="";0==(c+1)%2&&(d="striped");var e=null,e=c&&a["x-yyyymmdd"]?" d"+a["x-yyyymmdd"]:" ",g=null,g=c&&a["x-hh"]?" t"+a["x-hh"]:" ";c="<div panel="+c+' class="section card '+d+e+g+'"><div class="front">';for(d=0;d<a.fields.length;d++)e=a.fields[d],e.value&&(e=this.buildRowItem(e))&&(c+=e);c+="</div>";if(b){c+='<div class="back">';if(a.more_fields)for(d=0;d<a.more_fields.length;d++)e=a.more_fields[d],e.value&&(e=this.buildRowItemForShowMore(e))&&(c+=
e);c+="</div>"}return c+="</div>"}},buildRowItemForShowMore:function(a){if(!a.value)return null;var b;b='<div class="more">'+("<label>"+a.label+"</label>");b=a.icon?b+('<img src="weather/100x100/'+a.value+'.png">'):b+("<span>"+a.value_formatted+"</span>");return b+"</div>"},buildRowItem:function(a){if(!a.value)return null;var b='<div class="item">';a.style&&(b='<div class="item '+a.style+'">');a.suppress_label||(b+="<label>"+a.label+"</label>");b=a.icon?b+('<img src="weather/100x100/'+a.value+'.png">'):
b+("<span>"+a.value_formatted+"</span>");return b+"</div>"},onRefreshRequested:function(a){d.debug("Refresh UI");d.debug(a)},onMeasure:function(){d.debug("{}: onMeasure() RRR called",this.TAG);return{}}})});
