define("dojo/_base/lang dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers dojo/topic".split(" "),function(e,q,r,d,l,m){var f=0,h=WFPIXELS,k=!1,n=!1;showProperties=function(b){saveButton&&setButtonEnabled(saveButton,!0);var a=b.Parent.Item.D.MainTag.parentElement.parentElement.id;"Box"==b.Parent.Item.Kind?(b={node_row:b.Parent.Item.node_row,targetid:a},sendXHREvent("properties","nodes_table",b,REQUESTTYPE_SYNC,
"xml","text/xml",processXHR,null)):"Line"==b.Parent.Item.Kind&&(b={node_row:b.Parent.Item.D.Boxes[b.Parent.Item.From].node_row,action_row:b.Parent.Item.action_row,targetid:a},sendXHREvent("properties","actions_table",b,REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null));return!0};return q([r,l],{constructor:function(b){this.TAG=b.TAG;b.loglevel&&(d.LOG_LEVEL=b.loglevel);d.debug("{} DOM Node and options",this.TAG,this.domNode,b)},startup:function(){this.inherited(arguments);d.debug("{} startup called",
this.TAG);this.loadLibrary(function(){return null!=window.Designer},this.rootUrl+"/libraries/designer/DesignerE.js",e.hitch(this,this.createUI))},createUI:function(){var b=document.getElementById(this.domid);b.appendChild(document.createElement("hr"));this.mainGridId=this.domid+"_mainGrid";this.toolbarId=this.domid+"_toolbar";this.dwrapperId=this.domid+"_dwrapper";this.designerId=this.domid+"_designer";this.toolbarTable=document.createElement("table");this.toolbarTable.setAttribute("role","presentation");
this.toolbarTR=document.createElement("tr");this.toolbarTD1=document.createElement("td");this.toolbarTD2=document.createElement("td");this.buttonDiv=document.createElement("div");this.buttonDiv.style.height="40px";this.buttonDiv.style.verticalAlign="top";this.fullSpan=document.createElement("span");this.fullSpan.setAttribute("onclick","Designers[1].SetZoom(1)");this.fullSpan.style.width="25%";this.fullSpan.setAttribute("role","button");this.fullSpanImg=document.createElement("img");this.fullSpanImg.setAttribute("src",
"ac22_zoomToActualSize.png");this.fullSpanImg.setAttribute("id","zoomToActualImg");this.fullSpanImg.setAttribute("title","");this.fullSpanImg.setAttribute("alt","");this.fullSpan.appendChild(this.fullSpanImg);this.buttonDiv.appendChild(this.fullSpan);this.plusSpan=document.createElement("span");this.plusSpan.setAttribute("onclick","Designers[1].SetZoom(Designers[1].Zoom*1.1)");this.plusSpan.style.width="25%";this.plusSpan.setAttribute("role","button");this.plusSpanImg=document.createElement("img");
this.plusSpanImg.setAttribute("src","ac22_zoomin.png");this.plusSpanImg.setAttribute("id","zoomInImg");this.plusSpanImg.setAttribute("title","");this.plusSpanImg.setAttribute("alt","");this.plusSpan.appendChild(this.plusSpanImg);this.buttonDiv.appendChild(this.plusSpan);this.minusSpan=document.createElement("span");this.minusSpan.setAttribute("onclick","Designers[1].SetZoom(Designers[1].Zoom*0.9)");this.minusSpan.style.width="25%";this.minusSpan.setAttribute("role","button");this.minusSpanImg=document.createElement("img");
this.minusSpanImg.setAttribute("src","ac22_zoomout.png");this.minusSpanImg.setAttribute("id","zoomOutImg");this.minusSpanImg.setAttribute("title","");this.minusSpanImg.setAttribute("alt","");this.minusSpan.appendChild(this.minusSpanImg);this.buttonDiv.appendChild(this.minusSpan);this.mainGridDiv=document.createElement("div");this.mainGridDiv.setAttribute("id",this.mainGridId);b.appendChild(this.mainGridDiv);b.setAttribute("dir","ltr");this.toolbarDiv=document.createElement("div");this.toolbarDiv.setAttribute("id",
this.toolbarId);this.toolbarDiv.style.borderLeft="1px solid #b3b3b3";this.toolbarTD1.appendChild(this.buttonDiv);this.toolbarTD2.appendChild(this.toolbarDiv);this.toolbarTR.appendChild(this.toolbarTD1);this.toolbarTR.appendChild(this.toolbarTD2);this.toolbarTable.appendChild(this.toolbarTR);this.mainGridDiv.appendChild(this.toolbarTable);this.mainGridDiv.appendChild(document.createElement("hr"));this.wrapperDiv=document.createElement("div");this.wrapperDiv.setAttribute("id",this.dwrapperId);this.wrapperDiv.style.position=
"relative";this.designerDiv=document.createElement("div");this.designerDiv.setAttribute("id",this.designerId);this.designerDiv.style.overflow="hidden";this.designerDiv.style.position="absolute";this.designerDiv.style.borderRight="none";this.wrapperDiv.appendChild(this.designerDiv);this.mainGridDiv.appendChild(this.wrapperDiv);this.createUIToolbar(this.toolbarId);this.createUIDesigner(this.designerId);m.publish("miniapp.hideprogress",this.domid)},createUIToolbar:function(b){this.toolbarUniqueId=b+
"_"+(new Date).getTime();TDSetEvent("OnRendered",this.toolbarUniqueId,e.hitch(this,this.OnToolbarRendered));TDSetEvent("OnStartDragBox",this.toolbarUniqueId,e.hitch(this,this.OnStartDragBox));TDSetEvent("OnLoaded",this.toolbarUniqueId,e.hitch(this,this.OnToolBarLoaded));var a={Layout:{Url:this.baseUrl+"/Def4.xml"},Base:{Url:this.baseUrl+"/Shapes.xml"},Boxes:{Url:this.baseUrl+"/WFBoxes.xml"},Text:{Url:this.toUrl("async_load_wfdesigner_string_data",{value:null,project:null}),Cache:3},Data:{Url:this.baseUrl+
"/wftoolbar.xml"}};this.toolbar=Designer(a,b,this.toolbarUniqueId);d.debug("TOOLBAR: ",this.toolbar)},createUIDesigner:function(b){this.designerUniqueId=b+"_"+(new Date).getTime();TDSetEvent("OnBoxMove",this.designerUniqueId,e.hitch(this,this.OnBoxMove));TDSetEvent("OnBoxAdded",this.designerUniqueId,e.hitch(this,this.OnBoxAdded));TDSetEvent("OnBoxDeleted",this.designerUniqueId,e.hitch(this,this.OnBoxDeleted));TDSetEvent("OnEndDragBox",this.designerUniqueId,e.hitch(this,this.OnEndDragBox));TDSetEvent("OnLineAdd",
this.designerUniqueId,e.hitch(this,this.OnLineAdd));TDSetEvent("OnLineDeleted",this.designerUniqueId,e.hitch(this,this.OnLineDeleted));TDSetEvent("OnEndDragLine",this.designerUniqueId,e.hitch(this,this.OnEndDragLine));TDSetEvent("OnDblClick",this.designerUniqueId,e.hitch(this,this.OnDblClick));TDSetEvent("OnRendered",this.designerUniqueId,e.hitch(this,this.OnRendered));TDSetEvent("OnMenu",this.designerUniqueId,e.hitch(this,this.OnMenu));this.subscribeOn("wf.designer.propchange",e.hitch(this,this.onPropChange));
this.subscribeOn("wf.designer.refresh",e.hitch(this,this.onRefreshRequested));var a={Layout:{Url:this.baseUrl+"/Def4.xml"},Base:{Url:this.baseUrl+"/Shapes.xml"},Boxes:{Url:this.baseUrl+"/WFBoxes.xml"},Lines:{Url:this.baseUrl+"/WFLines.xml"},Text:{Url:this.toUrl("async_load_wfdesigner_string_data",{value:null,project:null}),Cache:3},Data:{Url:this.toUrl("async_load_wfdesigner_xml_data",{value:{nodedatasrc:"nodes_table",actiondatasrc:"actions_table"},project:null})}};this.designer=Designer(a,b,this.designerUniqueId);
d.debug("DESIGNER: ",this.designer)},OnToolbarRendered:function(b){d.debug("Toolbar is Rendered, adjust zoom.");this.toolbar=b;this.toolbar.SetZoom(.75)},OnMenu:function(b,a,c){return a.Def&&0<=a.Def.indexOf("ShapeStart")?!0:"Object"==a.Kind},OnToolBarLoaded:function(b,a){console.log(this.toolbar.Lang.Text);for(var c=0;c<this.toolbarTD1.firstChild.childNodes.length;){var d=this.toolbarTD1.firstChild.childNodes[c].firstChild.id;"zoomToActualImg"==d?(this.toolbarTD1.firstChild.childNodes[c].firstChild.title=
this.toolbar.Lang.Text.ZoomActual,this.toolbarTD1.firstChild.childNodes[c].firstChild.alt=this.toolbar.Lang.Text.ZoomActual):"zoomInImg"==d?(this.toolbarTD1.firstChild.childNodes[c].firstChild.title=this.toolbar.Lang.Text.ZoomIn,this.toolbarTD1.firstChild.childNodes[c].firstChild.alt=this.toolbar.Lang.Text.ZoomIn):"zoomOutImg"==d&&(this.toolbarTD1.firstChild.childNodes[c].firstChild.title=this.toolbar.Lang.Text.ZoomOut,this.toolbarTD1.firstChild.childNodes[c].firstChild.alt=this.toolbar.Lang.Text.ZoomOut);
c++}},OnRendered:function(b){d.debug("Designer is Rendered, Updating state.");this.designer=b;this.designer.ZoomFit();var a=document.getElementById("wfdesigner_miniapp_designer");b=a.getElementsByClassName("Box");a=a.getElementsByClassName("Line");f=b.length;d.debug("Designer: Boxes: {}, Lines: {}",f,a.length)},OnLineAdd:function(b,a){saveButton&&setButtonEnabled(saveButton,!0);n=!0;d.debug("LINE MOVED: ",a)},OnLineDeleted:function(b,a){saveButton&&setButtonEnabled(saveButton,!0);sendXHREvent("deleteaction",
this.domid,{action_row:a.action_row,node_row:a.D.Boxes[a.From].node_row},REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null);d.debug("LINE DELETED: ",a)},OnEndDragLine:function(b,a){if(n){var c={action_positive:"#F00"!=a.Color,owner_node_id:"string"==typeof a.From?parseInt(a.From.replace(/[.,\s]/g,"")):a.From,member_node_id:"string"==typeof a.To?parseInt(a.To.replace(/[.,\s]/g,"")):a.To,node_row:a.F.node_row};a.action_row=this.getActionRow(a);sendXHREvent("addaction",this.domid,c,REQUESTTYPE_SYNC,
"xml","text/xml",processXHR,null)}d.debug("LINE ADDED: ",a)},OnStartDragBox:function(b,a,c,d){k=!0;console.log("about to drag a new box");return[0,1]},OnEndDragBox:function(b,a,c,e,f,n,q,r){k?k=!1:(saveButton&&setButtonEnabled(saveButton,!0),b=Math.round(parseInt(a.X,10)/h),c=Math.round(parseInt(a.Y,10)/h),sendXHREvent("movenode",this.domid,{node_x:b.toString(),node_y:c.toString(),node_row:a.node_row},REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null),d.debug("MOVED TO: x: {}, y: {}",a.X,a.Y,a));
var g=document.getElementById("SystemNavAppContent-sc_div").firstElementChild,l=g.scrollLeft,m=g.scrollTop,p=function(){g.scrollTo(l,m);g.removeEventListener("scroll",p)};g.addEventListener("scroll",p);window.setTimeout(function(){p()},300);stopFocus=!0},OnBoxAdded:function(b,a){saveButton&&setButtonEnabled(saveButton,!0);var c=Math.round(parseInt(a.X,10)/h),e=Math.round(parseInt(a.Y,10)/h),c={node_x:c.toString(),node_y:e.toString(),node_type:a.Text};a.node_row=f;f++;sendXHREvent("addnode",this.domid,
c,REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null);d.debug("BOX ADDED: ",a)},OnDblClick:function(b,a,c){saveButton&&setButtonEnabled(saveButton,!0);b.Selected=a;"Box"==a.Kind?(b={node_row:a.Item.node_row,targetid:this.domid},sendXHREvent("properties","nodes_table",b,REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null)):"Line"==a.Kind&&(b={node_row:a.Item.D.Boxes[a.Item.From].node_row,action_row:a.Item.action_row,targetid:this.domid},sendXHREvent("properties","actions_table",b,REQUESTTYPE_SYNC,"xml",
"text/xml",processXHR,null));d.debug("DOUBLE CLICK: ",a);return!0},OnBoxDeleted:function(b,a){saveButton&&setButtonEnabled(saveButton,!0);sendXHREvent("deletenode",this.domid,a.node_row,REQUESTTYPE_SYNC,"xml","text/xml",processXHR,null);d.debug("BOX DELETED: ",a)},OnBoxMove:function(b,a,c,d){k=!1},onRefreshRequested:function(){this.designer.Reload()},onPropChange:function(b,a){var c=JSON.parse(b),d=c.title,c=c.id;"Box"==this.designer.Selected.Kind?(this.designer.Boxes[c].Text=d,this.designer.RefreshItem(this.designer.Boxes[c])):
"Line"==this.designer.Selected.Kind&&(this.designer.Lines[c].Text=d,this.designer.RefreshItem(this.designer.Lines[c]))},clearDesigners:function(){console.log(Designers)},getActionRow:function(b){for(var a=0,c=0;c<b.F.Lines.length;)b.F.Lines[c].From==b.From&&null!=b.F.Lines[c].action_row&&a++,c++;return a},destroy:function(){if(this.designer&&this.designer.Dispose){d.debug("Cleaning up Designer {}",this.designerId);try{this.designer.Dispose()}catch(a){d.warn("Designer clean up encountered an error {}",
this.designerId,a)}}if(this.toolbar&&this.toolbar.Dispose){d.debug("Cleaning up Designer Toolbar {}",this.toolbarId);try{this.toolbar.Dispose()}catch(a){d.warn("Designer clean up encountered an error {}",this.toolbarId,a)}}for(;0<Designers.length;){var b=length-1;null==Designers[b]&&Designers.splice(b,1)}this.inherited(arguments)}})});
