define("dojo/aspect dojo/topic dojo/_base/lang dojo/_base/window dojo/on dojo/_base/declare dojo/window dojo/dom-style dojo/dom-attr com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/dom-geometry dojo/dom".split(" "),function(n,p,k,q,r,g,l,t,u,v,c,h,m){g=g([v],{PAD:15,constructor:function(a,b){this.sizeToParentId=this.preferredHeight=this.preferredWidth=this.resizeTimeoutHandle=this.apectSizePanesHandle=this.resizeHandle=this.refreshHandle=null;this.fillHeight=
!1;this.TAG="["+a.appid+":"+b+"]";this.domNode=m.byId(b);this.domId=b;k.mixin(this,a)},postCreate:function(){this.inherited(arguments);var a=this,b="miniapp."+this.appid+".refresh";c.debug("{}: listening for {} event",this.TAG,b);this.refreshHandle=p.subscribe(b,function(f){c.debug("{}: received event: {}",a.TAG,b,f);try{a.onRefreshRequested(f)}catch(d){c.error("{}: onRefreshRequestedFailed!",a.TAG,d,a)}});a._deferredResize(1);this.apectSizePanesHandle=n.after(window,"toggleNavContainer",function(){c.debug("toggleNavContainer was called");
a._deferredResize(1)});window.addEventListener("resize",function(){a._deferredResize(1)});c.debug("{}: postCreate() called",this.TAG)},startup:function(){this.inherited(arguments);c.debug("{}: startup() called",this.TAG);this._connectResize();this.resize();this.postCreate()},destroy:function(){c.debug("{}: destroy() called",this.TAG);this.refreshHandle&&(this.refreshHandle.remove(),this.refreshHandle=null);this.resizeHandle&&(this.resizeHandle.remove(),this.resizeHandle=null);this.apectSizePanesHandle&&
(this.apectSizePanesHandle.remove(),this.apectSizePanesHandle=null);this.inherited(arguments)},_deferredResize:function(a){window.clearTimeout(this.resizeTimeoutHandle);var b=this;this.resizeTimeoutHandle=window.setTimeout(function(){if(1===a)b.onSideNavResized();b.resize()},450)},onSideNavResized:function(){},resize:function(){var a=this.onMeasure();c.debug("{}: resize() called with measure",this.TAG,a);a&&(a.w||a.h)?h.setContentSize(this.domNode,a):a&&(a.width||a.height)?t.set(this.domNode,a):c.warn("Failed to calculate size of miniapp??",
a)},onMeasure:function(){c.debug("{}: onMeasure() called",this.TAG);if(null!=this.sizeToParentId){var a=h.position(this.domNode),b=m.byId(this.sizeToParentId),f=h.getContentBox(b),d=h.position(b);c.debug("{}: control, parent:",this.TAG,a,d);var b=2*Math.abs(a.y-d.y)+this.PAD,e=u.get(q.body(),"dir"),e="RTL"==e||"rtl"==e?2*Math.abs(a.x+a.w-(d.x+d.w))+this.PAD:2*Math.abs(a.x-d.x)+this.PAD,d=parseInt(this.preferredHeight);isNaN(d)&&(d=0);d=Math.max(400,d);e=f.w-e;c.debug("{}: SIZING DEBUG: prefH: {}, prefW: {}, parentBox.h: {}, my: {}, this.preferredHeight: {}, this.fixedheight: {}, this.fillHeight: {}",
this.TAG,d,e,f.h,b,this.preferredHeight,this.fixedheight,this.fillHeight);this.fillHeight&&(d=a=l.getBox().h-a.y-b/2-2*this.PAD,c.debug("{}: Filling Vertical Space: {}",this.TAG,a));return{w:e,h:d}}c.debug("{}: Fixed Size: W:{} H: {}",this.TAG,this.preferredWidth,this.preferredHeight);a=this.preferredHeight;f=this.preferredWidth;this.fillHeight&&(b=l.getBox(),d=h.position(this.domNode),a=b.h-d.y-this.PAD+"px",c.debug("{}: Sizing to Screen Height: Screen: {}, Pos: {}, H: ",this.TAG,b,d,a));return{width:f,
height:a}},_connectResize:function(){null!=this.sizeToParentId&&(document.getElementById(this.sizeToParentId)?this.resizeHandle=r(window,"resize",k.hitch(this,this._deferredResize)):c.debug("Can't hook resize handler since {} element does not exist",this.sizeToParentId))},onRefreshRequested:function(a){c.debug("{}: onRefreshRequested()",this.TAG,a)},loadLibrary:function(a,b,f){c.debug("{}: Loading Dynamic Library: {}",this.TAG,b);try{var d=function(){c.debug("{}: Checking if loaded {}",k.TAG,b);g()?
h&&h():setTimeout(d,100)};if(a())f&&f();else{var e=document.createElement("script");e.type="text/javascript";e.src=b;document.documentElement.getElementsByTagName("head")[0].appendChild(e);c.debug("{}: Added Script Element",this.TAG,e);var g=a,h=f,k=this;d()}}catch(l){c.error("ERROR: Can't Load {}",b,l)}},isElementInViewport:function(a){a=a.getBoundingClientRect();return 0<=a.top&&0<=a.left&&a.bottom<=(window.innerHeight||document.documentElement.clientHeight)&&a.right<=(window.innerWidth||document.documentElement.clientWidth)},
isElementVisible:function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)},isVisible:function(){return this.domNode?this.isElementVisible(this.domNode):!1}});g.OK=2;g.CANCEL=4;g.YES=8;g.NO=16;g.NULL=-1;return g});
