define("dojo/_base/lang dojo/_base/declare dojo/dom-geometry dojo/dom dojo/dom-style dojo/dom-attr dojo/_base/window dojo/window dojo/Deferred dojo/dom-construct dojo/_base/array dojo/aspect com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers ibm/miniapp/linear/util/_LinearMenu ibm/miniapp/linear/util/_MapResize ibm/miniapp/linear/util/_LocSegOnMap ibm/miniapp/linear/util/_LocSegFromMap".split(" "),
function(b,m,g,k,e,n,p,l,A,q,B,r,t,u,c,v,w,x,y,z){return m([t,u,v,w],{GRID_VERSION:"Grid11.0",gridId:null,options:null,grid:null,reCreateGrid:!1,sizetoparentdomid:null,dom:null,setMapVisibleCtrl:!1,expand:!0,currentTabId:"",featureClassLinked:!1,firstPartOfTrowLabel:null,resizeMapObject:null,LocSegOnMap:null,LocSegFromMap:null,mapObj:null,MIN_HEIGHT:150,constructor:function(a){this.options=a;this.sizetoparentdomid=a.sizetoparentdomid;this.dom=a.dom?a.dom:this.domNode;a.loglevel&&(c.LOG_LEVEL=a.loglevel);
c.debug("{} options",this.TAG,a)},startup:function(){this.inherited(arguments);c.debug("{} Dynamic TreeGrid... loading dynamic library...",this.TAG);window.TreeGrid?this.createUI(null):this.loadLibrary(function(){return null!=window.TreeGrid},this.rootUrl+"/libraries/treegrid/Grid/GridE.js",b.hitch(this,this.createUI))},_removeOldGrid:function(){if(null!=this.grid){c.debug("{} Cleaning up TreeGrids",this.TAG);this.clearHandlers&&this.clearHandlers();try{this.grid.Clear(),this.grid.Dispose()}catch(a){c.warn("{} TreeGrid clean up encountered an error",
this.TAG,a)}}},destroy:function(){this._removeOldGrid();this.inherited(arguments);this.subscribeOn("miniapp.visibility",b.hitch(this,this.onVisibilityRequest));this.subscribeOn("linear.set.grid",b.hitch(this,this.createUI));this.fullScreenListener&&this.removeFullScreenListener()},removeFullScreenListener:function(){this.onFullscreenModeChanged({modeOn:!1});this.fullScreenListener.remove()},createUI:function(){this.dom||(dnode=this.domNode);window.TreeGrid&&c.debug("TreeGrid Release: {}, {}",window.Component.Version,
window.Component.Release);c.debug("Creating Gantt UI");this.grid&&this._removeOldGrid();this._newGridID();var a={};null!=this.options.mx_csrftoken&&(a={csrftoken:this.options.mx_csrftoken});a={Data:{Url:this.toUrl("get_root_data",{}),Header:a,Timeout:300},Page:{Url:this.toUrl("get_child_data",{}),Header:a,Timeout:300,Format:"JSON"},Layout:{Url:this.toUrl("create_ui",{}),Header:a,Timeout:300}};0==c.LOG_LEVEL?a.Debug=a.Debug||"Problem,Error,IOError,Check,Info":3==c.LOG_LEVEL?(a.DebugTag="Console",a.Debug=
a.Debug||"Problem,Error,IOError"):a.Debug="";a.Text=a.Text||{Url:this.toUrl("load_labels",{}),Format:"JSON",Header:{csrftoken:this.options.mx_csrftoken}};TGSetEvent("OnLoadError",this.gridId,new function(a,d){c.error(d);sendEvent("showwarnings",this.appid)});TGSetEvent("OnClick",this.gridId,b.hitch(this,this.OnClick));TGSetEvent("OnTip",this.gridId,b.hitch(this,this.OnTip));TGSetEvent("OnRenderPageFinish",this.gridId,b.hitch(this,this.OnRenderPageFinish));TGSetEvent("OnRightClick",this.gridId,b.hitch(this,
this.OnRightClick));TGSetEvent("OnGanttMenu",this.gridId,b.hitch(this,this.OnGanttMenu));TGSetEvent("OnGanttMenuClick",this.gridId,b.hitch(this,this.OnGanttMenuClick));TGSetEvent("OnDataGet",this.gridId,b.hitch(this,this.OnDataGet));this.grid=TreeGrid(a,this.dom,this.gridId);this.subscribeOn("linear.ui.refresh.grid",b.hitch(this,this.onRefreshRequested));this.subscribeOn("linear.ui.reset.grid",b.hitch(this,this.onResetRequested));this.subscribeOn("linear.ui.from.to.measure",b.hitch(this,this.fromToMeasure));
this.subscribeOn("miniapp.visibility",b.hitch(this,this.onVisibilityRequest));this.subscribeOn("linear.set.grid",b.hitch(this,this.setGrid));this.subscribeOn("linear.destroy.grid",b.hitch(this,this.destroy));this.subscribeOn("linear.getOptions",b.hitch(this,this.getOptions));this.subscribeOn("linear.map.visibility",b.hitch(this,this.mapVisibilityCtrl));this.subscribeOn("linear.reset.map.visibility",b.hitch(this,this.resetMapVisibilityCtrl));this.subscribeOn("locate.LVCLinearSeg.from.map",b.hitch(this,
this.locateLinearSegment));this.grid.MainTag.hidden=this.options.hidden;this.dom.style["padding-left"]="10px";this.hideDebugDisplay();r.after(window,"onresize",b.hitch(this,this._deferredResize))},catchConsecutiveDupFeatureSpecCalls:"",OnDataGet:function(a,f,d,c){try{var b=JSON.parse(d);console.log("OnDataGet data:"+b);if(b.Body&&b.Body[0]&&b.Body[0].id){var e=b.Body[0].id;if(e.includes("--features--")){if(this.catchConsecutiveDupFeatureSpecCalls)return this.catchConsecutiveDupFeatureSpecCalls="",
"{}";this.catchConsecutiveDupFeatureSpecCalls=e;return d}this.catchConsecutiveDupFeatureSpecCalls=""}}catch(g){}},getGrid:function(a,f){return null==this.grid?"":this.grid.IsCellExpanded(a,f)},GetRow:function(a,f,d,b,c){if("G"!=d)return f;a=a.GetGanttXY(f,d,b,c);return null!=a&&null!=a.Type&&a.RunId?this.GetRowById(a.RunId):f},GetRowById:function(a){var f=this.grid.GetRowById(a);f||"R"!=a.charAt(0)||(f=this.grid.GetRowById(a.substring(1)));return f},_newGridID:function(){this.gridId="g"+Math.floor(1E4*
Math.random()+1);this.TAG=(this.options.TAG||"Linear")+"["+this.gridId+"]"},getOptions:function(){this.publishTo("getOptions",{rootUrl:this.rootUrl,tag:this.TAG,loglevel:this.loglevel,Header:{csrftoken:this.options.mx_csrftoken}})},OnTip:function(a,f,d,b,e,g,k,l){c.debug("Can do something different with the tooltip, if we want",b);return b},OnClick:function(a,f,d,b,c,e){return null==this.LocSegFromMap||"name"!=d&&"Mark"!=d?null!=this.LocSegOnMap?this.LocSegOnMap.OnClick(a,f,d,b,c,e,this.mapObj):!1:
this.LocSegFromMap.OnClick(a,f,d,b,c,e)},mapVisibilityCtrl:function(a){this.setMapVisibleCtrl="toggle"==a.enabled?!this.setMapVisibleCtrl:a.enabled;this.currentTabId=a.currentTabId;if(!miniapps.linear.instances._MiniAppInstance.reCreateGrid)this.onVisibilityRequest('{enabled: true, currentTabId: "'+a.currentTabId+'"}');this.firstPartOfTrowLabel=a.trow;this.fullScreenListener&&this.removeFullScreenListener();this.setMapVisibleCtrl?(this.fullScreenListener=dojo.subscribe("mapFullScreenModeChanged_"+
a.mapObj.getId(),b.hitch(this,this.onFullscreenModeChanged)),null!=a.mapObj&&(this.mapObj=a.mapObj,a.mapObj.RefLinearView=this,this.LocSegOnMap||(this.LocSegOnMap=new y({map:a.mapObj,componentId:this.componentId,appid:this.appid})),this.LocSegFromMap||(this.LocSegFromMap=new z({map:a.mapObj,componentId:this.componentId,appid:this.appid,firstPartOfTrowLabel:a.trow}))),this._resize(),this.createMapResizing(a.mapObj)):this.removeMapResizing(a.mapObj);this.setMapVisibleCtrl&&(this._resize(),this.delayActionZoomFit(this),
this.grid.Reload())},removeMapResizing:function(a){dojo.byId("mapResizer")&&(this.grid.MainTag.hidden=!0,this.setMapVisibleCtrl=!1,this.resizeMapObject.destroy(),this.LocSegOnMap.cleanUp(),a.height="100%",a._resize())},createMapResizing:function(a){if(null==dojo.byId("mapResizer")&&(this.inFullScreenMode=a.inFullScreen(),this.setMapVisibleCtrl=!0,this.grid.MainTag.hidden=!1,null==this.resizeMapObject&&(this.resizeMapObject=new x(this)),this.inFullScreenMode||(a.height="50%",a._resize()),this.resizeMapObject.create(),
this.inFullScreenMode))this.onFullscreenModeChanged({modeOn:!0})},resetMapVisibilityCtrl:function(a){this.setMapVisibleCtrl=dojo.fromJson(a).enabled;this.reCreateGrid=!1},onVisibilityRequest:function(a){var b=this;this.fetch("isMboLinkedToFeatureClass").then(function(a){b.featureClassLinked=a.plussIsGis});a=dojo.fromJson(a);this.currentTabId=a.currentTabId;this.setVisible=this.setMapVisibleCtrl?!0:a.enabled;c.debug("Visibility Set: "+this.setVisible);this.setVisible&&null==this.grid?this.startup():
this.setVisible||null==this.grid?null==this.grid||this.reCreateGrid?null!=this.grid&&(this.grid.MainTag.hidden=this.setVisible?!1:!0):(this.createUI(),this.grid.MainTag.hidden&&(this._resize(),this.grid.MainTag.hidden=!1),this.reCreateGrid=!0):this.grid.MainTag.hidden=!0;this._resize();this.delayActionZoomFit(this)},numOfDelayActionZoomFitIter:0,delayActionZoomFitInProgress:!1,delayActionZoomFit:function(a){(a.setVisible||a.setMapVisibleCtrl)&&a.reCreateGrid&&a.grid&&!a.delayActionZoomFitInProgress&&
(a.delayActionZoomFitInProgress=!0,a.grid.CanZoomIn()||a.grid.CanZoomOut()?setTimeout(function(){a.numOfDelayActionZoomFitIter=0;a.grid.ActionZoomFit();a.delayActionZoomFitInProgress=!1;console.log("ActionZoomFit function called")},1E3):30>a.numOfDelayActionZoomFitIter++?setTimeout(function(){a.delayActionZoomFitInProgress=!1;a.delayActionZoomFit(a)},1500):(a.numOfDelayActionZoomFitIter=0,a.delayActionZoomFitInProgress=!1))},setGrid:function(a){},onRefreshRequested:function(a){c.debug("Refresh UI");
c.debug(a);GetGrids();a=this.grid.GetRowById(a);null!=a&&(this.grid.Expand(a),this.grid.ExpandParents(a),this.grid.Reload())},OnRenderPageFinish:function(a,b){console.log("OnRenderFinish "+b.id);this.grid=a;if("mxmap"==this.currentTabId){this.hideResizer();this._resize();if(null!=this.LocSegFromMap&&this.LocSegFromMap.locateSegFromMap)this.LocSegFromMap.OnRenderPageFinish(a,b);else if(null!=this.mapObj&&null!=this.mapObj.targetCenter)this.mapObj.centerAt(this.map.targetCenter),this.mapObj.targetCenter=
null;else if(null!=this.mapObj&&this.mapObj.currentRecordMgr&&this.mapObj.currentRecordMgr.mboInfo.marker){var d=this.mapObj.currentRecordMgr.mboInfo.marker.point.toProprietary();if(0==this.mapObj.map.spatialMapManager.isPointInFullExtent(d))return;this.mapObj.map.centerAt(d)}for(var d=document.getElementsByTagName("div"),c=0;c<d.length;c++)-1!==d[c].id.indexOf("TGTmpFocusGrid")&&q.destroy(d[c].id)}},onResetRequested:function(a){c.debug("Reset UI");this.reCreateGrid&&this.createUI();this.reCreateGrid=
!1;this.grid.MainTag.hidden=!0},fromToMeasure:function(a){c.debug("From-To Measure: "+a);a=dojo.fromJson(a);this.reCreateGrid&&null!=this.grid.GetGanttBase()&&""!=this.grid.GetGanttBase()&&(this.grid.SetGanttBase(a.SetGanttBase),this.grid.SetGanttFinish(a.SetGanttFinish))},_resize:function(){if(this.setVisible||this.setMapVisibleCtrl)if(this.inMapTab())this.resizeInMapTab();else{this.fixToolStyleOutsideMapTab();var a=this.onMeasure();c.debug("{}: resize() called with measure",this.TAG,a);a&&(a.w||
a.h)?g.setContentSize(this.domNode,a):a&&(a.width||a.height)?e.set(this.domNode,a):c.warn("Failed to calculate size of miniapp??",a);e.set(this.domNode,{"margin-bottom":"25px","margin-left":"10px","margin-right":"25px"})}},_deferredResize:function(){var a=this;setTimeout(function(){a._resize()},300)},onMeasure:function(){c.debug("{}: onMeasure() RRR called",this.TAG);if(null!=this.sizetoparentdomid){var a=g.position(this.domNode),b=dojo.byId("SystemNavAppContent-sc_div"),d=k.byId(this.sizetoparentdomid);
"mxmap"==this.currentTabId&&null!=b&&(d=k.byId(b));b=g.getContentBox(d);d=g.position(d);b.w>=window.innerWidth&&"mxmap"==this.currentTabId&&(b.w=window.innerWidth);c.debug("{}: control, parent:",this.TAG,a,d);var e=2*Math.abs(a.y-d.y)+this.PAD;n.get(p.body(),"dir");var d=Math.max(200,parseInt(this.preferredHeight))-50,h=b.w-35;"mxmap"==this.currentTabId&&(h=b.w-35);c.debug("{}: SIZING DEBUG: prefH: {}, prefW: {}, parentBox.h: {}, my: {}, this.preferredHeight: {}, this.fixedheight: {}, this.fillHeight: {}",
this.TAG,d,h,b.h,e,this.preferredHeight,this.fixedheight,this.fillHeight);this.fillHeight&&(d=a=l.getBox().h-a.y-e/2-2*this.PAD,c.debug("{}: Filling Vertical Space: {}",this.TAG,a));return{w:h,h:d}}c.debug("{}: Fixed Size: W:{} H: {}",this.TAG,this.preferredWidth,this.preferredHeight);a=this.preferredHeight;b=this.preferredWidth;this.fillHeight&&(d=l.getBox(),h=g.position(this.domNode),a=d.h-h.y-this.PAD+"px",c.debug("{}: Sizing to Screen Height: Screen: {}, Pos: {}, H: ",this.TAG,d,h,a));return{width:b,
height:a}},hideDebugDisplay:function(){var a=k.byId("_TreeGridDebug"),b=k.byId("_TreeGridDebugButtons");a&&Grids&&0==c.LOG_LEVEL&&(a.style.display="none",b.style.display="none",Grids.DebugHidden=1)},locateLinearSegment:function(a){this.LocSegFromMap&&this.LocSegFromMap.locateLinearSegment(this.grid,this.firstPartOfTrowLabel,a)},inMapTab:function(){return"mxmap"==this.currentTabId},resizeInMapTab:function(){var a=this.getMap(),a=this.getAvailableHeightInMapTab()-a.offsetHeight;this.fixToolStyleOnMapTab();
e.set(this.domNode,{height:a+"px",width:"100%",margin:"",padding:""})},getMap:function(){return dojo.byId("mxmap_div-mapcontrol_mapdiv")},getAvailableHeightInMapTab:function(){var a=this.getMap(),a=(a.offsetParent||document.body).offsetHeight-a.offsetTop;dojo.isWebKit||--a;return a},hideResizer:function(){var a=dojo.query(".CGResizeGrid",this.dom)[0];a&&e.set(a,{display:"none"})},getTable:function(){return dojo.query(".CGMainTable",this.dom)[0]},getTableHeight:function(){var a=this.getTable();return a?
a.offsetHeight:0},getHeader:function(){return dojo.query(".CGToolbarRow",this.dom)[0]},fixToolStyleOnMapTab:function(){var a=this.getHeader();a&&e.set(a,{border:"none"});(a=this.getTable())&&e.set(a,{border:"none",borderBottom:"1px solid rgba(192, 192, 255)"});e.set(this.dom,{border:"1px solid rgba(0, 0, 0, 0.72)",backgroundColor:"#FFFFFF"})},fixToolStyleOutsideMapTab:function(){e.set(this.dom,{border:"",backgroundColor:""})},onFullscreenModeChanged:function(a){var b=this.getMap();a=a.modeOn;b.style.height=
this.getAvailableHeightInMapTab()/2+"px";a?(this.inFullScreenMode=!0,this.positionTool()):(this.inFullScreenMode=!1,e.set(this.dom,{position:"",left:"",top:"",width:"",height:"",zIndex:""}));this._resize()},positionTool:function(){if(this.inFullScreenMode){var a=this.getMap(),b=a.offsetWidth,a=a.offsetHeight+a.offsetTop,d=0,c=dojo.query(".application-navigation-menu")[0];c&&(d=parseInt(dojo.style(c,"width"))||0);e.set(this.dom,{position:"fixed",left:d+"px",width:b+"px",top:a+"px",zIndex:1001})}}})});
