define("dojo/_base/lang dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers dojo/date ibm/tivoli/mbs/dijit/DateTimeCalendar dijit/Calendar dijit/popup dojo/request dojo/json dojo/dom".split(" "),function(m,p,q,r,e,t,w,u,v,n,x,y,z){return p([q,r,t],{GANTTCOL:"GANTT",gridId:"apptbook",grid:null,projectid:"",constructor:function(a){this.TAG=a.TAG||"APPTBOOK";a.loglevel&&(e.LOG_LEVEL=
a.loglevel);e.debug("{} options",this.TAG,a);this.options=a||{};this.subscribeOn("apptbook.toolbar.sample",m.hitch(this,this.OnSampleIconClick))},OnSampleIconClick:function(a){e.debug("Clicked the sample icon in the toolbar, message: {}",a);alert("Sample")},startup:function(){this.inherited(arguments);e.debug("{} Dynamic TreeGrid... loading dynamic library...",this.TAG);window.TreeGrid?this.createUI():this.loadLibrary(function(){return null!=window.TreeGrid},this.rootUrl+"/libraries/treegrid/Grid/GridE.js",
m.hitch(this,this.createUI))},_removeOldGrid:function(){if(null!=this.grid){e.debug("{} Cleaning up TreeGrids",this.TAG);this.clearHandlers&&this.clearHandlers();try{this.grid.Dispose()}catch(a){e.warn("{} TreeGrid clean up encountered an error",this.TAG,a)}}},destroy:function(){this._removeOldGrid();this.inherited(arguments)},createUI:function(){window.TreeGrid&&e.debug("TreeGrid Release: {}, {}",window.Component.Version,window.Component.Release);e.debug("Creating Gantt UI");this.grid&&this._removeOldGrid();
var a={Data:{Url:this.toUrl("get_root_data",{}),Timeout:300},Page:{Url:this.toUrl("get_child_data",{}),Timeout:300,Format:"JSON"},Layout:{Url:this.toUrl("create_ui",{startDate:(new Date).getTime()}),Timeout:300}};a.Debug=a.Debug||"Problem,Error,IOError";a.Text=a.Text||{Url:this.toUrl("load_labels",{}),Format:"JSON"};TGSetEvent("OnLoadError",this.gridId,function(a,c){e.error(c);sendEvent("showwarnings",this.appid)});TGSetEvent("OnGetGanttHeader",this.gridId,m.hitch(this,this.OnGetGanttHeader));TGSetEvent("OnIncDate",
this.gridId,function(a,c,d,e){return"t"==d?(a=new Date(c),c=new Date(a),c.setDate(a.getDate()+e),c-0):null});TGSetEvent("OnRightClick",this.gridId,m.hitch(this,this.OnRightClick));TGSetEvent("OnRenderFinish",this.gridId,m.hitch(this,this.OnRenderFinish));TGSetEvent("OnClick",this.gridId,m.hitch(this,this.OnClick));Grids.OnClickButton=m.hitch(this,function(a,c,d,g){if(this["On"+d+"Click"])return e.debug("CLICK Toolbar Icon: {}",d,g),this["On"+d+"Click"](g),1;e.debug("No On{}Click handler defined",
d)});this.grid=TreeGrid(a,this.domNode,this.gridId);window.AddGanttUnits("t",864E5,null)},OnGetGanttHeader:function(a,b,c,d,g,f){e.debug(b);if(0<=b.indexOf("."))return"<div id='date_"+b+'\' class="weather"></div>';a=b.split(" ");return'<span class="DayNumber">'+a[0]+"</span><span>"+a[1]+"</span>"},OnRenderFinish:function(a){e.debug("Resizing to Fit");a.ActionZoomFit();this.grid=a},onRefreshRequested:function(a){e.debug("Refresh UI");this.createUI()},OnRightClick:function(a,b,c,d,g,f){f.metaKey||this.closeDatePicker&&
this.closeDatePicker();if(null!=b&&"Data"==b.Kind){this.eventPageX=f.pageX;this.eventPageY=f.pageY;e.debug("OnRightClick: {}",c);a.Focus(b,c,null,!1);if(c==this.GANTTCOL){var k=a.GetGanttXY(b,c,d,g);if(null!=k&&null!=k.Type&&"line"!=k.Type)this.OnActivityContextMenu(a,b,c,d,g,f);else return!1}else this.OnTableContextMenu(a,b,c,d,g,f);return!0}},OnActivityContextMenu:function(a,b,c,d,g,f){e.debug("OnActivityContextMenu: {}",b.id);return this.OnTableContextMenu(a,b,c,d,g,f)},OnContextMenu:function(a,
b,c,d){e.debug("OnContextMenu: {} {}",c,d)},OnTableContextMenu:function(a,b,c,d,g,f){e.debug("OnTableMenuContextMenu: {}",c,a.Cols[c]);var k=this;if(!a.Cols[c])return!1;value=c==this.GANTTCOL?b.id:b[c];b=this.GetRow(a,b,c,d,g);var h=a.GetGanttXY(b,c,d,g);if(null!=h&&"dependency"==h.Type)this._EDIT_DEPENDENCY=h,e.debug("Dependency Menu Fetch for",h),this.fetch("async_get_table_context_menu",{projectid:k.projectid,id:h.DependencyFrom,col:"dependency",value:h.DependencyTo+h.DependencyType}).then(function(e){k._ShowContextMenu(e,
a,b,c,d,g,f)});else{var h=this.GetSelectionIds(a,c,b),l=this._GetSelectedRowIds(a,c,b);e.debug("OnTableMenuContextMenu: Context Menu: Selection: {}",l,h);this.fetch("async_get_table_context_menu",{projectid:k.projectid,id:l,selection:h,col:c,value:value}).then(function(e){e=k._AdditionalTableContextMenu(e,a,b,c,d,g,f);k._ShowContextMenu(e,a,b,c,d,g,f)})}return!0},_GetSelectedRows:function(a,b,c){var d=[];if(b==this.GANTTCOL)if(b=a.GetGanttRunSelectedBoxes(null,b),0<b.length)for(a=0;a<b.length;a++){var e=
b[a].Id;e&&(e=this.GetRowById(e),null!=e&&d.push(e))}else d=a.GetSelRows();else if(d=a.GetSelRows(),2===d.length&&(b=a.GetGanttRunSelectedBoxes(null,this.GANTTCOL),0<b.length))for(a=0;a<b.length;a++)if(e=b[a].Id)e=this.GetRowById(e),null!=e&&d.push(e);b=!0;for(a=0;a<d.length;a++)if(null!=c&&d[a].id==c.id){b=!1;break}null!=c&&b&&d.push(c);return d},_GetSelectedRowIds:function(a,b,c){a=this._GetSelectedRows(a,b,c);c=b="";for(var d in a)b=b+c+a[d].id,c=",";return b},isResourceView:function(){return!1},
GetSelection:function(a,b,c){var d={activities:[],resources:[]},e=this.isResourceView,f=a.GetGanttRunSelectedBoxes(null,this.GANTTCOL);if(0<f.length)for(var k=0;k<f.length;k++){var h=f[k].Id;h&&(h=this.GetRowById(h),null!=h&&(d.activities.push(h),h.parentNode&&e&&d.resources.push(h.parentNode)))}this._focusGanttObject&&d.activities.push(this._focusGanttObject);(a=a.GetSelRows())&&a.length&&(this.isResourceView()?d.resources=d.resources.concat(a):d.activities=d.activities.concat(a));c&&("box"==c.Type?
(d.activities.push(c),this.isResourceView()&&d.resources.push(c.parentNode)):this.isResourceView()?d.resources.push(c):d.activities.push(c),d.current_row=c,d.current_row_parent=c.parentNode,d.current_row_type=this.isResourceView?1:0);b&&(d.col=b,c&&b!=this.GANTTCOL&&(d.col_value=c[b]));return d},GetSelectionIds:function(a,b,c){var d={activities:[],resources:[]},e={};a=this.GetSelection(a,b,c);for(c=0;c<a.activities.length;c++)e[a.activities[c].id]||(d.activities.push(a.activities[c].id),e[a.activities[c].id]=
1);e={};for(c=0;c<a.resources.length;c++)e[a.resources[c].id]||(d.resources.push(a.resources[c].id),e[a.resources[c].id]=1);a.current_row&&(d.current_row=a.current_row.id);a.current_row_parent&&(d.current_row_parent=a.current_row_parent.id);d.current_row_type=this.isResourceView?1:0;d.col=b;d.col_value=a.col_value;return d},GetRow:function(a,b,c,d,e){if(c!=this.GANTTCOL)return b;a=a.GetGanttXY(b,c,d,e);return null!=a&&null!=a.Type&&a.RunId?this.GetRowById(a.RunId):b},GetRowById:function(a){return this.grid.GetRowById(a)},
OnContextMenuItemSelected:function(a,b){var c=this;e.debug("OnContextMenuItemSelected",a);if(a.Values&&a.Values.dialogname)"GOTO"!=a.Values.dialogname?this.OnShowMaximoDialog(a):this.OnGoToMaximoApplication(a);else if(this[a.Value])try{e.debug("Calling ContextMenu Handler: {}",a.Value),this[a.Value](a,b)}catch(d){e.error("Error While Invoking Internal Method for {}",a.Value,d)}else a.longOpMessage&&this.publishPleaseWait(a.longOpMessage),this.fetch("on_handle_context_menu_item",{projectid:this.projectid,
id:this.SetIDFromItem(a),value:a.Value,values:a.Values}).then(function(d){c.progress(!0);c[a.Value+"Reply"]?(e.debug(" handle_context_menu_item: Sending Reply To {}",a.Value+"Reply"),c[a.Value+"Reply"](d,a,b)):c.handleServerReply(d,a);(1==a.ClearSelection||d&&d.IO&&1==d.IO.ClearSelection)&&c.grid.ClearSelection();c.progress(!1)})},handleServerReply:function(a,b){b=b||{};a&&a.Changes?(this.acceptChangesFromServer(a),this.sendToBeSaved()):a&&a.IO?(e.debug("Handling Reply.IO",a),1E3==a.IO.Result?(this.grid.ActionReload(),
this.sendToBeSaved()):1001==a.IO.Result?this.sendToBeSaved():0>a.IO.Result?e.error("Error Processing Action: {}, Error: {}",b.Value,a.IO.Result):e.error("Server Reply for Action: {}, OK Result: {}",b.Value,a.IO.Result)):e.debug("no reply to process",a)},publishPleaseWait:function(a){this.publishTo("apptbook.ui.please-wait",a)},acceptChangesFromServer:function(a){a&&a.Changes?(e.debug("Begin Applying Changes from server"),this.grid.AddDataFromServer(a),e.debug("Done Applying Changes from server")):
e.warn("No Changes",a)},ReloadBody:function(a){null==a&&(a=function(){e.debug("Reload Complete")});e.debug("Reloading Body");this.grid.ReloadBody(a)},OnShowMaximoDialog:function(a){e.debug("Show Maximo Dialog",a.Values);for(var b in a.Values)e.debug("addCommInput({},{})",b,a.Values[b]),addCommInput(b,a.Values[b]);e.debug("sendEvent({},{})",a.Values.dialogname,this.appname);sendEvent(a.Values.dialogname,this.appname,"")},OnGoToMaximoApplication:function(a){e.debug("Go To Maximo Application",a.Values);
for(var b in a.Values)e.debug("addCommInput({},{})",b,a.Values[b]),addCommInput(b,a.Values[b]);e.debug("sendEvent({},{})",a.Values.dialogname,this.appname);sendEvent("applink",this.appname,"")},_OnDebugItem:function(a){a.Col==this.GANTTCOL?e.debug("DEBUG GANTT ITEM",a.Row):e.debug("DEBUG ITEM {}",a.Row.name,a.Row)},_OnClearSavedState:function(){this.fetch("clear_saved_state")},_ShowContextMenu:function(a,b,c,d,g,f,k){if(a){var h=this;try{e.debug("Dynamic Menu",a),d!=this.GANTTCOL&&b.GetCell(c,d),
this._currentContextRow=c,b.HideTip(),b.CloseDialog(),a.ZIndex=50001,b.Dialog=b.ShowPopup(a,function(a){h.OnContextMenuItemSelected(a,c)})}catch(l){e.error("error processing menu",l,a,d,c)}}else e.debug("No Menu for {}",d,c)},_AdditionalTableContextMenu:function(a,b,c,d,g,f,k){e.debug("_AdditionalTableContextMenu: {}",d);if("name"==d||d==this.GANTTCOL)a=a||{Items:[]},e.debug("Adding Debug Menus"),0>=this.loglevel&&(a.Items.push({Name:"-",Grid:b,Row:c,Col:d,X:f,Y:f}),a.Items.push({Name:"Debug Item",
Value:"_OnDebugItem",Grid:b,Row:c,Col:d,X:f,Y:f}),a.Items.push({Name:"Clear Saved State",Value:"_OnClearSavedState",Grid:b,Row:c,Col:d,X:f,Y:f}),a.Items.push({Name:"Fetch UI Model",Value:"_FetchUIModel",Grid:b,Row:c,Col:d,X:f,Y:f}),a.Items.push({Name:"Fetch Data Model",Value:"_FetchDataModel",Grid:b,Row:c,Col:d,X:f,Y:f}));return a},_FetchUIModel:function(){window.open(this.grid.Data.Layout.Url)},_FetchDataModel:function(){window.open(this.grid.Data.Data.Url)},TGDateToTZDate:function(a){return(new Date(a+
6E4*(new Date(a)).getTimezoneOffset())).getTime()},TZDateToTGDate:function(a){return a-6E4*(new Date).getTimezoneOffset()},TGDateToUserTZDate:function(a){return a+(this.GMT0TZOffset||0)},_today:function(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a=new Date(this.TZDateToTGDate(a.getTime()))},LoadNewDateForModel:function(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);var b=this;this.fetch("goto_date",{projectid:this.projectid,tzOffset:a.getTimezoneOffset(),
date:a.getTime(),fmtDate:a.getFullYear()+"-"+(a.getMonth()+1)+"-"+a.getDate()}).then(function(a){b.handleServerReply(a)})},OnNEXTClick:function(a){var b=this;this.fetch("goto_date_offset",{projectid:this.projectid,dateOffset:1}).then(function(a){b.handleServerReply(a)})},OnPREVClick:function(a){var b=this;this.fetch("goto_date_offset",{projectid:this.projectid,dateOffset:-1}).then(function(a){b.handleServerReply(a)})},OnGOTOTODAYClick:function(a){e.debug("Goto TODAY");this.LoadNewDateForModel(new Date)},
OnGOTOSELECTDAYClick:function(a){e.debug("Goto Selected DAY [TG Event]>",a);try{this.eventPageX=a.ClientX,this.eventPageY=a.ClientY,this._selectDatePopupAction("_movetoSelectedDate",null,v,m.hitch(this,this._GotoSeletedDateActionHandler))}catch(b){e.error("Goto TODAY failed",b)}},_GotoSeletedDateActionHandler:function(a,b,c){e.debug("Need to Jump to this date: {}",c);this.LoadNewDateForModel(c)},_selectDatePopupAction:function(a,b,c,d){e.debug("_selectDatePopupAction(): Calendar Constraints ",this.userinfo.calendarConstraints);
var g=this.userinfo.calendarConstraints;null!=g.datePackage&&0<g.datePackage.length?require(g.datePackage,g.datePackage+".locale",function(){this._showDatePickerAction(a,b,c,d)}):this._showDatePickerAction(a,b,c,d)},_showDatePickerAction:function(a,b,c,d){this.closeDatePicker&&this.closeDatePicker();var g=this.userinfo.calendarConstraints,f=this.getVisibleStartDate();null!=b&&(f=this._findEarliestStartDate(b));f||(f=(new Date).getDate());var k=new Date(f),k=new Date(f+6E4*(new Date(f)).getTimezoneOffset());
e.debug("CalendarWidget: Adjusting Time for TimeZone: {} - {} - {} - {}",f,new Date(f),(new Date(f)).toISOString(),(new Date(f)).getTimezoneOffset());var h=this,l;l=new c({lang:g.lang,lng:g.lng,dir:document.body.dir,constraints:g,value:k,maxHeight:"150",datePackage:g.datePackage,_close:function(){n.close(l);l.destroy();delete l},onChange:function(f){c===u&&(e.debug("CalendarWidget: Adjusting for TimeZone {}",f.getTimezoneOffset()),f=new Date(f.getTime()-6E4*f.getTimezoneOffset()));e.debug("OnChange: {}",
f);this._close();d(a,b,f)}});n.moveOffScreen(l);dojo.marginBox(l.domNode,{w:100});l.startup&&l.startup();this.closeDatePicker=function(){try{n.close(l)}catch(a){}h.DATE_SELECTION_IN_PROGRESS=!1};this.DATE_SELECTION_IN_PROGRESS=!0;n.open({popup:l,x:this.eventPageX,y:this.eventPageY});e.debug("Showing Calendar Popup: x,y; {},{}",this.eventPageX,this.eventPageY)},_createZoomRange:function(a,b){var c={},d=b-a;864E5>d?(c.start=a-(864E5-d)/2,c.end=c.start+864E5):6048E5>d?(c.start=a-(6048E5-d)/2,c.end=c.start+
6048E5):(c.start=a-864E5,c.end=b+864E5);return c},ZoomTo:function(a,b,c,d){d=d||!1;null!=a&&null===b&&(e.debug("ZoomTo: Adjusting end because it is null"),b=a+this.DURATION_ONE_DAY,d=!0);e.debug("{} ZoomTo: {}, {}",this.TAG,new Date(a),new Date(b));if(!a||!b||null==a||null==b||0>=a||0>=b||a==b)e.warn("{} ZoomTo called with invalid start {} and end times {}",this.TAG,a,b);else{e.debug("{} Zooming Befor Create Range: {} - {}",this.TAG,a,b);range=!0===d?{start:a,end:b}:this._createZoomRange(a,b);e.debug("{} Zooming After Create Range: {} - {}",
this.TAG,range.start,range.end);try{e.debug("{} Zooming: {} - {}",this.TAG,new Date(range.start),new Date(range.end)),this.grid.ZoomTo(new Date(range.start),new Date(range.end),c)}catch(g){e.error("{} error during ZoomTo",this.TAG,g)}e.debug("{} Zoomed: {} - {}",this.TAG,new Date(range.start),new Date(range.end))}},getVisibleStartDate:function(){var a=this.grid.GetScrollLeft(2),a=this.grid.GetGanttDate(a,this.GANTTCOL);e.debug("Gantt Date: "+a);return a},getVisibleMidDate:function(){var a=this.grid.GetBodyWidth(2),
a=this.grid.GetScrollLeft(2)+a/2;return this.grid.GetGanttDate(a,this.GANTTCOL)},OnClick:function(a,b,c,d,e,f){this.hideTooltip(a,b,c,d,e,f);return!1},hideTooltip:function(a,b,c,d,e,f){this.closeDatePicker&&this.closeDatePicker();if(f.metaKey)return this.OnRightClick(a,b,c,d,e,f)}})});
