const sampleActivityItem = {
  id: 'BSTA1125',
  scenarioname: 'BST_GS',
  skdprojectid: 88,
  name: 'Install Fuel Pump',
  duration: '100',
  sneconstraint: '2022-02-18T14:57:17+00:00',
  fnlconstraint: '2022-02-19T14:57:17+00:00',
  wopriority: 1,
  interruptible: false,
  wonum: '1000',
  wogroup: '1000',
  resourcename: 'Carpenter',
  laborname: 'Adams',
  laborhrs: '4',
  assetnum: 'ASSET1',
  location: 'LOC1',
  isemergency: true,
  assignstatus: 'WAITASGN',
  assignmentid: 2114,
  assignstatus_maxvalue: 'WAITASGN',
  assignstatus_description: 'Waiting for assignment',
};

export default sampleActivityItem;
