define("dojo/_base/lang dojo/_base/window dojo/dom-class dojo/on dojo/mouse dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/topic ibm/miniapp/scheduler/gantt/GanttActions dijit/Tooltip dojo/dom-geometry dijit/TooltipDialog dijit/popup dojo/json dojo/_base/array dojo/dom ibm/miniapp/scheduler/SingleGanttView ibm/miniapp/scheduler/gantt/SchedulerWorkView".split(" "),function(f,t,u,v,w,n,x,k,l,y,z,A,B,C,m,D,E,F,p){var q=JSON.stringify([235,255,
255]),r=JSON.stringify([224,244,244]);return n([p],{constructor:function(a){this.ViewName="SchedMax";this.ganttDisableDependencies=!1;this.selectedLevel=-1},addCustomActions:function(a){window.Grids.ZoomToWork=f.hitch(this,this.ZoomToWork)},attachExtraGridEvents:function(a){var b=this;TGSetEvent("OnZoom",a,function(a,e,h,c){k.debug("OnZoom: {}, {}, {}",e,h,c);b._otherGRID&&b._otherGRID.reloadRequired&&b.fetch("_getSelectedTab",b._ioOptions({})).then(function(a){b._otherGRID.TAG==a.currentResourceMiniapp+
"["+b._otherGRID.gridId+"]"&&(b._otherGRID.reloadRequired=!1,b._otherGRID._newGridID(),b._otherGRID._initGANTT())})});TGSetEvent("OnSelectGanttRunRect",a,f.hitch(this,this.OnSelectGanttObjects));TGSetEvent("OnClick",a,f.hitch(this,this.OnClick));TGSetEvent("OnExpand",a,f.hitch(this,this.OnExpand));TGSetEvent("OnExport",a,f.hitch(this,this.OnExport));TGSetEvent("OnRenderPageFinish",a,f.hitch(this,this.OnRenderPageFinish));this.subscribeOn("skd.workview.constraintedited",f.hitch(this,this._constraintEdited));
this.subscribeOn("skd.workview.unloadedConstraintRemoved",f.hitch(this,this._unloadedConstraintsRemoved));this.subscribeOn("skd.workview.unloadedConstraintAdded",f.hitch(this,this._unloadedConstraintsAdded));this.subscribeOn("skd.request.workview.reference",f.hitch(this,this.publishResponseWorkViewReference));this.subscribeOn("skd.workview.refreshSelected",f.hitch(this,this.__refreshSelected));AddEvent("OnAfterSectionResize",this.gridId,function(){b._onSyncRequest()})},OnExpand:function(a,b){-1<this.selectedLevel&&
this.fetch("_expandToLevel",this._ioOptions({level:-1})).then(function(a){})},OnRenderPageFinish:function(a,b){var d=this,e=null;!this.ganttBackground&&a.Cols.G.GanttBackground&&(this.ganttBackground=a.Cols.G.GanttBackground.split("White").join("WORKAlternate"));var h=this.GetRootActivity(a);h.firstChild&&this._applyToRow(h,1,function(a,b){e||(e=0);a._OBJECTNAME&&(1==e?a.GGanttBackground=d.ganttBackground:delete a.GGanttBackground,e=1-e);return!0});this.Refresh(255)},_expandToLevel:function(a,b){var d=
parseInt(a.id),e=this._GetSelectedRowIds(this.grid,"G",b),h=this;this.selectedLevel=d;this.fetch("_expandToLevel",h._ioOptions({level:d})).then(function(a){a=h.grid.GetRowById(e);h.grid.ClearSelection();h.grid.Expand(a);h._applyToRow(a,[],function(a,b){a.Level>=d?h.grid.Collapse(a):0==a.Expanded&&h.grid.Expand(a);return!0})})},publishResponseWorkViewReference:function(a){this.publishTo("skd.response.workview.reference",{grid:this.grid,view:this})},OnAfterSave:function(a,b,d){this.inherited(arguments);
0<=b&&!this.locked&&this.showMessage("system#saverecord")},OnClick:function(a,b,d,e,h,c){this.inherited(arguments);"TOGGLEDEPS"==d&&(this.ganttDisableDependencies=!this.ganttDisableDependencies)},OnGetGanttSideHtml:function(a,b,d,e,h,c,f,g,k,l){return this.ganttDisableDependencies?null:this.inherited(arguments)},OnRenderFinish:function(a){this._firstRender||(this._firstRender=!0,k.debug("{} Has Been Rendered",this.TAG),this.waitlockid&&(k.debug("{} Sending waitlockcomplete message: {}",this.TAG,this.waitlockid),
l.publish("miniapp.waitlockcomplete",this.waitlockid)),this.publishLater("skd.ui.new.grid",{grid:this}),l.publish("miniapp.hideprogress",this.domid),k.debug("{} TreeGrid Version: {}, Text Version: {}, Defaults Version: {}",this.TAG,Component.Version,this.grid.TextVersion,this.grid.DefaultsVersion,this.grid));var b=this;this.invokeLater(function(){b.showCurrentDateLine&&b._updateGanttLinesRepeat()},500,"ganttlinesrepeat")},OnFocus:function(a,b,d,e,h,c){this.inherited(arguments)},_newTreeGridOptions:function(){var a=
{Data:{Url:this.toUrl("async_load_gantt_pages",this._ioOptions({})),Timeout:300,Format:"JSON",Method:"POST"},Page:{Url:this.toUrl("async_load_gantt_page",this._ioOptions({})),Timeout:300,Format:"JSON",Method:"POST"},Layout:{Url:this.toUrl("async_load_gantt_project_ui",this._ioOptions({appname:this.appname,projectid:this.projectid}))}};a.Export={Format:"JSON",Url:this.toUrl("async_export_xls",this._ioOptions({})),Type:"Settings"};a.ExportPDF=a.ExportPDF||{Url:this.servletBase+"/utility/tg/ExportPdf.jsp",
Param:{Source:"ExportPDF.html",Layoutxml:a.Layout.Url,Dataxml:this.toUrl("async_load_gantt_data",this._ioOptions({}))},Type:"Gantt,Settings,Expanded,Selected,Changes"};this.Layoutxml=a.Layout.Url;this.Dataxml=this.toUrl("async_load_gantt_data",this._ioOptions({}));return a},OnShowTooltip:function(a,b,d,e,h,c){var f=this;if("Panel"!=d&&("name"!=d||c&&c.srcElement&&c.srcElement.id&&-1!=c.srcElement.id.indexOf("TGCell_"))&&"startTime"!=d&&"endTime"!=d&&"Data"===b.Kind){if("G"==d){var g=a.GetGanttXY(b,
d,e,h);k.debug("Gantt Object",g);if(null!=g&&null!=g.Point)return this.fetch("async_get_tooltip_for_point",f._ioOptions({projectid:f.projectid,id:g.Row.id,point_index:g.PointIndex})).then(function(a){f._showTooltip(a,c,g.Row)}),!1;if(null==g||null==g.Main)if(null!=g&&null!=g.RunId)b=this.GetRowById(g.RunId),k.debug("Using RUN BAR for ToolTip",b);else return null!=g&&"dependency"==g.Type?(k.debug("Using Dependency for ToolTip",g),"0"===g.DependencyFromBox?this._fetchDependencyTooltip(g.DependencyFrom,
g.DependencyTo,c):this._fetchDependencyTooltip(g.DependencyFromBox,g.DependencyToBox,c)):c&&c.originalTarget&&c.originalTarget.className&&-1!==c.originalTarget.className.indexOf("skd-icon")||c&&c.target&&c.target.className&&-1!==c.target.className.indexOf("skd-icon")?(d=c.originalTarget?-1<c.originalTarget.className.indexOf("left"):-1<c.target.className.indexOf("left"),this._fetchUnloadedDependencyTooltip(g.Row.id,d,c)):(a=this.getDateForX(e),k.debug("Gantt Click at {} is date {} ({})",e,a,(new Date(a)).toUTCString()),
this.fetch("async_get_tooltip_for_date",f._ioOptions({projectid:f.projectid,id:b.id,col:d,date:a})).then(function(a){f._showTooltip(a,c,b)})),!1}this.fetch("async_get_tooltip",f._ioOptions({projectid:f.projectid,id:b.id,col:d})).then(function(a){f._showTooltip(a,c,b)})}},_fetchUnloadedDependencyTooltip:function(a,b,d){var e=this;this.fetch("async_get_tooltip_unloaded_cpm",e._ioOptions({projectid:e.projectid,activityid:a,fromdependency:b})).then(function(a){e._showTooltip(a,d)})},GOTOTODAYAction:function(a,
b,d,e,f,c){this._GotoTodayToolbarAction()},GOTOSELECTDAYAction:function(a,b,d,e,f,c){this._GotoSelectedDayToolbarAction(c)},ZOOMWEEKAction:function(a,b,d,e,f,c){this._ZoomToWeekToolbarAction()},_unloadedConstraintsRemoved:function(a){var b=m.parse(a);null==b?k.error("Unable to parse dependency item: {}",a):(a=this.grid.GetRowById(b.id),b.incoming?delete a.mxLeftIconClass:delete a.mxRightIconClass,this.grid.RefreshRow(a),this.grid.RefreshGantt(1))},_unloadedConstraintsAdded:function(a){var b=m.parse(a);
null==b?k.error("Unable to parse dependency item: {}",a):(a=this.grid.GetRowById(b.id),b.incoming?a.mxLeftIconClass="skd-icon-to-dependencies":a.mxRightIconClass="skd-icon-from-dependencies",this.grid.RefreshRow(a),this.grid.RefreshGantt(1))},GetRootActivity:function(a){return a.Body&&a.Body.firstChild?a.Body.firstChild:null},OnCfgSaved:function(a,b){this.inherited(arguments);return!1},MarkToBeSaved:function(){this.showMessage("system#saverecord")},OnGetColor:function(a,b,d,e,f,c){if(!a.Cols[d]||
!a.Cols[d].Visible)return null;a=null;e=JSON.stringify([e,f,c]);if(q==e||r==e)a="white",b.WhiteBackground=1;return a},OnContextMenuItemSelected:function(a,b,d){this.inherited(arguments);"COMMSELECTED"==a.Value&&(b._UNCOMMITTED=0,this.grid.RefreshRow(b))}})});
