define("dojo/aspect dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang ibm/miniapp/scheduler/gantt/GanttWidget ibm/miniapp/scheduler/gantt/BaseResourceViewWidget ibm/miniapp/scheduler/gantt/CommonResourceHoursView com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(g,m,n,d,e,p,q,r,t){return m([p,n,q,r,t],{constructor:function(a){d.debug("{} Base Bean Target set to {} for view",this.gridId,this.mxtargetbean,a);this.showCurrentDateLine=
!1;this.RefreshIcon=this.aspectShowHideElHandle=this.linkedWorkView=this.linkedWorkViewGrid=null;this.lastEnd=this.lastStart=-1;this.PDFSource="ExportPDF.html";this.Dataxml=this.Layoutxml=null},postCreate:function(){this.inherited(arguments);var a=this;this.aspectShowHideElHandle=g.after(window,"hideShowElement",function(b,c){b&&b.querySelector&&b.querySelector("#"+a.domId)&&(d.debug("ShowHideEl: called with {}",c),a.onVisibilityChanged(a.isVisible()))},!0)},destroy:function(){this.inherited(arguments);
this.aspectShowHideElHandle&&(this.aspectShowHideElHandle.remove(),this.aspectShowHideElHandle=null)},onVisibilityChanged:function(a){d.debug("Visibility Has Changed: Visible: {}",a);a?(this._updateSync(),this.onUpdateResourceViewRequested()):(d.debug("Disabling Grid Sync"),this.grid.SyncId=null,this.lastEnd=this.lastStart=-1)},_newTreeGridOptions:function(a,b){a=a||-1;b=b||-1;this.lastStart=a;this.lastEnd=b;var c={Data:{Url:this.toUrl("async_load_project_data",{start:a,end:b}),Timeout:300},Layout:{Url:this.toUrl("async_load_project_ui",
this._ioOptions({appname:this.appname,projectid:this.projectid}))}};c.ExportPDF=c.ExportPDF||{Url:this.servletBase+"/utility/tg/ExportPdf.jsp",Param:{Source:"ExportPDF.html",Layoutxml:c.Layout.Url,Dataxml:this.toUrl("async_load_gantt_data",this._ioOptions({}))},Type:"Gantt,Settings,Expanded,Selected,Changes"};this.Layoutxml=c.Layout.Url;this.Dataxml=this.toUrl("async_load_project_data",this._ioOptions({start:this.startDate,end:this.endDate}));return c},addCustomActions:function(a){},upgradeTGInstance:function(a){this.inherited(arguments);
this.grid._printToPDF=e.hitch(this,this._printToPDF);this.grid._showLoadAvailNumbersAction=e.hitch(this,this._showLoadAvailNumbersAction);this.grid._hideLoadAvailNumbersAction=e.hitch(this,this._hideLoadAvailNumbersAction)},attachExtraGridEvents:function(a){this.inherited(arguments);d.debug("{} Registering extra grid events",this.TAG);this.subscribeOn("skd.workview.updated",e.hitch(this,this.onWorkViewChanged));this.subscribeOn("skd.max.update.resourceview",e.hitch(this,this.onUpdateResourceViewRequested));
this.subscribeOn("skd.response.workview.reference",e.hitch(this,this.onWorkViewReferenceReceived));AddEvent("OnZoom",a,e.hitch(this,this.OnZoomChanged));AddEvent("OnScroll",a,e.hitch(this,this.OnScrollChanged));AddEvent("OnUpdated",a,e.hitch(this,this.DisableRefresh));AddEvent("OnExport",a,e.hitch(this,this.OnExport))},OnExport:function(a,b,c){if(1==c){c=this.servletBase+"/utility/tg/ExportPdf.jsp";var d=this.servletBase.replace("/webclient",""),e=this.Layoutxml,f=this.Dataxml;this.pdfExportBaseUrl&&
(e=e.replace(d,this.pdfExportBaseUrl),f=f.replace(this.servletBase,this.pdfExportBaseUrl));e=encodeURIComponent(e);f=encodeURIComponent(f);b=encodeURI(b);var d=encodeURI(this.projectName),k=Math.round(25.4*a.PrintPageWidth/a.PrintDPI+a.PrintMarginWidth),l=Math.round(25.4*a.PrintPageHeight/a.PrintDPI+a.PrintMarginHeight);c=c+"?PDFName="+a.PDFName+"&PDFFormat="+a.PDFFormat+"&Data="+b+"&PDFPageOrientation="+a.PrintPageOrientation;c=c+"&PrintMarginWidth="+a.PrintMarginWidth+"&PrintMarginHeight="+a.PrintMarginHeight+
"&PrintDPI="+a.PrintDPI;c=c+"&PDFPageSize="+a.PrintPageSize+"&Layoutxml="+e+"&Dataxml="+f+"&Source="+this.PDFSource;c=c+"&ProjectName="+d+"&PrintPageWidth="+k+"&PrintPageHeight="+l+"&PDFFitPage="+a.PDFFitPage;b=new XMLHttpRequest;b.open("POST",c,!0);b.send(null);this.ShowProgress(a,90,30,500);return!0}return!1},OnScrollChanged:function(a,b,c,d,e,f,k,l,g){this.OnZoomChanged()},OnZoomChanged:function(){-1!=this.lastStart&&-1!=this.lastEnd&&this.linkedWorkView&&this.invokeLater(e.hitch(this,this._OnZoomChanged),
200,"zoomed")},_OnZoomChanged:function(){this.grid.MidWidth=this.linkedWorkViewGrid.GetBodyWidth(1);var a=this.linkedWorkView.getVisibleRange(),b=this.getVisibleRange();d.debug("START DATE: {}",new Date(this.grid.GetGanttDate(0,"G")));d.debug("WORK RANGE: {} -> {} [SCROLL: {}]",new Date(a.start),new Date(a.end),this.linkedWorkView.grid.GetScrollLeft(2));d.debug("RESV RANGE: {} -> {} [SCROLL: {}]",new Date(b.start),new Date(b.end),this.grid.GetScrollLeft(2));d.debug("LAST RANGE: {} -> {}",new Date(this.lastStart),
new Date(this.lastEnd));(b.start<this.lastStart||b.end>this.lastEnd)&&10<Math.abs(this.lastStart-b.start)/this.getMillisecondsFerPixel()&&this.EnableRefresh()},showResourceForDateRange:function(a,b,c){try{d.debug("Requesting resource information: start: {}, end: {}",new Date(a),new Date(b),c);var e=this._newTreeGridOptions(a,b);this.grid.Data.Data.Url=e.Data.Url;this.grid.ShowMessage(this.label("loading_resources"),10);var h=this;this.grid.ReloadBody(function(){h._updateSync();h.grid.HideMessage()})}catch(f){d.error("Refresh Failed",
f)}},updateResources:function(a){d.debug("Updating Resources",a)},onWorkViewReferenceReceived:function(a){d.debug("Got a Work View Reference'",a);a.grid&&(this.linkedWorkViewGrid=a.grid,this.linkedWorkView=a.view,this.onUpdateResourceViewRequested(this.getVisibleRangeForGrid(a.grid)))},REFRESH_RESOURCESAction:function(){d.debug("REFRESH RESOURCES CALLED");this.onUpdateResourceViewRequested()},onUpdateResourceViewRequested:function(a){if(this.isVisible())if(this.DisableRefresh(),a&&a.start&&a.end)this.showResourceForDateRange(a.start,
a.end,a);else if(this.linkedWorkView)this.onUpdateResourceViewRequested(this.linkedWorkView.getVisibleRange());else this.publishTo("skd.request.workview.reference",null);else d.debug("We are not visible:  Ignoring request to update.")},onWorkViewChanged:function(a,b){this.isVisible()?this.EnableRefresh():d.debug("We are not visible:  Ignoring request to update.")},EnableRefresh:function(){d.debug("Enabling Refresh");this.grid.Toolbar.REFRESH_RESOURCESDisabled=0;this.grid.RefreshRow(this.grid.Toolbar)},
DisableRefresh:function(){d.debug("Disabling Refresh.");this.grid.Toolbar.REFRESH_RESOURCESDisabled=1;this.grid.RefreshRow(this.grid.Toolbar)},_getRefreshIcon:function(){if(this.RefreshIcon)return this.RefreshIcon;for(var a=this.grid.Toolbar.r1.querySelectorAll(".COToolHtmlIcon"),b=0;b<a.length;b++){var c=a[b].getAttribute("onmousedown");if(c&&0<=c.indexOf("REFRESH_RESOURCES")){this.RefreshIcon=a[b];break}}return this.RefreshIcon},onRefreshRequested:function(a){this.isVisible()?a&&a.sourceId&&-1!=
a.sourceId.indexOf("_SAVE")||a&&a.sourceId&&-1!=a.sourceId.indexOf("schedacm")?d.warn("Refresh Ignored because of Toolbar Save",a):this.inherited(arguments):d.debug("We are not visible:  Ignoring request to update.")},__OnNewGridRegistered:function(a){},_printToPDF:function(){this.grid.ActionExportPDF()},ShowProgress:function(a,b,c,d){var e=this;setTimeout(function(){a.ShowProgress("Export PDF","Preparing Print job...",null,c,b);c>=b?a.ShowMessageTime("Print job submitted.",2E3):(c+=30,e.ShowProgress(a,
b,c,d))},d)},_showLoadAvailNumbersAction:function(){this.showLoadAvailNumbers=1;this.grid.ShowMessage(this.label("loading_resources"),10);var a=this;this.grid.ReloadBody(function(){a.grid.HideMessage()})},_hideLoadAvailNumbersAction:function(){this.showLoadAvailNumbers=0;this.grid.ShowMessage(this.label("loading_resources"),10);var a=this;this.grid.ReloadBody(function(){a.grid.HideMessage()})}})});
