define(["dojo/_base/lang","dojo/_base/declare","com/ibm/tivoli/maximo/miniapps/_MaximoLog"],function(f,g,e){return g(null,{_refreshSelected:function(c){c=this._GetSelectedRowIds(this.grid,null,null);var d=this;""==c?d.grid.ShowMessageTime("No work records selected.",0):this.fetch("_refreshSelected",d._ioOptions({ids:c})).then(function(b){d.grid.AddDataFromServer(b);if(b&&b.Changes&&b.Changes.length)for(var a=b.Changes,c=0;c<a.length;c++){var e=a[c],f=d.grid.GetRowById(e.id);null!=f&&(f._ASSIGNMENTID=
e._ASSIGNMENTID,d.grid.RefreshRow(f))}d.publishLater("skd.workview.updated",{grid:d.grid,result:b.Result});d.grid.RefreshGantt(1);d.grid.ClearSelection();d.showMessage("scheduler#refreshproject")})},_showWorkAction:function(c,d){e.debug("showWorkAction(): ",c);this.ZoomTo(d.startTime,d.endTime);return!0},_lockAction:function(c,d){var b=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(b,f.hitch(this,function(a){e.debug("before lock activity",c.Value,a,a.MODAPPOINTMENT);a.mxLeftIconClass=
"skd-icon-appointment";a.GGanttRunMove="All,Move,Selected,Entire,Vert,Mouse";a._READONLY_STARTEND=!0;this.SetValue(a,"MODAPPOINTMENT",!0,!0)}))},_unlockAction:function(c,d){var b=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(b,f.hitch(this,function(a){e.debug("before unlock activity",c.Value,a,a.MODAPPOINTMENT,a.APPTREQUIRED);"1"==a.APPTREQUIRED||"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?a.mxLeftIconClass="skd-icon-requirement":delete a.mxLeftIconClass;delete a.GGanttRunMove;
delete a._READONLY_STARTEND;this.SetValue(a,"MODAPPOINTMENT",!1,!0)}))},_reslockAction:function(c,d){var b=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(b,f.hitch(this,function(a){e.debug("before lock activity",c.Value,a,a.MODRESOURCELOCK);a.mxLeftIconClass="skd-icon-appointment";a.GGanttRunMove="All,Move,Selected,Entire,Slide,Mouse";a._READONLY_ASSIGNMENT=!0;this.SetValue(a,"MODRESOURCELOCK",!0,!0)}))},_resunlockAction:function(c,d){var b=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(b,
f.hitch(this,function(a){e.debug("before unlock activity",c.Value,a,a.MODRESOURCELOCK,a.APPTREQUIRED);"1"==a.APPTREQUIRED||"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?a.mxLeftIconClass="skd-icon-requirement":delete a.mxLeftIconClass;delete a.GGanttRunMove;delete a._READONLY_ASSIGNMENT;this.SetValue(a,"MODRESOURCELOCK",!1,!0)}))},newWorkActionReply:function(c,d,b){e.debug("newWorkActionReply()",d.Value,b,c);this.processReply(c)},deleteWorkActionReply:function(c,d,b){e.debug("deleteWorkActionReply()",
d.Value,b,c);this.processReply(c)},splitActionReply:function(c,d,b){e.debug("splitActionReply()",d.Value,b,c);this.processReply(c)},split3ActionReply:function(c,d,b){e.debug("split3ActionReply()",d.Value,b,c);this.processReply(c)},splitShiftActionReply:function(c,d,b){e.debug("splitShiftActionReply()",d.Value,b,c);this.processReply(c)},mergeWorkActionReply:function(c,d,b){e.debug("mergeWorkActionReply()",d.Value,b,c);this.processReply(c)},assigntoselectedlocationsReply:function(c,d,b){e.debug("assigntoselectedlocationsReply()",
d.Value,b,c)},reloadModel:function(){this.grid.Reload(null,null,!1)},deleteActionReply:function(c,d,b){e.debug("deleteActionActionReply()",d.Value,b,c)},unassignReply:function(c,d,b){e.debug("unassignReply()",d.Value,b,c);this.processReply(c)},assigntoReply:function(c,d,b){e.debug("assigntoReply()",d.Value,b,c);this.processReply(c)},processReply:function(c){if(c&&c.Changes&&c.Changes.length){var d=c.Changes;this.grid.AddDataFromServer(c);for(c=0;c<d.length;c++){var b=d[c],a=this.grid.GetRowById(b.id);
null!=a&&(a.ISASSIGNMENT=b.ISASSIGNMENT,a._OBJECTNAME=b._OBJECTNAME,a._REFOBJECTNAME=b._REFOBJECTNAME,a._PARENT_WONUM=b._PARENT_WONUM,a._WONUM=b._WONUM,a.WONUM=b.WONUM,a.WOPARENT=b.WOPARENT,a.WOGROUP=b.WOGROUP,a.TASKID=b.TASKID,a._INTERNALSTATUS=b._INTERNALSTATUS,a._OBJECTNAME=b._OBJECTNAME,a.WORKLOG=b.WORKLOG,a.STATUS=b.STATUS,a.SKILLLEVEL=b.SKILLLEVEL,a.mxRightIconClass=b.mxRightIconClass,a.mxRightIconClick=b.mxRightIconClick,null!=b.TASKID&&(a.TASKID=b.TASKID),a.APPTREQUIRED=b.APPTREQUIRED,a.MXDURATION=
b.MXDURATION,a.duration=b.duration,a.startTime=b.startTime,a.endTime=b.endTime,a.duration=b.duration,a._ASSIGNMENTID=b._ASSIGNMENTID,a._ASSIGNMENTCREW=b._ASSIGNMENTCREW,a._ASSIGNMENTCREWTYPE=b._ASSIGNMENTCREWTYPE,a._ASSIGNMENTSKILL=b._ASSIGNMENTSKILL,a._ASSIGNMENTCRAFT=b._ASSIGNMENTCRAFT,a._Resources=b._Resources,a._ASSIGNMENTLABOR=b._ASSIGNMENTLABOR,a.GGanttBackground=b.GGanttBackground,a.IsSummary=b.IsSummary,a.ERRVAL=b.ERRVAL,this.SetValue(a,"startTime",a.startTime,!0),this.SetValue(a,"endTime",
a.endTime,!0),this.grid.RefreshRow(a));a=b._OLDPARENTID;b=b.Parent;null!=a&&(a=this.grid.GetRowById(a),this.grid.RefreshRow(a));null!=b&&(b=this.grid.GetRowById(b),this.grid.RefreshRow(b))}null!=this._focusGanttObject&&(delete this._focusGanttObject._GGanttClassOld,delete this._focusGanttObject.GGanttClass,delete this._focusGanttObject._SKDRunClassOld,delete this._focusGanttObject._SKDRunClass);this.grid.RefreshGantt(1);this._focusGanttObject=null;this.grid.ClearSelection();this.publishTo("skd.refreshResource",
null)}else this._focusGanttObject=null,this.grid.ClearSelection()}})});
