define("dojo/_base/declare dojo/aspect com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang ibm/miniapp/scheduler/gantt/GanttWidget com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(e,f,g,b,d,h,k){return e([h,g,k],{constructor:function(a){this.linkedWorkViewGrid=this.linkedWorkView=null;this.reloadRequired=!1;var c=this;this.aspectAfterResize=f.after(c,"resize",function(a){try{c._updateGanttPosition()}catch(d){b.debug("Scheduler encountered and error before resize",
d)}});this.actions="REFRESH REFRESHALL COMMIT COMMITCONSTRAINTS VMAINSNRIO selectrecord longopcheck RECALPC MOVETODFLT SWSCEN cps_optmz publish scenariocps ROLLPRJ PRJCALCRON CALCCOST snapshot reslevel_optmz capplan_optmz scenariom scenarior scenarioc manresults odmerunreport msgbox PREVIOUS NEXT UPDSUM schacm_workview_viewermax_miniapp-miniapp_miniapp toBeSaved".split(" ")},destroy:function(){this.aspectAfterResize&&this.aspectAfterResize.remove()},attachExtraGridEvents:function(a){this.inherited(arguments);
b.debug("Listening for Linked WorkView to be destroyed");this.subscribeOn("skd.workview.destroyed",d.hitch(this,this._onLinkedViewDestroyed))},_onLinkedViewDestroyed:function(){b.debug("{}: Destroying our Resource view, since, the WorkView is destroyed",this.TAG);this._removeOldGrid();b.debug("{}: Destroyed our Resource view",this.TAG)},_applyScheduleWindow:function(a,b){},_updateGanttLines:function(){},onSideNavResized:function(){b.debug("Resource View: Side Nav Changed");this.invokeLater(d.hitch(this,
this._updateSync),100,"resize")},resize:function(){this.isVisible()&&(this.inherited(arguments),this.invokeLater(d.hitch(this,this._updateSync),100,"resize"))},OnRenderFinish:function(a){this.inherited(arguments);b.debug("{} Load View Render Fishined, Sending Post Render Events",this.TAG);a.HideCol("_resizer");a.ShowCol("_resizer");this.invokeLater(d.hitch(this,this._updateSync),100,"renderfinish")},OnDblClick:function(a,b,d,e,f,g){this.OnDblClick_ZoomToResourceLoadAvail(a,b,d,e,f,g)},_updateGanttPosition:function(){if(this.isVisible())if(b.debug("{}: Resource View Sync",
this.TAG),this.reloadRequired)this.reloadRequired=!1,this._createUI();else if(this.linkedWorkView)if(this.linkedWorkViewGrid.Rendering||this.linkedWorkViewGrid.Loading||this.grid.Rendering||this.grid.Loading)b.debug("Resource View is waiting for Work View to complete it's Rendering..."),this.invokeLater(d.hitch(this,this._updateGanttPosition),100,"resourceRender");else{var a=this.grid.Cols.G,c=this.linkedWorkViewGrid.Cols.G;a.GanttZoom=c.GanttZoom;a.GanttZoomDate=c.GanttZoomDate;a.GanttZoomDateAlign=
c.GanttZoomDateAlign;a.GanttZoomChange=c.GanttZoomChange;a.GanttZoomFit=c.GanttZoomFit;a.GanttZoomFitWidth=c.GanttZoomFitWidth;a=this.linkedWorkView.getVisibleRange();this.grid.ZoomTo(a.start,a.end);b.debug("Grid Sync Set to {}",this.grid.SyncId)}else b.debug("No Registered Linked Work View yet. Resource section position update skipped.")},_updateSync:function(){if(this.isVisible())if(b.debug("{}: Resource View Sync",this.TAG),this.reloadRequired)this.reloadRequired=!1,this._createUI();else if(this.linkedWorkView)if(this.linkedWorkViewGrid.Rendering||
this.linkedWorkViewGrid.Loading||this.grid.Rendering||this.grid.Loading)b.debug("Resource View is waiting for Work View to complete it's Rendering..."),this.invokeLater(d.hitch(this,this._updateSync),100,"resourceRender");else{var a=this.grid.Cols.G,c=this.linkedWorkViewGrid.Cols.G;if(a.GanttZoom!=c.GanttZoom||a.GanttZoomDate!=c.GanttZoomDate||this.grid.LeftWidth!=this.linkedWorkViewGrid.GetBodyWidth(0)||this.grid.RightWidth!=this.linkedWorkViewGrid.GetBodyWidth(2))this.domNode.style.width=this.linkedWorkView.domNode.offsetWidth+
"px",this.grid.SyncId=null,this.grid.LeftWidth=this.linkedWorkViewGrid.GetBodyWidth(0),this.grid.MidWidth=this.linkedWorkViewGrid.GetBodyWidth(1),this.grid.RightWidth=this.linkedWorkViewGrid.GetBodyWidth(2),this.grid.SetScrollLeft(this.linkedWorkViewGrid.GetScrollLeft(2),2),this.grid.Cols.G.Width=this.linkedWorkViewGrid.Cols.G.Width,this.grid.Cols._gresizer.Width=this.linkedWorkViewGrid.Cols._gresizer.Width,this.grid.SyncId=this.linkedWorkViewGrid.SyncId,this.grid.Update(),this.grid.UpdatePos(),a=
{view:this},this.linkedWorkView._onChildSizeUpdate&&this.linkedWorkView._onChildSizeUpdate(a),b.debug("Grid Sync Set to {}",this.grid.SyncId),this.invokeLater(d.hitch(this,this._updateGanttPosition),100,"resourceRender")}else b.debug("No Registered Linked Work View.  Update Sync Ignored."),this.publishTo("skd.request.workview.reference",null)},_removeOldGrid:function(){this.inherited(arguments);b.debug("{}: removing old grid reference",this.TAG);this.linkedWorkView=this.linkedWorkViewGrid=null},onRefreshRequested:function(a){if(a.type&&
this.actions.includes(a.type)||a.targetId&&this.actions.includes(a.targetId))this.reloadRequired=!0;a&&a.sourceId&&-1!=a.sourceId.indexOf("schedacm")&&a.type&&-1!=a.type.indexOf("SAVE")&&(this.reloadRequired=!0);a&&a.sourceId&&-1!=a.sourceId.indexOf("_SAVE")?b.warn("Refresh Ignored because of Toolbar Save",a):this.grid&&this.grid.Disable()}})});
