define("dojo/_base/lang dojo/_base/declare dojo/_base/array com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/date ibm/tivoli/mbs/dijit/DateTimeCalendar dijit/Calendar dijit/popup".split(" "),function(p,t,l,f,q,u,r,n){return t(null,{DURATION_ONE_HOUR:36E5,DURATION_ONE_DAY:864E5,DURATION_ONE_WEEK:6048E5,_unselectAllRunBoxes:function(){var b=this,a=this.grid.GetGanttRunSelectedBoxes();a&&l.forEach(a,function(a,d){b.grid.SelectGanttRunBox(a,!1)});this.grid.ClearSelection()},OnAddViewNotesClicked:function(b,
a){this._unselectAllRunBoxes();var c=this;if(!b.Cols.G)return!1;var d=b.ARow;value=d?d.id:a.G;var e=this._GetSelectedRowIds(b,"G",a);this.fetch("async_get_table_context_menu",c._ioOptions({projectid:c.projectid,id:e,col:"G",value:value,selection:{}})).then(function(a){if(a&&a.Items)for(var b=0;b<a.Items.length;b++)if("writeworklog"==a.Items[b].Value){c.OnContextMenuItemSelected(a.Items[b],d);break}});return!0},_showWorkAction:function(b,a){f.debug("showWorkAction(): ",b);if(a.startTime)return this.ZoomTo(a.startTime,
a.endTime),!0},_GotoTodayToolbarAction:function(){f.debug("Goto TODAY");try{var b=this._today().getTime();this.ZoomTo(b,b+this.DURATION_ONE_DAY)}catch(a){f.error("Goto TODAY failed",a)}},_today:function(){var b=new Date;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);return b=new Date(this.TZDateToTGDate(b.getTime()))},_GotoSelectedDayToolbarAction:function(b){f.debug("Goto Selected DAY [TG Event]>",b);try{this.eventPageX=b.ClientX||b.clientX,this.eventPageY=b.ClientY||b.clientY,
this._selectDatePopupAction("_movetoSelectedDate",null,r,p.hitch(this,this._GotoSeletedDateActionHandler))}catch(a){f.error("Goto TODAY failed",a)}},_GotoSeletedDateActionHandler:function(b,a,c){b=this.TZDateToTGDate(c.getTime());this.ZoomTo(b,b+this.DURATION_ONE_DAY)},_ZoomToWeekToolbarAction:function(){try{var b=this.grid.Cols.G.GanttChartMaxStart,a=this.grid.Cols.G.GanttChartMinEnd;if(a-b<7*this.DURATION_ONE_DAY)f.debug("ZoomToWeek Zoom Entire Project: {},{}",new Date(b),new Date(a)),this.ZoomTo(b,
a,null,!0);else{var c=this.grid.GetBodyWidth(2),d=this.grid.GetScrollLeft(2)+c/2,e=new Date(this.grid.GetGanttDate(d,"G"));e.setHours(e.getHours(),0,0,0);var g=3.5*this.DURATION_ONE_DAY,b=new Date(e.getTime()-g);b.setHours(0,0,0,0);a=new Date(e.getTime()+g);a.setHours(23,59,0,0);this.ZoomTo(b.getTime(),a.getTime(),1E3,!0)}}catch(m){f.error("Zoom To Week Failed",m)}},_deleteConstraintAction:function(b,a){f.debug("Delete Constraint",b,this._EDIT_DEPENDENCY);var c=this._EDIT_DEPENDENCY,c=this.grid.GetDependencies(c.DependencyFrom,
null,null,c.DependencyTo,c.DependencyType);f.debug("Constraint",c);this.grid.DeleteDependencies(c)},_moveToNextHourAction:function(b,a){this._moveToDateOffsetAction(b,a,this.DURATION_ONE_HOUR)},_moveToNextDayAction:function(b,a){this._moveToDateOffsetAction(b,a,this.DURATION_ONE_DAY)},_moveToTodayAction:function(b,a){var c=this._localToMaxTz(new Date);this._moveToDay(b,a,c)},_moveToDay:function(b,a,c){var d=this.TGDateToUserTZDate(this._findEarliestStartDate(a));if(d&&0!=d){d=new Date(d);c.setHours(d.getHours());
c.setMinutes(d.getMinutes());c.setSeconds(d.getSeconds());var e=q.difference(d,c,"day")*this.DURATION_ONE_DAY;f.debug("DUR: {}-{}={}",c,d,e);this._moveToDateOffsetAction(b,a,e)}},_moveToDayPopupAction:function(b,a){this._selectDatePopupAction(b,a,r,p.hitch(this,this._moveToDay))},_setToDateTimePopupAction:function(b,a){this._selectDatePopupAction(b,a,u,p.hitch(this,this._setDateTimeAction))},_selectDatePopupAction:function(b,a,c,d){f.debug("_selectDatePopupAction(): Calendar Constraints ",this.userinfo.calendarConstraints);
var e=this.userinfo.calendarConstraints;null!=e.datePackage&&0<e.datePackage.length?require(e.datePackage,e.datePackage+".locale",function(){this._showDatePickerAction(b,a,c,d)}):this._showDatePickerAction(b,a,c,d)},_showDatePickerAction:function(b,a,c,d){this.closeDatePicker&&this.closeDatePicker();var e=this.userinfo.calendarConstraints,g=this.getVisibleMidDate();null!=a&&(g=this._findEarliestStartDate(a));g||(g=(new Date).getDate());var m;m=this.TGDateToUserTZDate(g);f.debug("CalendarWidget: Adjusting Time for TimeZone: {} - {} - {} - {}",
m,new Date(g),(new Date(g)).toISOString(),(new Date(g)).getTimezoneOffset());var k=this,h;h=new c({lang:e.lang,lng:e.lng,dir:document.body.dir,constraints:e,value:m,maxHeight:"150",datePackage:e.datePackage,_close:function(){n.close(h);h.destroy();delete h},onChange:function(c){f.debug("CalendarWidget: Adjusting for TimeZone {}",c.getTimezoneOffset());if("_setToDateTimePopupAction"==b.Value){var e=new Date(this.params.value);e.getHours()==c.getHours()&&e.getMinutes()==c.getMinutes()&&(c=c.getTime()-
e.getTime(),e=k._findEarliestStartDate(a),c=new Date(k.TGDateToTZDate(e)+c))}f.debug("OnChange: {}",c);this._close();d(b,a,c)}});n.moveOffScreen(h);h.startup&&h.startup();this.closeDatePicker=function(){try{n.close(h)}catch(a){}k.DATE_SELECTION_IN_PROGRESS=!1};this.DATE_SELECTION_IN_PROGRESS=!0;n.open({popup:h,x:this.eventPageX,y:this.eventPageY});f.debug("Showing Calendar Popup: x,y; {},{}",this.eventPageX,this.eventPageY)},_moveToDateOffsetAction:function(b,a,c){b=this.grid.GetRowById("toolbar");
if(null==b||"1"!=b.LOCKSCH)a=this._GetSelectedRows(this.grid,"G",a),this.moveToDateOffset(a,c)},moveToDateOffset:function(b,a){b=this.normalizeSelectedRows(b);var c=this,d=this._applyDatesFunction(a);this.grid.StartUpdate();var e=[];l.forEach(b,function(a,b){void 0!=a._READONLY&&a._READONLY||void 0!=a._READONLY_STARTEND&&a._READONLY_STARTEND||c._applyToRow(a,e,d);a&&null!=a._OBJECTNAME&&"PM"==a._OBJECTNAME&&(c.rightClickMove=!0)});this.grid.EndUpdate();f.debug("Moved {} rows",e.length);return e.length},
_findEarliestStartDate:function(b){b=this._GetSelectedRows(this.grid,"G",b);var a=this,c=function(a,b){a&&a.startTime&&(null==b.date?b.date=a.startTime:0>q.compare(a.startTime,b.date)&&(b.date=a.startTime));return!0},d={date:null};l.forEach(b,function(b,g){a._applyToRow(b,d,c)});return d.date},_applyDatesFunction:function(b){var a=this;return function(c,d){if(null==c)return!1;if(0<=l.indexOf(d,c.id))return!0;d.push(c.id);if((null==c.firstChild||0===c.firstChild.CanMove)&&c&&c.startTime){var e=a.grid.CheckGantt(c,
"startTime",c.startTime+b);0!=e&&a.SetValue(c,"startTime",e)}return!0}},_setDateFunction:function(b){var a=this;return function(c,d){if(null==c)return!1;if(0<=l.indexOf(d,c.id))return!0;d.push(c.id);if((null==c.firstChild||0===c.firstChild.CanMove)&&c&&c.startTime){var e=a.grid.CheckGantt(c,"startTime",b);0!=e&&a.SetValue(c,"startTime",e)}return!0}},_setDateTimeAction:function(b,a,c){a=this._GetSelectedRows(this.grid,"G",a);var d=this;c=this.TZDateToTGDate(c.getTime());var e=this._setDateFunction(c);
this.grid.StartUpdate();var g=[];l.forEach(a,function(a,b){void 0!=a._READONLY&&a._READONLY||void 0!=a._READONLY_STARTEND&&a._READONLY_STARTEND||d._applyToRow(a,g,e)});this.grid.EndUpdate();f.debug("Moved {} rows",g.length);f.debug("Applied Set Date function {} to {} rows with date {}",b.Value,g.length,c)},_refreshSelected:function(b){b=this._GetSelectedRowIds(this.grid,null,null);var a=this;""==b?a.grid.ShowMessageTime("No work records selected.",0):this.fetch("_refreshSelected",a._ioOptions({ids:b})).then(function(b){a.grid.AddDataFromServer(b);
a.publishLater("skd.workview.updated",{grid:a.grid,result:b.Result});a.grid.ClearSelection();a.showMessage("scheduler#refreshproject")})},_discardRefreshSelected:function(b){b=this._GetSelectedRowIds(this.grid,null,null);var a=this;""==b?a.grid.ShowMessageTime("No work records selected.",0):this.fetch("_discardRefreshSelected",a._ioOptions({ids:b})).then(function(b){var d=b.Changes;a.grid.AddDataFromServer(b);for(var e=0;e<d.length;e++){var g=d[e],f=a.grid.GetRowById(g.id);null!=f&&(f._INTERRUPTIBLE=
g._INTERRUPTIBLE,f.INTERRUPTIBLE=g.INTERRUPTIBLE,f.INTSHIFT=g.INTSHIFT,a.grid.RefreshRow(f))}var d=a._GetSelectedRows(a.grid,null,null),k;for(k in d)d[k]._UNCOMMITTED=0,a.grid.RefreshCell(d[k],"name");a.publishLater("skd.workview.updated",{grid:a.grid,result:b.Result});a.grid.ClearSelection();a.showMessage("scheduler#refreshproject")})}})});
