define(["dojo/_base/lang","dojo/_base/declare","com/ibm/tivoli/maximo/miniapps/_MaximoLog"],function(f,g,e){return g(null,{_showWorkAction:function(b,d){e.debug("showWorkAction(): ",b);this.ZoomTo(d.startTime,d.endTime);return!0},_deleteWorkAction:function(b,d){var c=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(c,f.hitch(this,function(a){e.debug("delete activity ",b.Value,a);this.grid.DeleteRow(a,2)}));this.Refresh(255)},_lockAction:function(b,d){var c=this._GetSelectedRows(this.grid,
"G",d);this._applyForEachRow(c,f.hitch(this,function(a){e.debug("before lock activity",b.Value,a,a.MODAPPOINTMENT);""!=b&&(a.mxLeftIconClass="skd-icon-appointment");"1"==a.MODRESOURCELOCK&&""!=b&&(a.mxLeftIconClass="skd-icon-appresourceloc");a.GGanttRunMove="All,Move,Selected,Entire,Vert,Mouse";a._READONLY_STARTEND=!0;""!=b&&this.SetValue(a,"MODAPPOINTMENT",!0,!0)}))},_unlockAction:function(b,d){var c=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(c,f.hitch(this,function(a){e.debug("before unlock activity",
b.Value,a,a.MODAPPOINTMENT,a.APPTREQUIRED);"1"==a.APPTREQUIRED||"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?""!=b&&(a.mxLeftIconClass="skd-icon-requirement"):"1"==a.MODRESOURCELOCK&&""!=b?a.mxLeftIconClass="skd-icon-resourceloc":delete a.mxLeftIconClass;delete a.GGanttRunMove;delete a._READONLY_STARTEND;""!=b&&this.SetValue(a,"MODAPPOINTMENT",!1,!0)}))},_reslockAction:function(b,d){var c=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(c,f.hitch(this,function(a){e.debug("before lock activity",
b.Value,a,a.MODRESOURCELOCK);""!=b&&(a.mxLeftIconClass="skd-icon-resourceloc");"1"==a.MODAPPOINTMENT&&""!=b&&(a.mxLeftIconClass="skd-icon-appresourceloc");a.GGanttRunMove="All,Move,Selected,Entire,Slide,Mouse";a._READONLY_ASSIGNMENT=!0;""!=b&&this.SetValue(a,"MODRESOURCELOCK",!0,!0)}))},_resunlockAction:function(b,d){var c=this._GetSelectedRows(this.grid,"G",d);this._applyForEachRow(c,f.hitch(this,function(a){e.debug("before unlock activity",b.Value,a,a.MODRESOURCELOCK,a.APPTREQUIRED);"1"==a.APPTREQUIRED||
"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?""!=b&&(a.mxLeftIconClass="skd-icon-requirement"):"1"==a.MODAPPOINTMENT&&""!=b?a.mxLeftIconClass="skd-icon-appointment":delete a.mxLeftIconClass;delete a.GGanttRunMove;delete a._READONLY_ASSIGNMENT;""!=b&&this.SetValue(a,"MODRESOURCELOCK",!1,!0)}))},newWorkActionReply:function(b,d,c){e.debug("newWorkActionReply()",d.Value,c,b);this.processReply(b)},splitActionReply:function(b,d,c){e.debug("splitActionReply()",d.Value,c,b);this.processReply(b)},
split3ActionReply:function(b,d,c){e.debug("split3ActionReply()",d.Value,c,b);this.processReply(b)},splitShiftActionReply:function(b,d,c){e.debug("splitShiftActionReply()",d.Value,c,b);this.processReply(b)},mergeWorkActionReply:function(b,d,c){e.debug("mergeWorkActionReply()",d.Value,c,b);this.processReply(b)},assigntoselectedlocationsReply:function(b,d,c){e.debug("assigntoselectedlocationsReply()",d.Value,c,b);this.reloadModel()},reloadModel:function(){this.grid.Reload(null,null,!1);this.sendToBeSaved()},
deleteActionReply:function(b,d,c){e.debug("deleteActionActionReply()",d.Value,c,b)},unassignReply:function(b,d,c){e.debug("unassignReply()",d.Value,c,b);this.processReply(b)},assigntoReply:function(b,d,c){e.debug("assigntoReply()",d.Value,c,b);this.processReply(b)},processReply:function(b){if(b&&b.Changes&&b.Changes.length){var d=b.Changes;this.grid.AddDataFromServer(b);for(b=0;b<d.length;b++){var c=d[b],a=this.grid.GetRowById(c.id);null!=a&&(a._INTERNALSTATUS=c._INTERNALSTATUS,a.STATUS=c.STATUS,
a._OBJECTNAME=c._OBJECTNAME,"1"==c.MODRESOURCELOCK&&"1"==c.MODAPPOINTMENT?(a.mxLeftIconClass="skd-icon-appresourceloc",a._READONLY_STARTEND=!0,this.SetValue(a,"MODRESOURCELOCK",!0,!0),this.SetValue(a,"MODAPPOINTMENT",!0,!0)):"0"==c.MODRESOURCELOCK&&"1"==c.MODAPPOINTMENT?(a.mxLeftIconClass="skd-icon-appointment",a._READONLY_STARTEND=!0,this.SetValue(a,"MODRESOURCELOCK",!1,!0),this.SetValue(a,"MODAPPOINTMENT",!0,!0)):"1"==c.MODRESOURCELOCK&&"0"==c.MODAPPOINTMENT&&(a.mxLeftIconClass="skd-icon-resourceloc",
a._READONLY_ASSIGNMENT=!0,this.SetValue(a,"MODRESOURCELOCK",!0,!0),this.SetValue(a,"MODAPPOINTMENT",!1,!0)),delete a._GGanttClassOld,delete a.GGanttClass,delete a._SKDRunClassOld,delete a._SKDRunClass,this.grid.RefreshRow(a));a=c._OLDPARENTID;c=c.Parent;null!=a&&(a=this.grid.GetRowById(a),this.grid.RefreshRow(a));null!=c&&(c=this.grid.GetRowById(c),this.grid.RefreshRow(c))}this._focusGanttObject=null;this.grid.RefreshGantt(1);this.grid.ClearSelection();this.sendToBeSaved()}}})});
