define("dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang dojo/_base/array ibm/miniapp/scheduler/gantt/GanttWidget ibm/miniapp/scheduler/gantt/BaseResourceViewWidget ibm/miniapp/scheduler/gantt/ResourceViewActions".split(" "),function(n,u,f,g,r,v,w,x){var y=JSON.stringify([235,255,255]),z=JSON.stringify([224,244,244]);return n([v,u,w,x],{constructor:function(a){this.ViewName="Assignments";this.relatedAssignments=[];this.prevDescendants=
null;f.debug("{} Base Bean Target set to {} for view",this.gridId,this.mxtargetbean,a)},attachExtraGridEvents:function(a){this.inherited(arguments);AddEvent("OnGetDefaultColor",a,g.hitch(this,this.OnGetDefaultColor));AddEvent("OnGanttChanged",a,function(a,c,d,e,f,g,k,h,l){a.ColorRow(c)});window.Grids.ZoomToWork=g.hitch(this,this.ZoomToWork)},upgradeTGInstance:function(a){this.inherited(arguments);var b=this;a.ActionEnableLinkToWorkViewFilter=g.hitch(this,function(a){f.debug("Enabled Filter");this.fetch("async_update_filter_state",
{filter:!0}).then(g.hitch(b,b.processServerResponse))});a.ActionDisableLinkToWorkViewFilter=g.hitch(this,function(a){f.debug("Disable Filter");this.fetch("async_update_filter_state",{filter:!1}).then(g.hitch(b,b.processServerResponse))})},OnGetDefaultColor:function(a,b,c,d,e,f){if("Data"==b.Kind&&("LABOR"===b._REFOBJECTNAME||"AMCREW"===b._REFOBJECTNAME||"LOCATIONS"===b._REFOBJECTNAME)&&"G"!=c&&"Panel"!=c)return b.ERRVAL&&"name"==c?this._conflictRowColor:null},OnGanttRunDrop:function(a,b,c,d,e,f,g,
k,h,l,p,q,m,r){var n=this.inherited(arguments),t=this;1==d&&this.invokeLater(function(){t.relatedAssignments=[];t._applyRelatedAssignmentsHighlight(a,t.relatedAssignments)},100,"rundrop");return n},OnGanttRunBoxChanged:function(a,b,c,d){this.inherited(arguments)},OnValidateAssignmentDrop:function(a,b,c){},OnUndo:function(a,b,c,d,e){"Move"==b&&this.OnValidateAssignmentDrop(c.parentNode,c.parentNode,c)},OnGanttMenuClick:function(a,b,c,d,e,g){return e&&"ToggleTiledMode"==e.Name?(f.debug("ToggleTiledMode",
e),this.ToggleTiledMode()):this.inherited(arguments)},ToggleTiledMode:function(){var a=this,b=this.grid.Body;this.visitRow(b,[],function(a,d){a!==b&&a._UNASSIGNED&&(a.GGanttRunErrorsShift=0===a.GGanttRunErrorsShift?16:0,d.push(a));return!0});this.invokeLater(function(){a.grid.RefreshGantt(511)},50)},OnFocus:function(a,b,c,d,e,f){a=0;this.grid.Cols.G.GanttLines&&""!=this.grid.Cols.G.GanttLines&&(this.grid.Cols.G.GanttLines="",a=1);this.relatedAssignments&&this.relatedAssignments.length&&(this.relatedAssignments=
[],a=65);a&&this.Refresh(a);return!1},OnClick:function(a,b,c,d,e,f){this.inherited(arguments);if(f.ctrlKey||f.altKey||f.shiftKey)return!1;if("G"===c){var g=a.GetGanttXY(b,c,d,e);null!=g&&null!=g.Type&&g.RunId||this.OnFocus(a,b,c)}return!1},_focusGanttBarAdditionalActions:function(a){this.inherited(arguments);f.debug("Additional on focus bar actions");this._fetchAndShowScheduleWindow(a.id);this._highlightMultiSkillActivity(a.id);this._highlightRelatedAssignments(a.id)},_fetchAndShowScheduleWindow:function(a){var b=
this;this.invokeLater(function(){b.fetch("async_get_schedule_window",b._ioOptions({projectid:b.projectid,activityid:a})).then(function(a){b._applyScheduleWindow(b.grid,a)})},100,"async_get_schedule_window")},_highlightMultiSkillActivity:function(a){f.debug("_highlightMultiSkillActivity (): "+a);var b=this;this.invokeLater(function(){b.fetch("async_get_multi_skill_resourceset",b._ioOptions({projectid:b.projectid,activityid:a})).then(function(a){f.debug("_highlightMultiSkillActivity () end");b._applyMultiSkill(b.grid,
a)})},100,"async_get_multi_skill_resourceset")},_highlightRelatedAssignments:function(a){f.debug("highlight related assignments (): "+a);var b=this;this.invokeLater(function(){b.fetch("async_get_related_assignments",b._ioOptions({projectid:b.projectid,activityid:a})).then(function(a){f.debug("_highlightRelatedAssignments () end",a);b._applyRelatedAssignmentsHighlight(b.grid,a.related);b.isShowConstraintsOnSelectEnabled&&b._applyDescendantsFor(a)})},100,"async_get_related_assignments")},isShowConstraintsOnSelectEnabled:function(){return!0},
_applyDescendantsFor:function(a){f.debug("Descendants",a);delete a.descendants;delete a.resource;delete a.related;this.prevDescendants&&(r.forEach(this.prevDescendants,function(a){a.__clearDescendants&&a.__clearDescendants()}),this.prevDescendants=null,this.RefreshLater(255));var b=this;a.Changes&&(this.prevDescendants=[],r.forEach(a.Changes,function(a){var d=b.grid.GetRowById(a.id);d&&(d.__clearDescendants=function(){d._TG_DESENDANTS&&(d._TG_DESENDANTS="",d.__clearDescendants=null)},b.prevDescendants.push(d))}),
this.RefreshLater(255));this.grid.AddDataFromServer(a)},_applyRelatedAssignmentsHighlight:function(a,b){f.debug("Related Assignments",b);this.relatedAssignments=b;this.RefreshLater(65)},_GetAltCSSClassForActivity:function(a){if(this.relatedAssignments&&-1<this.relatedAssignments.indexOf(a.id)&&a!==this._focusGanttObject)return"skd-RELATED";if("undefined"!=a._INTERNALPLUSTQUALMET&&"ASSIGNED"==a._INTERNALSTATUS&&null!=a._INTERNALPLUSTQUALMET&&("NONE"==a._INTERNALPLUSTQUALMET||"PARTIAL"==a._INTERNALPLUSTQUALMET))return cls=
"skd-Conflict";if("ASSIGNED"===a._INTERNALSTATUS&&"ASSIGNREPLOC"===a._OBJECTNAME){if("undefined"!=a._INTPLUSARESERVATION&&null!=a._INTPLUSARESERVATION&&"HARD"===a._INTPLUSARESERVATION)return cls="skd-HardResType",f.debug("_GetAltCSSClassForActivity: {}",cls,a._INTPLUSARESERVATION,a.PRIMARYFLAG),cls;if("undefined"!=a.PRIMARYFLAG&&null!=a.PRIMARYFLAG&&(0===a.PRIMARYFLAG||"N"===a.PRIMARYFLAG||!1===a.PRIMARYFLAG))return cls="skd-SecondaryAssignment"}return"ASSIGNED"===a._INTERNALSTATUS&&1==a._READONLY?
cls="skd-FilteredAssignment":this.inherited(arguments)},_AdditionalTableContextMenu:function(a,b,c,d,e,f,g){var k=this.inherited(arguments);if("ASSIGNED"===c._INTERNALSTATUS&&1==c._READONLY||"OTHERASSIGNMENT"===c._OBJECTNAME&&1==c._READONLY){var h=k.Items.filter(function(a,b,c){return null!=a.Name&&a.Name.startsWith("Go To")});k.Items=h}return k},OnRenderFinish:function(a){this.inherited(arguments);this.relatedAssignments=[]},_autoRefreshData:function(a){this.fetch("async_auto_refresh_model",a._ioOptions({projectid:a.projectid})).then(function(b){if(b&&
b.Changes&&b.Changes.length){for(var c=b.Changes,d=[],e=0;e<c.length;e++)d.push(c[e].id);a.grid.AddDataFromServer(b);for(b=0;b<d.length;b++)e=a.grid.GetRowById(d[b]),e.name=c[b].name,e._idx=c[b]._idx,e.mxRightIconClass=c[b].mxRightIconClass,e.mxLeftIconClass=c[b].mxLeftIconClass,e._OBJECTNAME=c[b]._OBJECTNAME,e._REFOBJECTNAME=c[b]._REFOBJECTNAME,e._INTERNALSTATUS=c[b]._INTERNALSTATUS,e.STATUS=c[b].STATUS;a.grid.RefreshGantt(1)}window.clearTimeout(window.timeoutId);window.timeoutId=setTimeout(function(){a._autoRefreshData(a)},
a.dispatchRefreshInterval)})},OnLoadCfg:function(){return!1},_NotifyRowSelected:function(){return!1},_onSyncResponse:function(){return!1},_updateSync:function(){return!1},requestSync:function(){return!1},focusGanttBarLater:function(){if(this.Dragging)return!1;this.inherited(arguments)},_exportAssignmentsAction:function(a,b){f.debug("Selected row: {}",b);var c=a.Values.selection,c=JSON.parse(c).join(),d=this.GetSelection(this.grid,"G",b).resources,e=[];for(i=0;i<d.length;i++)"CRAFT"==d[i]._OBJECTNAME?
e.push("LABOR"):e.push("AMCREW");0==e.length&&e.push(b._OBJECTNAME);addCommInput("selection",c);addCommInput("objectnames",e.join());addCommInput("actionname","export_calendar");addCommInput("dialogname","export_calendar");addCommInput("skdobjectname",b._OBJECTNAME);addCommInput("objectname",b._OBJECTNAME);addCommInput("eventtargetid","assignments_miniapp");addCommInput("projectid",this.projectid);f.debug("sendEvent({},{})","export_calendar",this.appname);sendEvent("export_calendar",this.appname,
"")},OnGetColor:function(a,b,c,d,e,f){if(!a.Cols[c]||!a.Cols[c].Visible)return null;a=null;d=JSON.stringify([d,e,f]);if(y==d||z==d)a="white";!this._firstRender&&"name"==c&&b._REFOBJECTNAME&&"CRAFT"!=b._REFOBJECTNAME&&!a&&b&&b.GGanttBackground&&(c=b.GGanttBackground,c=c.split("White").join("WORKAlternate"),b.GGanttBackground=c);return a},OnTip:function(a,b,c,d,e,f,n,k){d=this.inherited(arguments);if(!d&&b.MODAVAIL)for(var h=this.getDateForX(n,c),l=JSON.parse(b.MODAVAIL),p=0;p<l.length;p++){var q=l[p];
if(q.startDate<=h&&q.finishDate>=h){var m;null!=this["gantt.MODAVAIL.tip.tpl"]&&(m=this["gantt.MODAVAIL.tip.tpl"],null==m||0==m.trim().length)&&(m="{reasonCode} / {start}-{finish}");h=Object.assign({},q);null!=h.duration&&(l=this.doubleToDuration(h.duration,!1),h.duration=l);d=g.replace(m,g.hitch({row:h},this.__rowValFunc));if(null==d||0==d.trim().length)d=h.reasonCode+(" / "+start+"-"+finish);break}}return d}})});
