define("dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang ibm/miniapp/scheduler/gantt/WorkView com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(m,n,h,f,p,q){return m([p,n,q],{constructor:function(a){this.ViewName="Scheduler";this.locked=!1;this.selectedPMRow=null;this.PDFSource="ExportPDF.html";this.Dataxml=this.Layoutxml=null;this.allSegments={};this.previousPMRowState=this.modifiedPMRowId=null;this.rightClickMove=this.Undoing=
!1},upgradeTGInstance:function(a){this.inherited(arguments);this.grid._enableFilterCPM=f.hitch(this,this._enableFilterCPM);this.grid._disableFilterCPM=f.hitch(this,this._disableFilterCPM);this.grid._runCPM=f.hitch(this,this._runCPM);this.grid._runCPMSelected=f.hitch(this,this._runCPMSelected);this.grid._createLinksCPM=f.hitch(this,this._createLinksCPM);this.grid._printToPDF=f.hitch(this,this._printToPDF);this.grid._runUpdateSummary=f.hitch(this,this._runUpdateSummary)},attachExtraGridEvents:function(a){this.inherited(arguments);
TGSetEvent("OnSelectGanttRunRect",a,f.hitch(this,this.OnSelectGanttObjects));TGSetEvent("OnFocus",a,f.hitch(this,this.OnFocus));TGSetEvent("OnExport",a,f.hitch(this,this.OnExport));TGSetEvent("OnUpload",a,f.hitch(this,this.OnUpload));h.debug("{} Registering extra grid events",this.TAG);this.subscribeOn("skd.request.workview.reference",f.hitch(this,this.publishResponseWorkViewReference))},publishResponseWorkViewReference:function(a){this.publishTo("skd.response.workview.reference",{grid:this.grid,
view:this})},_removeOldGrid:function(){this.publishTo("skd.workview.destroyed");this.inherited(arguments)},onRefreshRequested:function(a){a&&a.sourceId&&-1!=a.sourceId.indexOf("_SAVE")||a&&a.type&&"toBeSaved"==a.type?h.warn("Refresh Ignored because of Toolbar Save",a):this.inherited(arguments)},OnAfterSave:function(a,b,e){if(0<=b&&!this.locked){this.inherited(arguments);var c=!1;if(null!=this.allSegments){for(var d in this.allSegments){var g=new Date(this.allSegments[d]);g.setHours(0,0,0,0);var f=
a.GetRowById(d),f=new Date(f.startTime);f.setHours(0,0,0,0);if(g.getTime()!=f.getTime()){c=!0;break}}c||this.rightClickMove||null==this.modifiedPMRowId||(c=a.GetRowById(this.modifiedPMRowId),c.Color=null,c._UNCOMMITTED=0,a.RefreshRow(c),this.modifiedPMRowId=null)}this.rightClickMove=!1}},OnExport:function(a,b,e){if(1==e){e=this.servletBase+"/utility/tg/ExportPdf.jsp";var c=this.servletBase.replace("/webclient",""),d=this.Layoutxml,g=this.Dataxml;this.pdfExportBaseUrl&&(d=d.replace(c,this.pdfExportBaseUrl),
g=g.replace(this.servletBase,this.pdfExportBaseUrl));d=encodeURIComponent(d);g=encodeURIComponent(g);b=encodeURI(b);var c=encodeURI(this.projectName),f=Math.round(25.4*a.PrintPageWidth/a.PrintDPI+a.PrintMarginWidth),h=Math.round(25.4*a.PrintPageHeight/a.PrintDPI+a.PrintMarginHeight);b="PDFName="+a.PDFName+"&PDFFormat="+a.PDFFormat+"&Data="+b+"&PDFPageOrientation="+a.PrintPageOrientation;b=b+"&PrintMarginWidth="+a.PrintMarginWidth+"&PrintMarginHeight="+a.PrintMarginHeight+"&PrintDPI="+a.PrintDPI;b=
b+"&PDFPageSize="+a.PrintPageSize+"&Layoutxml="+d+"&Dataxml="+g+"&Source="+this.PDFSource;b=b+"&ProjectName="+c+"&PrintPageWidth="+f+"&PrintPageHeight="+h+"&PDFFitPage="+a.PDFFitPage;d=new XMLHttpRequest;d.open("POST",e,!0);d.setRequestHeader("Content-type","application/x-www-form-urlencoded");d.send(b);this.ShowProgress(a,90,30,500);return!0}return!1},OnUpload:function(a,b,e,c){-1<b.indexOf("PM_")&&0==this.previousPMRowState&&this.Undoing&&(a=JSON.parse(b),a.Changes[0].Undoing=!0,this.Undoing=!1,
b=JSON.stringify(a));return b},_enableFilterCPM:function(){h.debug("{} Enable Filter CPM",this.TAG);this._CPMFilterEnabled=!0;this._FilterCPM()},_disableFilterCPM:function(){h.debug("{} Disable Filter CPM",this.TAG);this._CPMFilterEnabled=!1;this._FilterCPM()},_FilterCPM:function(){h.debug("{} Filter CPM",this.TAG);var a=this;this.fetch("_cpmfilter",a._ioOptions({filteredByCriticalPath:a._CPMFilterEnabled})).then(function(b){a.grid.AddDataFromServer(b);a.grid.RefreshGantt(1)})},_GetSelectedRows:function(a,
b,e){var c=[];if(b==this.GANTTCOL)if(b=a.GetGanttRunSelectedBoxes(null,b),0<b.length)for(a=0;a<b.length;a++){var d=b[a].Id;d&&(d=this.GetRowById(d),null!=d&&c.push(d))}else c=a.GetSelRows();else if(c=a.GetSelRows(),2===c.length&&(b=a.GetGanttRunSelectedBoxes(null,this.GANTTCOL),0<b.length))for(a=0;a<b.length;a++)if(d=b[a].Id)d=this.GetRowById(d),null!=d&&c.push(d);b=!0;for(a=0;a<c.length;a++)if(null!=e&&c[a].id==e.id){b=!1;break}null!=e&&b&&c.push(e);return c},_GetSelectedRowIds:function(a,b,e){a=
this._GetSelectedRows(a,b,e);e=b="";for(var c in a)b=b+e+a[c].id,e=",";return b},_runCPM:function(){h.debug("{} Run CPM",this.TAG);this.__pleaseWait();var a=this;this.fetch("_cpmall",a._ioOptions({})).then(function(b){a.grid.AddDataFromServer(b);0<b.IO.Result?(a._firstRender=!1,a.grid.ReloadBody(function(){a.invokeLater(function(){a.grid.RefreshGantt(1)},100,"cpmGanttRefresh")}),a.publishLater("skd.workview.updated",{grid:a.grid,result:b.Result}),a.MarkToBeSaved()):(a.HideTGMessage(),a.grid.ShowMessageTime(b.IO.HtmlMessage,
0))})},_runCPMSelected:function(){h.debug("{} Run CPM Selected",this.TAG);this.__pleaseWait();var a=this._GetSelectedRowIds(this.grid,null,null),b=this;this.fetch("_cpmselected",b._ioOptions({ids:a})).then(function(a){b.HideTGMessage();b.grid.AddDataFromServer(a);b.publishLater("skd.workview.updated",{grid:b.grid,result:a.Result});b.grid.ClearSelection();b.MarkToBeSaved();a=a.Changes;for(var c=0;c<a.length;c++){var d=b.grid.GetRowById(a[c].id);d&&(d._UNCOMMITTED=a[c]._UNCOMMITTED,b.grid.RefreshRow(d))}})},
_createLinksCPM:function(){h.debug("{} Create Links CPM",this.TAG);this.__pleaseWait();var a=this._GetSelectedRowIds(this.grid,null,null),b=this;this.fetch("_cpmcreatelinks",b._ioOptions({ids:a})).then(function(a){0<=a.IO.Result?(b.HideTGMessage(),b.grid.AddDataFromServer(a),b.publishLater("skd.workview.updated",{grid:b.grid,result:a.Result}),b.MarkToBeSaved()):(b.HideTGMessage(),b.grid.ShowMessageTime(a.IO.HtmlMessage,0))})},_printToPDF:function(){this.grid.ActionExportPDF()},ShowProgress:function(a,
b,e,c){var d=this;setTimeout(function(){a.ShowProgress("Export PDF","Preparing Print job...",null,e,b);e>=b?a.ShowMessageTime("Print job submitted.",2E3):(e+=30,d.ShowProgress(a,b,e,c))},c)},_runUpdateSummary:function(){h.debug("{} Run Update Summary",this.TAG);this.__pleaseWait();var a=this;this.fetch("_updateSummary",a._ioOptions({})).then(function(b){0<b.IO.Result&&(a.HideTGMessage(),a.grid.AddDataFromServer(b),a.publishLater("skd.workview.updated",{grid:a.grid,result:b.Result}),a.MarkToBeSaved())})},
OnActivityChanged:function(a,b,e,c,d,g,f){h.debug("{} OnActivityChanged",this.TAG);var l=this;if("Resize"==f||"Move"==f)if(e=!1,g=this.GetRootActivity(a),null!=g){c=g.EARLYSTART;g=g.LATEFINISH;if(null!=b.CRITICAL&&b.CRITICAL||null!=c&&d.StartDate<c||null!=g&&d.EndDate>g)e=!0;e?this.showCriticalPathImpactWarning&&(l.locked=!0,this.ask("scheduler#criticalPathActivityMoved").then(function(b){h.debug("Response: {}",b);l.locked=!1;8==b?(l.publishLater("skd.workview.updated",{grid:a,result:b}),l.MarkToBeSaved()):
a.ActionUndo()})):this.sendToBeSaved()}},focusGanttBar:function(a){a&&null!=a._OBJECTNAME&&"PM"==a._OBJECTNAME&&null!=this.selectedPMRow?this.selectedPMRow=null:this.inherited(arguments)},OnUndo:function(a,b,e,c,d){"Change"==b&&"startTime"==c&&(b=e.parentNode)&&0==this.previousPMRowState&&(b._UNCOMMITTED=0,a.RefreshCell(b,"name"),this.Undoing=!0)},OnDragGanttRun:function(a,b,e,c,d,f,h,l,k,m,n,p,q){var u=this.inherited(arguments);if(b&&null!=b._OBJECTNAME&&"PM"==b._OBJECTNAME)for(this.allSegments=
{},i=1;i<=b["_PMFORECAST-SEGMENTCOUNT"];i++){var r=b._idx+"__"+i,t=a.GetRowById(r);null!=t&&(this.allSegments[r]=t.startTime)}return u},OnGanttChanged:function(a,b,e,c,d,f,h,l,k){null==b._OBJECTNAME||"PM"!=b._OBJECTNAME||"Slide"!=k&&"Move"!=k||(b._seq&&b.parentNode&&(b=b.parentNode),this.selectedPMRow=b,this.modifiedPMRowId=b.id,this.previousPMRowState=b._UNCOMMITTED,b.Color=this._pmreforecastpendingBG,a.RefreshRow(b));e=!1;"Dependency"!=c||"New"!=k&&"Delete"!=k||(f[1]&&(c=a.GetRowById(f[1]),this.SetValue(c,
"_UNCOMMITTED",1,!0),this.OnRowChanged(a,c)),e=!0);e&&this.SetValue(b,"_UNCOMMITTED",1,!0);this.state&&this.state.Filter&&this.state.Filter.Visible&&"Slide"!=k&&"Move"!=k&&"Correct"!=k&&(k=a.GetFilter(),Array.isArray(k)&&k.length&&0<k.length&&this.grid.DoFilter());this.OnRowChanged(a,b)},GetRootActivity:function(a){return a.Body.firstChild},MarkToBeSaved:function(){this.sendToBeSaved()}})});
