define("dojo/_base/declare dojo/aspect com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang ibm/miniapp/scheduler/gantt/GanttWidget ibm/miniapp/scheduler/gantt/BaseResourceViewWidget com/ibm/tivoli/maximo/miniapps/Handlers ibm/miniapp/scheduler/gantt/CommonResourceHoursView dojo/json dijit/popup".split(" "),function(r,t,u,l,k,v,w,x,y,z,p){var A=JSON.stringify([235,255,255]),B=JSON.stringify([224,244,244]);return r([v,u,w,x,y],{constructor:function(b){l.debug("{} Base Bean Target set to {} for view",
this.gridId,this.mxtargetbean,b);this.showCurrentDateLine=!1;this.aspectShowHideElHandle=null;this.selectedModAvailReasonCode="";this.selectedModAvailDurationType="FULLDAY";this.weekStart=1},_newTreeGridOptions:function(){return{Data:{Url:this.toUrl("async_load_project_data",this._ioOptions({ganttStart:-1})),Timeout:300},Layout:{Url:this.toUrl("async_load_project_ui",this._ioOptions({appname:this.appname,projectid:this.projectid}))}}},upgradeTGInstance:function(b){this.inherited(arguments);this.grid._onChangeModAvailRsnCode=
k.hitch(this,this._onChangeModAvailRsnCode);this.grid._onChangeModAvailDurationType=k.hitch(this,this._onChangeModAvailDurationType);this.grid._showLegendDialogAction=k.hitch(this,this._showLegendDialogAction);this.grid._previous=k.hitch(this,this._previous);this.grid._next=k.hitch(this,this._next);this.grid.ActionZoomOut=k.hitch(this,this.ZoomOut)},hideGanttZoomOptions:function(){return!0},ZoomOut:function(){var b=this,a=new Date(this.weekStart),c=new Date(this.weekStart+6048E5),d=new Date((a.getTime()+
c.getTime())/2);d.getMonth()==a.getMonth()&&d.getMonth()==c.getMonth()||!this.lastGanttZoom?this.grid.ChangeZoom("month"):(a=new Date(d.getFullYear(),d.getMonth(),1),this.__pleaseWait(),this.fetch("_gotoPeriod",b._ioOptions({direction:-1,zoomLevel:1,weekStart:a.getTime()})).then(function(a){var c=a.startGanttDate,d=a.endGanttDate,e=a&&a.Changes;b.weekStart=c;b.grid.ZoomTo(c,d);if(e){b.acceptChangesFromServer(a);a=a.Changes;for(c=0;c<a.length;c++)d=a[c],e=b.grid.GetRowById(d.id),null!=e&&(e=b.updateCraftRow(e,
d),b.grid.RefreshRow(e));b.grid.RefreshGantt(1);b.sendToBeSaved()}}))},OnDataSend:function(b,a,c,d){"Data"==a.Name&&a.Url.includes("ganttStart")&&this.state&&this.state.GanttStart&&(b=encodeURIComponent('"ganttStart":'+this.state.GanttStart+","),a.Url=a.Url.replace(/%22ganttStart%22%3A.*%2C/,b));if(a&&"Changes"===a.Type&&c&&-1!==c.indexOf('"Changes":[]'))return l.debug("Prevent Empty Changes",c),!0},OnTableContextMenu:function(b,a,c,d,g,h){l.debug("OnTableMenuContextMenu: {}",c,b.Cols[c]);var f=this;
if(!b.Cols[c])return!1;value="G"==c?a.id:a[c];a=this.GetRow(b,a,c,d,g);var e=b.GetGanttXY(a,c,d,g),q=this.GetSelectionIds(b,c,a),m=this._GetSelectedRowIds(b,c,a),k=a.START,e="LABOR"==a._OBJECTNAME||"AMCREW"==a._OBJECTNAME;"G"===c&&this.enableModAvail&&e&&(e=b.GetGanttXY(a,c,d,g),null!=e&&null!=e.Type&&e.RunId&&(k=this.GetRowById(e.RunId),m=this._GetSelectedObjectIds(b,null,null),""==m&&(m=a._OBJECTID),l.debug("Selected Row: {}",k),k=k.START));l.debug("OnTableMenuContextMenu: Context Menu: Selection: {}",
m,q);if(void 0==value)return!0;this.fetch("async_get_table_context_menu",f._ioOptions({projectid:f.projectid,id:m,selection:q,col:c,value:value,selecteddate:k})).then(function(e){e=f._AdditionalTableContextMenu(e,b,a,c,d,g,h);f._ShowContextMenu(e,b,a,c,d,g,h,q)});return!0},OnShowTooltip:function(b,a,c,d,g,h){var f=this;if("Panel"!=c&&("name"!=c||h&&h.srcElement&&h.srcElement.id&&-1!=h.srcElement.id.indexOf("TGCell_"))&&"startTime"!=c&&"endTime"!=c&&"Data"===a.Kind){if("G"==c){var e=b.GetGanttXY(a,
c,d,g);l.debug("Gantt Object",e);if(null!=e&&null!=e.Point)return this.fetch("async_get_tooltip_for_point",f._ioOptions({projectid:f.projectid,id:e.Row.id,point_index:e.PointIndex})).then(function(a){f._showTooltip(a,h,e.Row)}),!1;if(null==e||null==e.Main)if(null!=e&&null!=e.RunId)a=this.GetRowById(e.RunId),l.debug("Using RUN BAR for ToolTip",e,e.RunId,a);else return null!=e&&"dependency"==e.Type?(l.debug("Using Dependency for ToolTip",e),"0"===e.DependencyFromBox?this._fetchDependencyTooltip(e.DependencyFrom,
e.DependencyTo,h):this._fetchDependencyTooltip(e.DependencyFromBox,e.DependencyToBox,h)):(b=this.getDateForX(d),l.debug("Gantt Click at {} is date {} ({})",d,b,(new Date(b)).toUTCString()),this.fetch("async_get_tooltip_for_date",f._ioOptions({projectid:f.projectid,id:a.id,col:c,date:b})).then(function(b){f._showTooltip(b,h,a)})),!1}b=this.getDateForX(d);d=a.id;if("LABOR"==a._OBJECTNAME||"AMCREW"==a._OBJECTNAME)d=a._PARENTID;this.fetch("async_get_tooltip",f._ioOptions({projectid:f.projectid,id:d,col:c,
date:b})).then(function(b){f._showTooltip(b,h,a)})}},_onChangeModAvailRsnCode:function(b){this.selectedModAvailReasonCode=b},_onChangeModAvailDurationType:function(b){this.selectedModAvailDurationType=b},_onSaveModAvailRsnCode:function(b,a,c){var d=this;this.__pleaseWait();this.fetch("async_save_modavail_rsncode",d._ioOptions({projectid:d.projectid,selection:b,objectName:a,date:c,reasonCode:this.selectedModAvailReasonCode,durationType:this.selectedModAvailDurationType})).then(function(){d.grid.ReloadBody()})},
_onDeleteModAvailRsnCode:function(b,a,c){var d=this;this.__pleaseWait();this.fetch("async_delete_modavail_rsncode",d._ioOptions({projectid:d.projectid,selection:b,objectName:a,date:c,durationType:this.selectedModAvailDurationType})).then(function(a){1E3<=a.IO.Result?d.grid.ReloadBody():(d.HideTGMessage(),d.grid.ShowMessageTime("There is no modified availability to be removed.",0))})},_GetSelectedObjectIds:function(b,a,c){b=this._GetSelectedRows(b,a,c);c=a="";for(var d in b)a=a+c+b[d]._OBJECTID,c=
",";return a},_viewAssignmentsAction:function(b,a){l.debug("Selected row: {}",a);addCommInput("selectedAssignments",a.EXTERNALASSIGNMENTS);addCommInput("uniqueid",a.parentNode._OBJECTID);addCommInput("actionname","view_assign");addCommInput("dialogname","view_assign");addCommInput("skdobjectname",a._OBJECTNAME);addCommInput("objectname",a._OBJECTNAME);addCommInput("eventtargetid","viewerng_resourcetabs_rshb_gantt");addCommInput("projectid",this.projectid);l.debug("sendEvent({},{})","view_assign",
this.appname);sendEvent("view_assign",this.appname,"")},_modavailAction:function(b,a){var c=b.Values,d=c.selection,c=c.selecteddate;""==d&&(d=a._OBJECTID);this._modavailrsncode(d,c,a)},_modavailrsncode:function(b,a,c){var d="LABOR"==c._OBJECTNAME||"AMCREW"==c._OBJECTNAME;if(this.enableModAvail&&d){l.debug("Selected Row: {}",c);var g=new Date(this.TGDateToTZDate(a)),d=g.getDay()+1,h=this.getWeekOfMonth(g),g=0;c.parentNode&&(g=c.parentNode["WEEK"+h+"_WORKHOURSDAY"+d]);d="WORK"==this.reasonCodes[this.selectedModAvailReasonCode];
""!=this.selectedModAvailReasonCode&&"REMOVE"!=this.selectedModAvailReasonCode?"PARTIALDAY"!=this.selectedModAvailDurationType&&0<g?(g=this.GetModAvailList(c),d||g&&1<=g.length?this.openModAvailDialog(b,a,c):this._onSaveModAvailRsnCode(b,c._OBJECTNAME,a)):"FULLWEEK"==this.selectedModAvailDurationType?(g=this.GetModAvailWeekList(c),d||0!=g.length?this.openModAvailDialog(b,a,c):this._onSaveModAvailRsnCode(b,c._OBJECTNAME,a)):this.openModAvailDialog(b,a,c):"REMOVE"==this.selectedModAvailReasonCode?this._onDeleteModAvailRsnCode(b,
c._OBJECTNAME,a):(this.HideTGMessage(),this.grid.ShowMessageTime("There is no reason code specified.",0))}},getWeekOfMonth:function(b){var a=b.getDate(),a=a-(0==b.getDay()?6:b.getDay()-1);prefixes="012345".split("");return prefixes[0|(a+7)/7]},shouldRightClickSelectRow:function(b,a,c){return!1},shouldDblClickSelectRow:function(b,a,c){return!0},OnDblClick:function(b,a,c,d,g,h){this.inherited(arguments);var f="LABOR"==a._OBJECTNAME||"AMCREW"==a._OBJECTNAME,e=b.GetGanttXY(a,c,d,g);if("G"===c&&f&&f&&
this.enableModAvail){f=this._GetSelectedObjectIds(b,c,a);""==f&&(f=a._OBJECTID);var k=a.START;if(null!=e&&null!=e.Type&&e.RunId){var m=this.GetRowById(e.RunId);l.debug("Selected Row: {}",m);k=m.START}this._modavailrsncode(f,k,m)}},openModAvailDialog:function(b,a,c){addCommInput("selection",b);addCommInput("workdate",a);addCommInput("actionname","MODIFYMODAVAIL");addCommInput("dialogname","MODIFYMODAVAIL");addCommInput("linkedapp","MODIFYMODAVAIL");addCommInput("skdobjectname",c._OBJECTNAME);addCommInput("objectname",
c._OBJECTNAME);addCommInput("eventtargetid","viewerng_resourcetabs_rshb_gantt");addCommInput("projectid",this.projectid);addCommInput("reasoncode",this.selectedModAvailReasonCode);addCommInput("durationtype",this.selectedModAvailDurationType);l.debug("sendEvent({},{})","MODIFYMODAVAIL",this.appname);sendEvent("MODIFYMODAVAIL",this.appname,"")},attachExtraGridEvents:function(b){this.inherited(arguments);l.debug("{} Registering extra grid events",this.TAG);AddEvent("OnGetGanttHeader",this.gridId,k.hitch(this,
this.OnGetGanttHeader));this.subscribeOn("skd.refreshResource",k.hitch(this,this._refreshResource));this.subscribeOn("skd.cancelModAvailDialog",k.hitch(this,this._cancelModAvailDialog))},OnGetGanttHeader:function(b,a,c,d,g,h,f,e,k){1==c&&1==e&&(a="... "+DateToString(d,"MMM yyyy"));b=DateToString(d,"MMM yyyy");g=DateToString(g,"MMM yyyy");1==c&&"week"==this.grid.Cols.G.GanttZoom&&b!=g&&(a=b+" - "+g);return a},OnSaveCustomCfg:function(b,a){this.state||(this.state={});b&&b.Filter&&(this.state.Filter||
(this.state.Filter={}),this.state.Filter.Visible=b.Filter.Visible);var c=b.GetScrollLeft(2),c=b.GetGanttDate(c,"G");isNaN(c)||(this.state.GanttStart=c);c=z.stringify(this.state);l.debug("Custom State",c);return c},OnRenderFinish:function(b){this.inherited(arguments);var a=b.GetScrollLeft(2);this.weekStart=b.GetGanttDate(a,"G");this._setStartDate(this.weekStart)},postCreate:function(){this.inherited(arguments);var b=this;this.aspectShowHideElHandle=t.after(window,"hideShowElement",function(a,c){a&&
a.querySelector&&a.querySelector("#"+b.domId)&&l.debug("ShowHideEl: called with {}",c)},!0)},destroy:function(){this.inherited(arguments);this.aspectShowHideElHandle&&(this.aspectShowHideElHandle.remove(),this.aspectShowHideElHandle=null)},OnGetGanttBarHtml:function(b,a,c,d,g,h,f,e,l,m,p,n,r){b="{name}";c="gantt."+a._OBJECTNAME+".tpl";null!=this[c]&&(b=this[c],null==b||0==b.trim().length)&&(b="{name}");b=k.replace(b,k.hitch({row:a},this.__rowValFunc));if(null==b||0==b.trim().length)b=a.name;if(!a.IsSummary){g=
d="";d=null!=a._INTERNALSTATUS?"SKD"+a._OBJECTNAME+"_"+a._INTERNALSTATUS:"SKD"+a._OBJECTNAME;this.usePriorityColors&&a.WOPRIORITY&&(d="SKD"+a._OBJECTNAME+"_PRIORITY_"+a.WOPRIORITY);c=d+"-inner";a.STATUS&&(h="SKDSYN_"+a._OBJECTNAME+"_"+a.STATUS.toString().replace(/\s+/g,"-"),d+=" "+h,c+=" "+h+"-inner");a.ERRVAL&&(d="",0!=(a.ERRVAL&this.ERRORS.ERR_INVALID_CRAFT_SKILL)&&(d="skd-InvalidSkillMap"),0==(a.ERRVAL&this.ERRORS.ERR_CONFLICT_DOUBLE_BOOKED)&&0==(a.ERRVAL&this.ERRORS.ERR_CONFLICT_NON_WORK)||"ASSIGNED"!=
a._INTERNALSTATUS||(d+=" skd-Conflict"),0!=(a.ERRVAL&this.ERRORS.ERR_SCHEDULE_WINDOW)&&(d+=" skd-err-schedule-window"),""==d&&(d+=" skd-error"));a._ALTCLASS&&(g=a._ALTCLASS);f=1==a._READONLY?" skd-READONLY":"";e=1==a._READONLY_DURATION?" skd-READONLY_DURATION":"";l=1==a._READONLY_ASSIGNMENT?" skd-READONLY_ASSIGNMENT":"";m=1==a._READONLY_STARTEND?" skd-READONLY_STARTEND":"";h=this._GetAltCSSClassForActivity(a)||"";d="skd-bar "+d+" "+g+" "+h+" "+m+e+l+f;c="skd-bar-inner "+c+" "+(h?h+"-inner ":"");g=
null;if(this.GetBarStyle&&(g=this.GetBarStyle(a)))return b="st-"+a.id,h=document.createElement("style"),h.type="text/css",h.innerHTML="."+b+" { "+g+" }",d+=" "+b,n||(n=[]),n[2]=d,n[3]=c,b=a.TEXT,'<div class="'+d+'" style="'+g+'" >'+(b?b:"")+"</div>";n||(n=[]);n[2]=d;n[3]=c;null!=b&&(b=b.replace(/\|/g,"&vert;"),b=b.replace(/\'/g,"&apos;"))}return b},GetModAvailList:function(b){var a=b.DAYINDEX%7;0==a&&(a=7);var c=b.WEEK,d;b.parentNode&&(d=b.parentNode["WEEK"+c+"_MODAVAILINFO"+a])&&(d=JSON.parse(d));
return d},GetModAvailWeekList:function(b){var a=b.WEEK,c=[];if(b.parentNode)for(var d=1;7>=d;d++)if(modAvailList=b.parentNode["WEEK"+a+"_MODAVAILINFO"+d])modAvailList=JSON.parse(modAvailList),c.push(modAvailList);return c},GetBarStyle:function(b){if(b.MODAVAILCOLOR){var a="",c=b.MODAVAILCOLOR,d=this.GetModAvailList(b);if(d){var g=d&&1<d.length;if(g)for(var c="#B03060",h=0;h<d.length;h++)d[h].fullDay&&(b.FULLDAY=1,d[h].color&&(b.MODAVAILCOLOR=d[h].color),d[h].fontColor&&(b.MODAVAILFONTCOLOR=d[h].fontColor))}b.FULLDAY&&
(a+="background-color: "+b.MODAVAILCOLOR+"!important;",a+="color: "+b.MODAVAILFONTCOLOR+"!important;",a+="margin: 0px -15px;");if(!b.FULLDAY||g)a=a+("background: linear-gradient(to top right,transparent 50%,"+c+" 0) top right/25px 25px no-repeat,transparent;")+"border-radius: 12px;",a+="margin: 0px -13px;";return a}},_cancelModAvailDialog:function(){this.grid.ClearSelection()},_refreshResource:function(b){this.__pleaseWait(this.label("loading_resources"));this.grid.ReloadBody();this.grid.ClearSelection()},
_showLegendDialogAction:function(){var b=this,a=this.label("reasonCode");this.label("allocation");var c=this.label("closeButton");this.label("work");this.label("nonWork");this.allocationThresholds.split(",");this.allocationColors.split(",");var d="<table style='border-spacing: 5px;'>",d=d+("<tr><td colspan='3' style='text-align:center;'><b>"+a+"</b></td></tr>"),d=d+"<tr><td colspan='3'>&nbsp;</td></tr>";Object.keys(this.reasonCodeColors).forEach(function(a){d+="<tr><td>"+a+":<td><td style='width: 35%; border: 1px solid black; background-color: "+
b.reasonCodeColors[a]+";'>&nbsp;</td></tr>"});d+="<tr><td colspan='3'>&nbsp;</td></tr>";d+="<tr><td colspan='3' style='text-align:center;'><input type='button' value='"+c+"' onclick='Grids.forEach(g=>g ? g.CloseDialog() : null);' /></td></tr>";this.grid.CloseDialog();var g=window.outerHeight/4,h=window.innerWidth/2,b=this;this.invokeLater(function(){b.grid.Dialog=ShowDialog(d,{X:h,Y:g})},100,"ShowLegend")},_previous:function(){this._gotoPeriod(0,this.weekStart)},_next:function(){this._gotoPeriod(1,
this.weekStart)},_gotoPeriod:function(b,a){var c=this,d=null,d="month"==this.grid.Cols.G.GanttZoom?1:2;this.__pleaseWait();this.fetch("_gotoPeriod",c._ioOptions({direction:b,zoomLevel:d,weekStart:a})).then(function(a){var d=a.startGanttDate,f=a.endGanttDate,e=a&&a.Changes;c.weekStart=d;-1<b?c.grid.ZoomTo(d,f):(d=c.weekStart,e||(d+=864E5),c.grid.ScrollToDate(d,"Left"));c.state.GanttStart=c.weekStart;if(e){c.acceptChangesFromServer(a);a=a.Changes;for(e=0;e<a.length;e++)d=a[e],f=c.grid.GetRowById(d.id),
null!=f&&(f=c.updateCraftRow(f,d),c.grid.RefreshRow(f));c.grid.RefreshGantt(1)}c.HideTGMessage()})},updateCraftRow:function(b,a){b.MODAVAILCOLOR=a.MODAVAILCOLOR;b.MODAVAILFONTCOLOR=a.MODAVAILFONTCOLOR;b._INTERNALSTATUS=a._INTERNALSTATUS;b.STATUS=a.STATUS;b.FULLDAY=a.FULLDAY;b._OBJECTNAME=a._OBJECTNAME;b.TEXT=a.TEXT;a.Added&&1==a.Added&&delete b.name;for(var c=Object.keys(a).filter(function(a){return a.includes("MODAVAILINFO")}),d=0;d<c.length;d++)b[c[d]]=a[c[d]];return b},_setStartDate:function(b){var a=
this;this.fetch("_setStartDate",a._ioOptions({currentDate:b})).then(function(b){a.weekStart=b.startWeekDay})},OnZoom:function(b,a,c,d){try{if(b&&b.Toolbar&&(!this.lastGanttZoom||this.lastGanttZoom!=a)){var g=this;this.lastGanttZoom=a;b.Toolbar.ZoomInDisabled=0;b.Toolbar.ZoomOutDisabled=0;if("week"==a){b.Toolbar.ZoomInDisabled=1;var h=new Date(c),f=new Date(h.getFullYear(),h.getMonth(),1),e=f.getDate()-f.getDay(),k=new Date(f.setDate(e));this.weekStart=this.TZDateToTGDate(k);this.invokeLater(function(){b.ScrollToDate(g.weekStart,
"Left")},10,"ScrollToDate")}else"month"==a&&(b.Toolbar.ZoomOutDisabled=1);b.RefreshRow(b.Toolbar)}}catch(m){l.error("OnZoom Hook Failed",m)}},OnGetColor:function(b,a,c,d,g,h){var f=null;d=JSON.stringify([d,g,h]);if(A==d||B==d)f="white";this._firstRender||(!this.ganttBackground&&b.Cols.G.GanttBackground&&(this.ganttBackground=b.Cols.G.GanttBackground.split("White").join("WORKAlternate")),"name"==c&&!f&&a&&this.ganttBackground&&(a.GGanttBackground=this.ganttBackground));return f},_GotoSeletedDateActionHandler:function(b,
a,c){b=this.TZDateToTGDate(c.getTime());this._gotoPeriod(2,b)},_showDatePickerAction:function(b,a,c,d){this.closeDatePicker&&this.closeDatePicker();var g=this.userinfo.calendarConstraints,h=this.getVisibleMidDate();null!=a&&(h=this._findEarliestStartDate(a));h||(h=(new Date).getDate());var h=this.TGDateToTZDate(h),f=this,e;e=new c({lang:g.lang,lng:g.lng,dir:document.body.dir,constraints:g,value:h,maxHeight:"150",datePackage:g.datePackage,_close:function(){p.close(e);e.destroy();delete e},onChange:function(c){l.debug("OnChange: {}",
c);d(b,a,c);this._close()}});p.moveOffScreen(e);e.startup&&e.startup();this.closeDatePicker=function(){try{p.close(e)}catch(a){}f.DATE_SELECTION_IN_PROGRESS=!1};this.DATE_SELECTION_IN_PROGRESS=!0;p.open({popup:e,x:this.eventPageX,y:this.eventPageY})},onRefreshRequested:function(b){this._createUI()},OnGanttTip:function(b,a,c,d,g,h){var f;if("CRAFT"==a._OBJECTNAME||"AMCREWT"==a._OBJECTNAME)return null;"Run"===h&&g&&g.RunId&&(f=this.GetRowById(g.RunId));b=null;c=f.DAYINDEX%7;0==c&&(c=7);if(a=a["WEEK"+
f.WEEK+"_MODAVAILINFO"+c])if(a=JSON.parse(a),a.length&&1<a.length)b=this.label("multipleModAvail");else{var e;null!=this["gantt.MODAVAIL.tip.tpl"]&&(e=this["gantt.MODAVAIL.tip.tpl"],null==e||0==e.trim().length)&&(e="{reasonCode} / {start}-{finish}");f=Object.assign({},a[0]);null!=f.duration&&(a=this.doubleToDuration(f.duration,!1),f.duration=a);b=k.replace(e,k.hitch({row:f},this.__rowValFunc));if(null==b||0==b.trim().length)b=f.reasonCode+(" / "+start+"-"+finish)}else f.PATTERNDAYDESC&&(b=f.TEXT+
" = "+f.PATTERNDAYDESC);return b}})});
