define("dojo/_base/declare com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MaximoLog dojo/_base/lang ibm/miniapp/scheduler/gantt/GanttWidget com/ibm/tivoli/maximo/miniapps/Handlers dojo/json".split(" "),function(l,m,f,d,n,p,h){return l([n,m,p],{constructor:function(b){this.ViewName="WorkOrders"},OnGetDefaultColor:function(b,a,c,g,e,k){return"PM"!=a._OBJECTNAME||"0"!=a.ALLSEGMENTSMOVABLE&&"N"!=a.ALLSEGMENTSMOVABLE&&0!=a.ALLSEGMENTSMOVABLE?null:this._pmreforecastpendingBG},
OnValidatePMsegmentDrop:function(b,a,c){},addCustomActions:function(b){var a=this;window.Grids.FilterWork=function(b,g){if(!b.__FilterWorkData)return!0;var e=a._parseResources(g.Resources);if(!e)return!1;for(var k=e.split(","),f=0;f<b.__FilterWorkData.length;f++){if(e==b.__FilterWorkData[f])return!0;if(k&&1<k.length)for(var d=0;d<k.length;d++)if(a._parseResource(k[d])==b.__FilterWorkData[f])return!0}return!1};window.Grids.ZoomToWork=d.hitch(this,this.ZoomToWork)},_filterToSelected:function(b,a){var c=
this._GetSelectedRows(this.grid,"G",a);if(c&&0<c.length){f.debug("Filter to selected items being handled for {} rows",c.length);for(var g="",e=0;e<c.length;e++)0<g.length&&(g+=" OR "),g+='Identifier = "'+c[e].id+'"';this.grid.ActionClearFilters();this.grid.SetValue(this.grid.Toolbar,"Expression",g,1);this.grid.SearchRows("Filter");this.grid.ClearSelection();f.debug("Filtered to ",g)}},_lockAction:function(b,a){var c=this._GetSelectedRows(this.grid,"G",a);this._applyForEachRow(c,d.hitch(this,function(a){f.debug("before lock activity",
b.Value,a,a.MODAPPOINTMENT);var c=this.grid.GetRowById("toolbar");if(null==c||"0"==c.LOCKSCH)a.mxLeftIconClass="skd-icon-appointment";null!=c&&"1"!=c.LOCKSCH||delete a.mxLeftIconClass;"1"!=a.MODRESOURCELOCK||null!=c&&"0"!=c.LOCKRESOURCE||(a.mxLeftIconClass="skd-icon-appresourceloc");a.GGanttRunMove="All,Move,Selected,Entire,Vert,Mouse";a._READONLY_STARTEND=!0;this.SetValue(a,"MODAPPOINTMENT",!0,!0)}))},_unlockAction:function(b,a){var c=this._GetSelectedRows(this.grid,"G",a);this._applyForEachRow(c,
d.hitch(this,function(a){f.debug("before unlock activity",b.Value,a,a.MODAPPOINTMENT,a.APPTREQUIRED);"1"==a.APPTREQUIRED||"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?a.mxLeftIconClass="skd-icon-requirement":"1"==a.MODRESOURCELOCK&&"0"==tb.LOCKRESOURCE?a.mxLeftIconClass="skd-icon-resourceloc":delete a.mxLeftIconClass;delete a.GGanttRunMove;delete a._READONLY_STARTEND;this.SetValue(a,"MODAPPOINTMENT",!1,!0)}))},_reslockAction:function(b,a){var c=this._GetSelectedRows(this.grid,"G",
a);this._applyForEachRow(c,d.hitch(this,function(a){f.debug("before lock activity",b.Value,a,a.MODRESOURCELOCK);var c=this.grid.GetRowById("toolbar");if(null==c||"0"==c.LOCKRESOURCE)a.mxLeftIconClass="skd-icon-resourceloc";null!=c&&"1"!=c.LOCKRESOURCE||delete a.mxLeftIconClass;"1"!=a.MODAPPOINTMENT||null!=c&&"0"!=c.LOCKSCH||(a.mxLeftIconClass="skd-icon-appresourceloc");a.GGanttRunMove="All,Move,Selected,Entire,Slide,Mouse";a._READONLY_ASSIGNMENT=!0;this.SetValue(a,"MODRESOURCELOCK",!0,!0)}))},_resunlockAction:function(b,
a){var c=this._GetSelectedRows(this.grid,"G",a);this._applyForEachRow(c,d.hitch(this,function(a){f.debug("before unlock activity",b.Value,a,a.MODRESOURCELOCK,a.APPTREQUIRED);"1"==a.APPTREQUIRED||"Y"==a.APPTREQUIRED||1==a.APPTREQUIRED||"true"==a.APPTREQUIRED?a.mxLeftIconClass="skd-icon-requirement":"1"==a.MODAPPOINTMENT&&"0"==tb.LOCKSCH?a.mxLeftIconClass="skd-icon-appointment":delete a.mxLeftIconClass;delete a.GGanttRunMove;delete a._READONLY_ASSIGNMENT;this.SetValue(a,"MODRESOURCELOCK",!1,!0)}))},
attachExtraGridEvents:function(b){this.inherited(arguments);AddEvent("OnSelectGanttRunRect",b,d.hitch(this,this.OnSelectGanttObjects));f.debug("{} WorkView adding WorkView events",this.TAG);AddEvent("OnSelect",b,d.hitch(this,this._NotifyRowSelected));AddEvent("OnGetDefaultColor",this.gridId,d.hitch(this,this.OnGetDefaultColor));AddEvent("OnGanttChanged",this.gridId,function(a,b,e,f,d,h,l,m,n){a.ColorRow(b)});var a=this;AddEvent("OnAfterSectionResize",this.gridId,function(){a._onSyncRequest()});this.subscribeOn("skd.gantt.sync.request",
d.hitch(this,this._onSyncRequest));this.subscribeOn("skd.miniapp.topview.childsize",d.hitch(this,this._onChildSizeUpdate));this.subscribeOn("skd.resourceview.rowselected",d.hitch(this,this._onFilterWorkForResource));this.subscribeOn("skd.workview.constraintedited",d.hitch(this,this._constraintEdited));this.subscribeOn("skd.workview.refreshSelected",d.hitch(this,this.__refreshSelected))},OnZoom:function(b,a,c,g){this.inherited(arguments);this._otherGRID&&this._otherGRID.reloadRequired&&(this._otherGRID.reloadRequired=
!1,this._otherGRID._newGridID(),this._otherGRID._initGANTT())},upgradeTGInstance:function(b){this.inherited(arguments);this.grid._enableComplianceAction=d.hitch(this,this._enableComplianceAction);this.grid._disableComplianceAction=d.hitch(this,this._disableComplianceAction);this.grid._ReforecastPMAction=d.hitch(this,this._ReforecastPMAction);this.grid._enableFilterResourcesAction=d.hitch(this,this._enableFilterResourcesAction);this.grid._disableFilterResourcesAction=d.hitch(this,this._disableFilterResourcesAction)},
_constraintEdited:function(b){var a=h.parse(b);if(null==a)f.error("Unable to parse dependency item: {}",b);else{var c=this.grid.GetDependencies(a.from,"G",null,a.to);if(null==c)f.error("Failed to get dependencies for {}",a);else if(1!=c.length)f.error("Should only have a single dependency for {}",a,c);else{var g=this;this.doUpdate(function(b){f.debug("Will Update",c);if(c[0][2]==a.type&&c[0][3]==60*a.lag){b=a.optimize;var d=g.GetRowById(c[0][0]);g.SetValue(d,"_TG_DESENDANTS_EnforceLeadLag",d._TG_DESENDANTS+
"|"+b,null)}else b.DeleteDependencies(c),c[0][2]=a.type,c[0][3]=60*a.lag,b.AddDependencies(c)})}}},_onFilterWorkForResource:function(b){var a=b.grid.GetSelRows();if(!0===b.workFilterEnabled&&a&&0<a.length){b=[];for(var c=0;c<a.length;c++)b.push(a[c].name);this.grid.__FilterWorkData=b;f.debug("{}: Applying Work Filter",this.TAG,b);this.grid.SetFilter("work","Grids.FilterWork(Grid,Row)","Resources",2)}else f.debug("{}: Removing Work Filter",this.TAG),this.grid.SetFilter("work",null,"Resources",2),delete this.grid.__FilterWorkData},
_enableFilterResourcesAction:function(){f.debug("{} Enable Filter Resources",this.TAG);this._ResourceFilterEnabled=!0;this._NotifyRowSelected(this.grid,null)},_disableFilterResourcesAction:function(){f.debug("{} Disable Filter Resources",this.TAG);this._ResourceFilterEnabled=!1;this._NotifyRowSelected(this.grid,null)},_ReforecastPMAction:function(){f.debug("{} Reforecast PMs",this.TAG);var b=this;this.fetch("async_reforecast_pm",b._ioOptions({projectid:b.projectid})).then(function(){b.grid.ReloadBody(function(){})})},
_disableComplianceAction:function(){f.debug("disable compliance action");this.setCompliance(!1)},_enableComplianceAction:function(){f.debug("enable compliance action");this.setCompliance(!0)},setCompliance:function(b){var a=this;this.fetch("async_set_compliance",a._ioOptions({projectid:a.projectid,state:b})).then(function(){a.grid.ReloadBody(function(){})})},_onChildSizeUpdate:function(b){f.debug("{} Child Sizes ",this.TAG,b);var a=this,c=this;b&&b.pos&&require(["dojo/dom-geometry","dojo/dom-style"],
function(g,e){var f=g.position(a.domNode,!1),f=b.pos.x-f.x;g.setContentSize(c.domNode,{w:b.pos.w});e.set(c.domNode,{"margin-left":f+"px","margin-right":0,"padding-right":0})});b&&b.view&&(this.grid.MidWidth=b.view.grid.MidWidth)},OnAfterSave:function(b,a,c){this.inherited(arguments);0<=a&&this.publishLater("skd.workview.updated",{grid:b,result:a})},CanSelect:function(b){if(!b||!b.Visible||b.Hidden)return!1;if("rlassign"==this.appname&&this.lastMouseDownEvent){if(this.lastMouseDownEvent.ctrlKey)return b&&
"WORKORDER"===b._OBJECTNAME;if(this.lastMouseDownEvent.altKey)return b&&"ASSIGNMENT"===b._OBJECTNAME}return!0},OnSelectGanttObjects:function(b,a,c,g,e,d,h){f.debug("OnSelectGanttObjects:");c=this.getDateForX(c,"G");for(d=this.getDateForX(d,"G");null!=a;)if((a.startTime>=c&&a.startTime<=d||a.endTime>=c&&a.endTime<=d||a.startTime<c&&a.endTime>d)&&this.CanSelect(a)&&b.SelectRow(a,1),a=b.GetNext(a),a===e){(a.startTime>=c&&a.startTime<=d||a.endTime>=c&&a.endTime<=d||a.startTime<c&&a.endTime>d)&&this.CanSelect(a)&&
b.SelectRow(a,1);break}},_GetAltCSSClassForActivity:function(b){return"undefined"==b._INTERNALPLUSTQUALMET||"ASSIGNED"!=b._INTERNALSTATUS||null==b._INTERNALPLUSTQUALMET||"NONE"!=b._INTERNALPLUSTQUALMET&&"PARTIAL"!=b._INTERNALPLUSTQUALMET?null!=b.CRITICAL&&b.CRITICAL?cls="skd-CPM-highlight":this.inherited(arguments):cls="skd-Conflict"},_NotifyRowSelected:function(b,a,c,d,e,f,h,l){this.publishLater("skd.workview.rowselected",{grid:b,row:a,resourceFilterEnabled:this._ResourceFilterEnabled},100,"skd.workview.rowselected")},
_onSyncRequest:function(){f.debug("{} Sync Request Received; Sending Response.",this.TAG,this.grid);this.publishLater("skd.gantt.sync.response",{},50,"sync_request")},_autoRefreshData:function(b){this.fetch("async_auto_refresh_model",b._ioOptions({projectid:b.projectid})).then(function(a){if(a&&a.Changes&&a.Changes.length){f.debug("Model Refresh Reply",a);for(var c=a.Changes,d=[],e=0;e<c.length;e++)d.push(c[e].id);b.grid.AddDataFromServer(a);for(a=0;a<d.length;a++)e=b.grid.GetRowById(d[a]),e.name=
c[a].name,e._idx=c[a]._idx,e.mxRightIconClass=c[a].mxRightIconClass,e.mxLeftIconClass=c[a].mxLeftIconClass,e._OBJECTNAME=c[a]._OBJECTNAME,e._REFOBJECTNAME=c[a]._REFOBJECTNAME,e._INTERNALSTATUS=c[a]._INTERNALSTATUS,e.STATUS=c[a].STATUS;b.grid.RefreshGantt(1)}window.clearTimeout(window.timeoutId);window.timeoutId=setTimeout(function(){b._autoRefreshData(b)},b.dispatchRefreshInterval)})},__refreshSelected:function(b){var a=h.parse(b);if(a&&a.Changes&&a.Changes.length){var c=a.Changes;this.grid.AddDataFromServer(a);
for(a=0;a<c.length;a++){var d=c[a],e=this.grid.GetRowById(d.id);null!=e&&(e._INTERRUPTIBLE=d._INTERRUPTIBLE,e.INTERRUPTIBLE=d.INTERRUPTIBLE,e.MILESTONE=d.MILESTONE,e.WORKLOG=d.WORKLOG,this.grid.RefreshRow(e))}}this.publishLater("skd.workview.updated",{grid:this.grid,result:b.Result})}})});
