define("dojo/_base/lang dojo/_base/declare dojo/dom-geometry dojo/dom dojo/dom-style dojo/dom-attr dojo/_base/window dojo/Deferred dojo/dom-construct dojo/_base/array dojo/aspect dojo/window com/ibm/tivoli/maximo/miniapps/_MaximoIO com/ibm/tivoli/maximo/miniapps/_MiniApp com/ibm/tivoli/maximo/miniapps/_MaximoLog com/ibm/tivoli/maximo/miniapps/Handlers".split(" "),function(C,D,q,J,m,K,L,M,r,N,E,t,F,G,b,H){return D([F,G,H],{jsongraph:null,i18nJElabels:null,options:null,sizetoparentdomid:null,dom:null,
currentMode:"code",constructor:function(a){this.options=a;this.sizetoparentdomid=a.sizetoparentdomid;this.dom=a.dom?a.dom:this.domNode;a.loglevel&&(b.LOG_LEVEL=a.loglevel);b.debug("{} options",this.TAG,a)},startup:function(){this.inherited(arguments);this.createUI(null)},createUI:function(){this.dom||(dnode=this.domNode);b.debug("Creating JSONgraph UI");thisJGObjectObj=this;var a=r.create("div",{id:"jsonGraphId",width:"100%","margin-left":"20px"});r.place(a,this.domNode,"first");this.jsonEditorOptions();
thisJGObjectObj.fetch("getSymbologyConfig").then(function(a){var d=a.json;a=thisJGObjectObj.rootUrl+"/libraries/d3/d3.min.js";0==thisJGObjectObj.options.loglevel&&(a=thisJGObjectObj.rootUrl+"/libraries/d3/d3.js");require([a],function(a){thisJGObjectObj.jsongraph=thisJGObjectObj.createGraph(d)})});this._resize();E.after(window,"onresize",C.hitch(this,this._deferredResize))},resize:function(){this._resize()},_resize:function(){console.log("_resize occured");var a=this.onMeasure(),I=document.getElementById("jsonGraphId");
b.debug("{}: resize() called with measure",this.TAG,a);if(a&&(a.w||a.h)){a.w.replace("px","");var d=Number(a.h.replace("px",""));if(this.fillHeight){var h=t.getBox(),k=q.position(this.domNode);a.w=h.w-k.x-this.PAD-25+"px"}a.h=d-this.getHeightPad()+"px"}else a&&(a.width||a.height)?(a.width.replace("px",""),d=Number(a.height.replace("px","")),this.fillHeight&&(h=t.getBox(),k=q.position(this.domNode),a.width=h.w-k.x-this.PAD-25+"px"),a.height=d-this.getHeightPad()+"px"):b.warn("Failed to calculate size of miniapp??",
a);m.set(this.domNode,a);null!=I&&this.refreshData()},_removeOldEditor:function(){null!=this.jsongraph&&(b.debug("{} Cleaning up jsongraph",this.TAG),this.clearHandlers&&this.clearHandlers())},destroy:function(){this._removeOldEditor();this.inherited(arguments)},onRefreshRequested:function(a){b.debug("Refresh UI -- nothing to refresh");b.debug(a)},jsonEditorOptions:function(){return{mode:"code",modes:["code","form","text","tree","view"],onError:function(a){alert(a.toString())},onModeChange:function(a,
b){thisJGObjectObj.currentMode=a;console.log("Mode switched from",b,"to",a)}}},getHeightPad:function(){return 200},setDomStyle:function(a,b,d){m.set(a,d)},_deferredResize:function(){var a=this;setTimeout(function(){a._resize()},300)},refreshData:function(){},createGraph:function(a){function b(a,n){if("object"==typeof a)for(var d in a){var f=[],c=d,e=a[d];e.id?c=e.id:e.name?c=e.name:e.value?c=e.value:e.objectName&&(c=e.objectName);"find"!=c&&(b(e,f),n.push({name:c,children:f}))}else n.push({name:a})}
function d(a,n,b){if(a&&(n(a),a=b(a)))for(var f=a.length,c=0;c<f;c++)d(a[c],n,b)}function h(a){a.children&&(a._children=a.children,a._children.forEach(h),a.children=null)}function k(a){scale=u.scale();x=-a.y0;y=-a.x0;x=x*scale+v/2;y=y*scale+w/2;d3.select("g").transition().duration(750).attr("transform","translate("+x+","+y+")scale("+scale+")");u.scale(scale);u.translate([x,y])}function q(a){a.children?(a._children=a.children,a.children=null):a._children&&(a.children=a._children,a._children=null);
m(a);k(a)}function m(a){var b=[1],d=function(a,c){c.children&&0<c.children.length&&(b.length<=a+1&&b.push(0),b[a+1]+=c.children.length,c.children.forEach(function(b){d(a+1,b)}))};d(0,g);var f=50*d3.max(b);p=p.size([f,v]);var f=p.nodes(g).reverse(),c=p.links(f);f.forEach(function(a){a.y=10*a.depth*l;a.y=250*a.depth});node=A.selectAll("g.node").data(f,function(a){return a.id||(a.id=++t)});var e=node.enter().append("g").attr("class","node").attr("transform",function(O){return"translate("+a.y0+","+a.x0+
")"}).on("click",q);e.append("circle").attr("class","nodeCircle").attr("r",0).style("fill",function(a){return a._children?"lightsteelblue":"#fff"});e.append("text").attr("x",function(a){return a.children||a._children?-10:10}).attr("dy",".35em").attr("class","nodeText").attr("text-anchor",function(a){return a.children||a._children?"end":"start"}).text(function(a){return a.name}).style("fill-opacity",0);e.append("circle").attr("class","ghostCircle").attr("r",30).attr("opacity",.2).style("fill","red").attr("pointer-events",
"mouseover").on("mouseover",function(a){overCircle(a)}).on("mouseout",function(a){outCircle(a)});node.select("text").attr("x",function(a){return a.children||a._children?-10:10}).attr("text-anchor",function(a){return a.children||a._children?"end":"start"}).text(function(a){return a.name});node.select("circle.nodeCircle").attr("r",4.5).style("fill",function(a){return a._children?"lightsteelblue":"#fff"});node.transition().duration(750).attr("transform",function(a){return"translate("+a.y+","+a.x+")"}).select("text").style("fill-opacity",
1);e=node.exit().transition().duration(750).attr("transform",function(b){return"translate("+a.y+","+a.x+")"}).remove();e.select("circle").attr("r",0);e.select("text").style("fill-opacity",0);c=A.selectAll("path.link").data(c,function(a){return a.target.id});c.enter().insert("path","g").attr("class","link").attr("d",function(b){b={x:a.x0,y:a.y0};return B({source:b,target:b})});c.transition().duration(750).attr("d",B);c.exit().transition().duration(750).attr("d",function(b){b={x:a.x,y:a.y};return B({source:b,
target:b})}).remove();f.forEach(function(a){a.x0=a.x;a.y0=a.y})}var z=[];b(a,z);a=JSON.stringify(z);a=a.substr(1,a.length-2);a=JSON.parse(a);var r=0,l=0,t=0,g,v=this.domNode.clientWidth,w=this.domNode.clientHeight,p=d3.layout.tree().size([w,v]),B=d3.svg.diagonal().projection(function(a){return[a.y,a.x]});(function(){p.sort(function(a,b){return b.name.toString().toLowerCase()<a.name.toString().toLowerCase()?1:-1})})();var u=d3.behavior.zoom().scaleExtent([.1,3]).on("zoom",function(){A.attr("transform",
"translate("+d3.event.translate+")scale("+d3.event.scale+")")}),z=d3.select("#jsonGraphId").append("svg").attr("width",v).attr("height",w).attr("class","overlay").call(u);d(a,function(a){r++;var b=l;l=Math.max(a.name.length,l);isNaN(l)&&(l=b)},function(a){return a.children&&0<a.children.length?a.children:null});var A=z.append("g");g=a;g.x0=w;g.y0=0;g.children.forEach(function(a){h(a)});m(g);k(g)}})});
